FIRE      EQU $0
GRASS     EQU $1
LIGHTNING EQU $2
WATER     EQU $3
FIGHTING  EQU $4
PSYCHIC   EQU $5
COLORLESS EQU $6

FIRE_ENERGY_CARD             EQU $8
GRASS_ENERGY_CARD            EQU $9
LIGHTNING_ENERGY_CARD        EQU $A
WATER_ENERGY_CARD            EQU $B
FIGHTING_ENERGY_CARD         EQU $C
PSYCHIC_ENERGY_CARD          EQU $D
DOUBLE_COLORLESS_ENERGY_CARD EQU $E

TRAINER EQU $10
