
const_value = 1

TextOffsets:: ; 34000 (d:4000)
	db $00,$00,$00
	textpointer HandText
	textpointer CheckText
	textpointer AttackText
	textpointer PKMNPowerText
	textpointer DoneText
	textpointer TypeText
	textpointer RetreatText
	textpointer WeaknessText
	textpointer ResistanceText
	textpointer PKMNPWRText
	textpointer Text000b
	textpointer LengthText
	textpointer WeightText
	textpointer PokemonText
	textpointer Text000f
	textpointer lbsText
	textpointer Text0011
	textpointer Text0012
	textpointer Text0013
	textpointer Text0014
	textpointer Text0015
	textpointer Text0016
	textpointer Text0017
	textpointer Text0018
	textpointer Text0019
	textpointer Text001a
	textpointer Text001b
	textpointer Text001c
	textpointer Text001d
	textpointer Text001e
	textpointer Text001f
	textpointer Text0020
	textpointer Text0021
	textpointer Text0022
	textpointer NoPokemonOnTheBenchText
	textpointer UnableDueToSleepText
	textpointer UnableDueToParalysisText
	textpointer Received10DamageDueToPoisonText
	textpointer Received20DamageDueToPoisonText
	textpointer IsStillAsleepText
	textpointer IsCuredOfSleepText
	textpointer IsCuredOfParalysisText
	textpointer Text002b
	textpointer Text002c
	textpointer Text002d
	textpointer Text002e
	textpointer YesOrNoText
	textpointer DiscardName
	textpointer Text0031
	textpointer Text0032
	textpointer Text0033
	textpointer Text0034
	textpointer PokemonsAttackText
	textpointer Text0036
	textpointer Text0037
	textpointer Text0038
	textpointer Text0039
	textpointer Text003a
	textpointer Text003b
	textpointer NoSelectableAttackText
	textpointer UnableToRetreatText
	textpointer OnlyOneEnergyCardText
	textpointer Text003f
	textpointer Text0040
	textpointer DiscardDescription
	textpointer Text0042
	textpointer Text0043
	textpointer Text0044
	textpointer Text0045
	textpointer Text0046
	textpointer Text0047
	textpointer Text0048
	textpointer Text0049
	textpointer Text004a
	textpointer Text004b
	textpointer Text004c
	textpointer Text004d
	textpointer Text004e
	textpointer DamageToSelfDueToConfusionText
	textpointer Text0050
	textpointer Text0051
	textpointer Text0052
	textpointer Text0053
	textpointer Text0054
	textpointer TransmissionErrorText
	textpointer Text0056
	textpointer Text0057
	textpointer Text0058
	textpointer Text0059
	textpointer Text005a
	textpointer Text005b
	textpointer Text005c
	textpointer Text005d
	textpointer Text005e
	textpointer Text005f
	textpointer Text0060
	textpointer Text0061
	textpointer Text0062
	textpointer Text0063
	textpointer Text0064
	textpointer Text0065
	textpointer Text0066
	textpointer Text0067
	textpointer Text0068
	textpointer Text0069
	textpointer Text006a
	textpointer Text006b
	textpointer Text006c
	textpointer Text006d
	textpointer Text006e
	textpointer Text006f
	textpointer Text0070
	textpointer Text0071
	textpointer Text0072
	textpointer Text0073
	textpointer Text0074
	textpointer Text0075
	textpointer DecisionText
	textpointer DuelWasDrawText
	textpointer WonDuelText
	textpointer LostDuelText
	textpointer StartSuddenDeathMatchText
	textpointer Text007b
	textpointer Text007c
	textpointer Text007d
	textpointer Text007e
	textpointer Text007f
	textpointer Text0080
	textpointer WasKnockedOutText
	textpointer Text0082
	textpointer Text0083
	textpointer Text0084
	textpointer Text0085
	textpointer Text0086
	textpointer Text0087
	textpointer DuelistIsThinkingText
	textpointer Text0089
	textpointer Text008a
	textpointer Text008b
	textpointer Text008c
	textpointer Text008d
	textpointer Text008e
	textpointer Text008f
	textpointer Text0090
	textpointer Text0091
	textpointer Player2
	textpointer Text0093
	textpointer Text0094
	textpointer Text0095
	textpointer Text0096
	textpointer Text0097
	textpointer Text0098
	textpointer Text0099
	textpointer Text009a
	textpointer Text009b
	textpointer Text009c
	textpointer Text009d
	textpointer Text009e
	textpointer Text009f
	textpointer Text00a0
	textpointer Text00a1
	textpointer ResetBackUpRamText
	textpointer Text00a3
	textpointer NoCardsInHandText
	textpointer Text00a5
	textpointer Text00a6
	textpointer Text00a7
	textpointer Text00a8
	textpointer Text00a9
	textpointer Text00aa
	textpointer Text00ab
	textpointer Text00ac
	textpointer Text00ad
	textpointer Text00ae
	textpointer Text00af
	textpointer Text00b0
	textpointer Text00b1
	textpointer Text00b2
	textpointer Text00b3
	textpointer Text00b4
	textpointer Text00b5
	textpointer Text00b6
	textpointer Text00b7
	textpointer Text00b8
	textpointer Text00b9
	textpointer Text00ba
	textpointer Text00bb
	textpointer Text00bc
	textpointer Text00bd
	textpointer Text00be
	textpointer Text00bf
	textpointer NotEnoughEnergyCardsText
	textpointer Text00c1
	textpointer Text00c2
	textpointer Text00c3
	textpointer Text00c4
	textpointer Text00c5
	textpointer Text00c6
	textpointer Text00c7
	textpointer Text00c8
	textpointer Text00c9
	textpointer Text00ca
	textpointer CannotUseDueToStatusText
	textpointer Text00cc
	textpointer Text00cd
	textpointer Text00ce
	textpointer Text00cf
	textpointer Text00d0
	textpointer Text00d1
	textpointer Text00d2
	textpointer Text00d3
	textpointer UnableDueToToxicGasText
	textpointer Text00d5
	textpointer Text00d6
	textpointer Text00d7
	textpointer Text00d8
	textpointer Text00d9
	textpointer Text00da
	textpointer Text00db
	textpointer Text00dc
	textpointer Text00dd
	textpointer SandAttackCheckText
	textpointer SmokescreenCheckText
	textpointer ParalysisCheckText
	textpointer SleepCheckText
	textpointer PoisonCheckText
	textpointer ConfusionCheckText
	textpointer VenomPowderCheckText
	textpointer Text00e5
	textpointer Text00e6
	textpointer Text00e7
	textpointer Text00e8
	textpointer Text00e9
	textpointer Text00ea
	textpointer Text00eb
	textpointer Text00ec
	textpointer Text00ed
	textpointer Text00ee
	textpointer Text00ef
	textpointer Text00f0
	textpointer IfHeadsNoDamageNextTurnText
	textpointer Text00f2
	textpointer Text00f3
	textpointer Text00f4
	textpointer AcidCheckText
	textpointer Text00f6
	textpointer Text00f7
	textpointer Text00f8
	textpointer Text00f9
	textpointer Text00fa
	textpointer Text00fb
	textpointer Text00fc
	textpointer AttackUnsuccessfulText
	textpointer UnableToRetreatDueToAcidText
	textpointer UnableToUseTrainerDueToHeadacheText
	textpointer UnableToAttackDueToTailWagText
	textpointer UnableToAttackDueToLeerText
	textpointer UnableToAttackDueToBoneAttackText
	textpointer UnableToUseAttackDueToAmnesiaText
	textpointer KnockedOutDueToDestinyBondText
	textpointer ReceivesDamageDueToStrikesBackText
	textpointer UnableToEvolveDueToPrehistoricPowerText
	textpointer NoDamageOrEffectDueToFlyText
	textpointer NoDamageOrEffectDueToBarrierText
	textpointer NoDamageOrEffectDueToAgilityText
	textpointer UnableToUseAttackDueToNShieldText
	textpointer NoDamageOrEffectDueToNShieldText
	textpointer NoDamageOrEffectDueToTransparencyText
	textpointer Text010d
	textpointer SelectMonOnBenchToSwitchWithActiveText
	textpointer Text010f
	textpointer Text0110
	textpointer Text0111
	textpointer Text0112
	textpointer Text0113
	textpointer Text0114
	textpointer Text0115
	textpointer Text0116
	textpointer Text0117
	textpointer Text0118
	textpointer Text0119
	textpointer Text011a
	textpointer Text011b
	textpointer Text011c
	textpointer Text011d
	textpointer Text011e
	textpointer Text011f
	textpointer Text0120
	textpointer Text0121
	textpointer Text0122
	textpointer Text0123
	textpointer Text0124
	textpointer Text0125
	textpointer Text0126
	textpointer Text0127
	textpointer Text0128
	textpointer Text0129
	textpointer Text012a
	textpointer Text012b
	textpointer Text012c
	textpointer Text012d
	textpointer Text012e
	textpointer Text012f
	textpointer Text0130
	textpointer Text0131
	textpointer Text0132
	textpointer Text0133
	textpointer Text0134
	textpointer Text0135
	textpointer Text0136
	textpointer Text0137
	textpointer Text0138
	textpointer Text0139
	textpointer Text013a
	textpointer Text013b
	textpointer Text013c
	textpointer Text013d
	textpointer Text013e
	textpointer Text013f
	textpointer Text0140
	textpointer Text0141
	textpointer Text0142
	textpointer Text0143
	textpointer Text0144
	textpointer Text0145
	textpointer Text0146
	textpointer Text0147
	textpointer Text0148
	textpointer Text0149
	textpointer WasUnsuccessfulText
	textpointer Text014b
	textpointer Text014c
	textpointer Text014d
	textpointer Text014e
	textpointer Text014f
	textpointer Text0150
	textpointer Text0151
	textpointer Text0152
	textpointer Text0153
	textpointer Text0154
	textpointer Text0155
	textpointer Text0156
	textpointer Text0157
	textpointer Text0158
	textpointer Text0159
	textpointer Text015a
	textpointer Text015b
	textpointer Text015c
	textpointer Text015d
	textpointer Text015e
	textpointer Text015f
	textpointer Text0160
	textpointer Text0161
	textpointer Text0162
	textpointer Text0163
	textpointer Text0164
	textpointer Text0165
	textpointer Text0166
	textpointer Text0167
	textpointer Text0168
	textpointer Text0169
	textpointer Text016a
	textpointer Text016b
	textpointer Text016c
	textpointer Text016d
	textpointer Text016e
	textpointer Text016f
	textpointer Text0170
	textpointer Text0171
	textpointer Text0172
	textpointer Text0173
	textpointer Text0174
	textpointer Text0175
	textpointer Text0176
	textpointer Text0177
	textpointer Text0178
	textpointer Text0179
	textpointer Text017a
	textpointer Text017b
	textpointer Text017c
	textpointer Text017d
	textpointer Text017e
	textpointer Text017f
	textpointer Text0180
	textpointer Text0181
	textpointer Text0182
	textpointer Text0183
	textpointer Text0184
	textpointer Text0185
	textpointer Text0186
	textpointer Text0187
	textpointer Text0188
	textpointer Text0189
	textpointer Text018a
	textpointer Text018b
	textpointer Text018c
	textpointer Text018d
	textpointer Text018e
	textpointer ReceivedCardText
	textpointer ReceivedPromotionalCardText
	textpointer ReceivedLegendaryCardText
	textpointer ReceivedPromotionalFlyingPikachuText
	textpointer ReceivedPromotionalSurfingPikachuText
	textpointer Text0194
	textpointer Text0195
	textpointer Text0196
	textpointer Text0197
	textpointer Text0198
	textpointer Text0199
	textpointer Text019a
	textpointer Text019b
	textpointer Text019c
	textpointer Text019d
	textpointer Text019e
	textpointer Text019f
	textpointer Text01a0
	textpointer Text01a1
	textpointer Text01a2
	textpointer Text01a3
	textpointer Text01a4
	textpointer Text01a5
	textpointer Text01a6
	textpointer Text01a7
	textpointer Text01a8
	textpointer Text01a9
	textpointer Text01aa
	textpointer Text01ab
	textpointer Text01ac
	textpointer Text01ad
	textpointer Text01ae
	textpointer Text01af
	textpointer Text01b0
	textpointer Text01b1
	textpointer Text01b2
	textpointer Text01b3
	textpointer Text01b4
	textpointer Text01b5
	textpointer Text01b6
	textpointer Text01b7
	textpointer Text01b8
	textpointer Text01b9
	textpointer Text01ba
	textpointer Text01bb
	textpointer Text01bc
	textpointer Text01bd
	textpointer Text01be
	textpointer Text01bf
	textpointer Text01c0
	textpointer Text01c1
	textpointer Text01c2
	textpointer Text01c3
	textpointer Text01c4
	textpointer Text01c5
	textpointer Text01c6
	textpointer Text01c7
	textpointer Text01c8
	textpointer Text01c9
	textpointer Text01ca
	textpointer Text01cb
	textpointer Text01cc
	textpointer Text01cd
	textpointer Text01ce
	textpointer Text01cf
	textpointer Text01d0
	textpointer Text01d1
	textpointer Text01d2
	textpointer Text01d3
	textpointer Text01d4
	textpointer Text01d5
	textpointer Text01d6
	textpointer Text01d7
	textpointer Text01d8
	textpointer Text01d9
	textpointer Text01da
	textpointer Text01db
	textpointer Text01dc
	textpointer Text01dd
	textpointer PracticePlayerDeckName
	textpointer SamsPracticeDeckName
	textpointer CharmanderAndFriendsDeckName
	textpointer CharmanderExtraDeckName
	textpointer SquirtleAndFriendsDeckName
	textpointer SquirtleExtraDeckName
	textpointer BulbasaurAndFriendsDeckName
	textpointer BulbasaurExtraDeckName
	textpointer FirstStrikeDeckName
	textpointer RockCrusherDeckName
	textpointer GoGoRainDanceDeckName
	textpointer ZappingSelfdestructDeckName
	textpointer FlowerPowerDeckName
	textpointer StrangePsyshockDeckName
	textpointer WondersofScienceDeckName
	textpointer FireChargeDeckName
	textpointer LegendaryMoltresDeckName
	textpointer LegendaryZapdosDeckName
	textpointer LegendaryArticunoDeckName
	textpointer LegendaryDragoniteDeckName
	textpointer ImRonaldDeckName
	textpointer PowerfulRonaldDeckName
	textpointer InvincibleRonaldDeckName
	textpointer LegendaryRonaldDeckName
	textpointer WaterfrontPokemonDeckName
	textpointer LonelyFriendsDeckName
	textpointer SoundoftheWavesDeckName
	textpointer AngerDeckName
	textpointer FlamethrowerDeckName
	textpointer ReshuffleDeckName
	textpointer ExcavationDeckName
	textpointer BlisteringPokemonDeckName
	textpointer HardPokemonDeckName
	textpointer EtceteraDeckName
	textpointer FlowerGardenDeckName
	textpointer KaleidoscopeDeckName
	textpointer MusclesforBrainsDeckName
	textpointer HeatedBattleDeckName
	textpointer LovetoBattleDeckName
	textpointer PikachuDeckName
	textpointer BoomBoomSelfdestructDeckName
	textpointer PowerGeneratorDeckName
	textpointer GhostDeckName
	textpointer NapTimeDeckName
	textpointer StrangePowerDeckName
	textpointer FlyinPokemonDeckName
	textpointer LovelyNidoranDeckName
	textpointer PoisonDeckName
	textpointer ImakuniDeckName
	textpointer LightningAndFireDeckName
	textpointer WaterAndFightingDeckName
	textpointer GrassAndPsychicDeckName
	textpointer Text0212
	textpointer Text0213
	textpointer Text0214
	textpointer Text0215
	textpointer Text0216
	textpointer Text0217
	textpointer Text0218
	textpointer Text0219
	textpointer Text021a
	textpointer Text021b
	textpointer Text021c
	textpointer Text021d
	textpointer Text021e
	textpointer Text021f
	textpointer Text0220
	textpointer Text0221
	textpointer Text0222
	textpointer NewDeckText
	textpointer PleaseSelectDeckText
	textpointer Text0225
	textpointer Text0226
	textpointer Text0227
	textpointer Text0228
	textpointer Text0229
	textpointer ChosenAsDuelingDeckText
	textpointer Text022b
	textpointer Text022c
	textpointer Text022d
	textpointer Text022e
	textpointer ThereIsNoDeckHereText
	textpointer Text0230
	textpointer Text0231
	textpointer Text0232
	textpointer Text0233
	textpointer Text0234
	textpointer Text0235
	textpointer Text0236
	textpointer Text0237
	textpointer Text0238
	textpointer Text0239
	textpointer Text023a
	textpointer Text023b
	textpointer Text023c
	textpointer Text023d
	textpointer Text023e
	textpointer Text023f
	textpointer Text0240
	textpointer Text0241
	textpointer Text0242
	textpointer Text0243
	textpointer Text0244
	textpointer Text0245
	textpointer Text0246
	textpointer Text0247
	textpointer Text0248
	textpointer Text0249
	textpointer Text024a
	textpointer Text024b
	textpointer Text024c
	textpointer Text024d
	textpointer Text024e
	textpointer Text024f
	textpointer Text0250
	textpointer Text0251
	textpointer Text0252
	textpointer Text0253
	textpointer Text0254
	textpointer Text0255
	textpointer Text0256
	textpointer Text0257
	textpointer Text0258
	textpointer Text0259
	textpointer Text025a
	textpointer Text025b
	textpointer Text025c
	textpointer Text025d
	textpointer Text025e
	textpointer Text025f
	textpointer Text0260
	textpointer Text0261
	textpointer Text0262
	textpointer Text0263
	textpointer Text0264
	textpointer Text0265
	textpointer Text0266
	textpointer Text0267
	textpointer Text0268
	textpointer Text0269
	textpointer Text026a
	textpointer Text026b
	textpointer Text026c
	textpointer Text026d
	textpointer Text026e
	textpointer Text026f
	textpointer Text0270
	textpointer Text0271
	textpointer Text0272
	textpointer Text0273
	textpointer Text0274
	textpointer Text0275
	textpointer Text0276
	textpointer Text0277
	textpointer Text0278
	textpointer Text0279
	textpointer Text027a
	textpointer Text027b
	textpointer Text027c
	textpointer Text027d
	textpointer Text027e
	textpointer Text027f
	textpointer Text0280
	textpointer Text0281
	textpointer Text0282
	textpointer Text0283
	textpointer Text0284
	textpointer Text0285
	textpointer Text0286
	textpointer Text0287
	textpointer Text0288
	textpointer Text0289
	textpointer Text028a
	textpointer Text028b
	textpointer Text028c
	textpointer Text028d
	textpointer Text028e
	textpointer Text028f
	textpointer Text0290
	textpointer Text0291
	textpointer Text0292
	textpointer Text0293
	textpointer Text0294
	textpointer Text0295
	textpointer Text0296
	textpointer Text0297
	textpointer Text0298
	textpointer Text0299
	textpointer Text029a
	textpointer Text029b
	textpointer Text029c
	textpointer Text029d
	textpointer Text029e
	textpointer Text029f
	textpointer Text02a0
	textpointer Text02a1
	textpointer Text02a2
	textpointer Text02a3
	textpointer Text02a4
	textpointer Text02a5
	textpointer Text02a6
	textpointer Text02a7
	textpointer Text02a8
	textpointer Text02a9
	textpointer Text02aa
	textpointer Text02ab
	textpointer Text02ac
	textpointer Text02ad
	textpointer Text02ae
	textpointer Text02af
	textpointer Text02b0
	textpointer Text02b1
	textpointer Text02b2
	textpointer Text02b3
	textpointer Text02b4
	textpointer Text02b5
	textpointer Text02b6
	textpointer Text02b7
	textpointer Text02b8
	textpointer Text02b9
	textpointer Text02ba
	textpointer Text02bb
	textpointer Text02bc
	textpointer Text02bd
	textpointer Text02be
	textpointer Text02bf
	textpointer Text02c0
	textpointer Text02c1
	textpointer Text02c2
	textpointer Text02c3
	textpointer Text02c4
	textpointer Text02c5
	textpointer Text02c6
	textpointer Text02c7
	textpointer Text02c8
	textpointer Text02c9
	textpointer Text02ca
	textpointer Text02cb
	textpointer Text02cc
	textpointer Text02cd
	textpointer Text02ce
	textpointer Text02cf
	textpointer Text02d0
	textpointer Text02d1
	textpointer Text02d2
	textpointer Text02d3
	textpointer Text02d4
	textpointer Text02d5
	textpointer Text02d6
	textpointer Text02d7
	textpointer Text02d8
	textpointer Text02d9
	textpointer Text02da
	textpointer Text02db
	textpointer Text02dc
	textpointer Text02dd
	textpointer Text02de
	textpointer Text02df
	textpointer Text02e0
	textpointer Text02e1
	textpointer Text02e2
	textpointer Text02e3
	textpointer Text02e4
	textpointer Text02e5
	textpointer Text02e6
	textpointer Text02e7
	textpointer Text02e8
	textpointer Text02e9
	textpointer Text02ea
	textpointer Text02eb
	textpointer Text02ec
	textpointer Text02ed
	textpointer Text02ee
	textpointer Text02ef
	textpointer Text02f0
	textpointer Text02f1
	textpointer Text02f2
	textpointer Text02f3
	textpointer Text02f4
	textpointer Text02f5
	textpointer Text02f6
	textpointer Text02f7
	textpointer Text02f8
	textpointer Text02f9
	textpointer Text02fa
	textpointer Text02fb
	textpointer Text02fc
	textpointer Text02fd
	textpointer Text02fe
	textpointer Text02ff
	textpointer Text0300
	textpointer Text0301
	textpointer Text0302
	textpointer Text0303
	textpointer Text0304
	textpointer Text0305
	textpointer Text0306
	textpointer Text0307
	textpointer Text0308
	textpointer Text0309
	textpointer Text030a
	textpointer Text030b
	textpointer Text030c
	textpointer Text030d
	textpointer Text030e
	textpointer Text030f
	textpointer Text0310
	textpointer Text0311
	textpointer Text0312
	textpointer Text0313
	textpointer Text0314
	textpointer Text0315
	textpointer Text0316
	textpointer Text0317
	textpointer Text0318
	textpointer Text0319
	textpointer Text031a
	textpointer Text031b
	textpointer Text031c
	textpointer Text031d
	textpointer Text031e
	textpointer Text031f
	textpointer Text0320
	textpointer Text0321
	textpointer Text0322
	textpointer Text0323
	textpointer Text0324
	textpointer Text0325
	textpointer Text0326
	textpointer Text0327
	textpointer Text0328
	textpointer Text0329
	textpointer Text032a
	textpointer Text032b
	textpointer Text032c
	textpointer Text032d
	textpointer Text032e
	textpointer Text032f
	textpointer Text0330
	textpointer Text0331
	textpointer Text0332
	textpointer Text0333
	textpointer Text0334
	textpointer Text0335
	textpointer Text0336
	textpointer Text0337
	textpointer Text0338
	textpointer Text0339
	textpointer Text033a
	textpointer Text033b
	textpointer Text033c
	textpointer Text033d
	textpointer Text033e
	textpointer Text033f
	textpointer Text0340
	textpointer Text0341
	textpointer Text0342
	textpointer Text0343
	textpointer Text0344
	textpointer Text0345
	textpointer Text0346
	textpointer Text0347
	textpointer Text0348
	textpointer Text0349
	textpointer Text034a
	textpointer Text034b
	textpointer Text034c
	textpointer Text034d
	textpointer Text034e
	textpointer Text034f
	textpointer Text0350
	textpointer Text0351
	textpointer TurnedPCOnText
	textpointer TurnedPCOffText
	textpointer Text0354
	textpointer Text0355
	textpointer Text0356
	textpointer Text0357
	textpointer Text0358
	textpointer Text0359
	textpointer Text035a
	textpointer Text035b
	textpointer Text035c
	textpointer Text035d
	textpointer Text035e
	textpointer Text035f
	textpointer Text0360
	textpointer Text0361
	textpointer Text0362
	textpointer Text0363
	textpointer Text0364
	textpointer Text0365
	textpointer Text0366
	textpointer Text0367
	textpointer Text0368
	textpointer Text0369
	textpointer Text036a
	textpointer Text036b
	textpointer Text036c
	textpointer Text036d
	textpointer Text036e
	textpointer Text036f
	textpointer Text0370
	textpointer Text0371
	textpointer Text0372
	textpointer Text0373
	textpointer Text0374
	textpointer Text0375
	textpointer Text0376
	textpointer Text0377
	textpointer Text0378
	textpointer Text0379
	textpointer Text037a
	textpointer Text037b
	textpointer Text037c
	textpointer Text037d
	textpointer Text037e
	textpointer Text037f
	textpointer Text0380
	textpointer Text0381
	textpointer Text0382
	textpointer Text0383
	textpointer Text0384
	textpointer Text0385
	textpointer Text0386
	textpointer ReceivedBoosterPackText
	textpointer AndAnotherBoosterPackText
	textpointer CheckedCardsInBoosterPackText
	textpointer Text038a
	textpointer WonTheMedalText
	textpointer Text038c
	textpointer Text038d
	textpointer Text038e
	textpointer Text038f
	textpointer Text0390
	textpointer Text0391
	textpointer Text0392
	textpointer Text0393
	textpointer Text0394
	textpointer Text0395
	textpointer Text0396
	textpointer Text0397
	textpointer Text0398
	textpointer Text0399
	textpointer Text039a
	textpointer Text039b
	textpointer Text039c
	textpointer Text039d
	textpointer Text039e
	textpointer Text039f
	textpointer Text03a0
	textpointer Text03a1
	textpointer Text03a2
	textpointer Text03a3
	textpointer Text03a4
	textpointer Text03a5
	textpointer Text03a6
	textpointer Text03a7
	textpointer Text03a8
	textpointer Text03a9
	textpointer Text03aa
	textpointer Text03ab
	textpointer Text03ac
	textpointer Text03ad
	textpointer Text03ae
	textpointer Text03af
	textpointer Text03b0
	textpointer Text03b1
	textpointer Text03b2
	textpointer Text03b3
	textpointer Text03b4
	textpointer Text03b5
	textpointer Text03b6
	textpointer Text03b7
	textpointer Text03b8
	textpointer Text03b9
	textpointer Text03ba
	textpointer Text03bb
	textpointer Text03bc
	textpointer Text03bd
	textpointer Text03be
	textpointer Text03bf
	textpointer Text03c0
	textpointer Text03c1
	textpointer Text03c2
	textpointer Text03c3
	textpointer Text03c4
	textpointer Text03c5
	textpointer Text03c6
	textpointer Text03c7
	textpointer Text03c8
	textpointer Text03c9
	textpointer Text03ca
	textpointer Text03cb
	textpointer Text03cc
	textpointer Text03cd
	textpointer Text03ce
	textpointer Text03cf
	textpointer Text03d0
	textpointer Text03d1
	textpointer Text03d2
	textpointer Text03d3
	textpointer Text03d4
	textpointer Text03d5
	textpointer Text03d6
	textpointer Text03d7
	textpointer Text03d8
	textpointer Text03d9
	textpointer Text03da
	textpointer Text03db
	textpointer Text03dc
	textpointer Text03dd
	textpointer Text03de
	textpointer Text03df
	textpointer Text03e0
	textpointer Text03e1
	textpointer Text03e2
	textpointer Text03e3
	textpointer Text03e4
	textpointer Text03e5
	textpointer Text03e6
	textpointer Text03e7
	textpointer Text03e8
	textpointer Text03e9
	textpointer Text03ea
	textpointer Text03eb
	textpointer Text03ec
	textpointer Text03ed
	textpointer Text03ee
	textpointer Text03ef
	textpointer Text03f0
	textpointer Text03f1
	textpointer Text03f2
	textpointer Text03f3
	textpointer Text03f4
	textpointer Text03f5
	textpointer Text03f6
	textpointer Text03f7
	textpointer Text03f8
	textpointer Text03f9
	textpointer Text03fa
	textpointer Text03fb
	textpointer Text03fc
	textpointer Text03fd
	textpointer Text03fe
	textpointer Text03ff
	textpointer Text0400
	textpointer Text0401
	textpointer Text0402
	textpointer Text0403
	textpointer Text0404
	textpointer Text0405
	textpointer Text0406
	textpointer Text0407
	textpointer Text0408
	textpointer Text0409
	textpointer Text040a
	textpointer Text040b
	textpointer Text040c
	textpointer Text040d
	textpointer Text040e
	textpointer Text040f
	textpointer Text0410
	textpointer Text0411
	textpointer Text0412
	textpointer Text0413
	textpointer Text0414
	textpointer Text0415
	textpointer Text0416
	textpointer Text0417
	textpointer Text0418
	textpointer Text0419
	textpointer Text041a
	textpointer Text041b
	textpointer Text041c
	textpointer Text041d
	textpointer Text041e
	textpointer Text041f
	textpointer Text0420
	textpointer Text0421
	textpointer Text0422
	textpointer Text0423
	textpointer Text0424
	textpointer Text0425
	textpointer Text0426
	textpointer Text0427
	textpointer Text0428
	textpointer Text0429
	textpointer Text042a
	textpointer Text042b
	textpointer Text042c
	textpointer Text042d
	textpointer Text042e
	textpointer Text042f
	textpointer Text0430
	textpointer Text0431
	textpointer Text0432
	textpointer Text0433
	textpointer Text0434
	textpointer Text0435
	textpointer Text0436
	textpointer Text0437
	textpointer Text0438
	textpointer Text0439
	textpointer Text043a
	textpointer Text043b
	textpointer Text043c
	textpointer Text043d
	textpointer Text043e
	textpointer Text043f
	textpointer Text0440
	textpointer Text0441
	textpointer Text0442
	textpointer Text0443
	textpointer Text0444
	textpointer Text0445
	textpointer Text0446
	textpointer Text0447
	textpointer Text0448
	textpointer Text0449
	textpointer Text044a
	textpointer Text044b
	textpointer Text044c
	textpointer Text044d
	textpointer Text044e
	textpointer Text044f
	textpointer Text0450
	textpointer Text0451
	textpointer Text0452
	textpointer Text0453
	textpointer Text0454
	textpointer Text0455
	textpointer Text0456
	textpointer Text0457
	textpointer Text0458
	textpointer Text0459
	textpointer Text045a
	textpointer Text045b
	textpointer Text045c
	textpointer Text045d
	textpointer Text045e
	textpointer Text045f
	textpointer Text0460
	textpointer Text0461
	textpointer Text0462
	textpointer Text0463
	textpointer Text0464
	textpointer Text0465
	textpointer Text0466
	textpointer Text0467
	textpointer Text0468
	textpointer Text0469
	textpointer Text046a
	textpointer Text046b
	textpointer Text046c
	textpointer Text046d
	textpointer Text046e
	textpointer Text046f
	textpointer Text0470
	textpointer Text0471
	textpointer Text0472
	textpointer Text0473
	textpointer Text0474
	textpointer Text0475
	textpointer Text0476
	textpointer Text0477
	textpointer Text0478
	textpointer Text0479
	textpointer Text047a
	textpointer Text047b
	textpointer Text047c
	textpointer Text047d
	textpointer Text047e
	textpointer Text047f
	textpointer Text0480
	textpointer Text0481
	textpointer Text0482
	textpointer Text0483
	textpointer Text0484
	textpointer Text0485
	textpointer Text0486
	textpointer Text0487
	textpointer Text0488
	textpointer Text0489
	textpointer Text048a
	textpointer Text048b
	textpointer Text048c
	textpointer Text048d
	textpointer Text048e
	textpointer Text048f
	textpointer Text0490
	textpointer Text0491
	textpointer Text0492
	textpointer Text0493
	textpointer Text0494
	textpointer Text0495
	textpointer Text0496
	textpointer Text0497
	textpointer Text0498
	textpointer Text0499
	textpointer Text049a
	textpointer Text049b
	textpointer Text049c
	textpointer Text049d
	textpointer Text049e
	textpointer Text049f
	textpointer Text04a0
	textpointer Text04a1
	textpointer Text04a2
	textpointer Text04a3
	textpointer Text04a4
	textpointer Text04a5
	textpointer Text04a6
	textpointer Text04a7
	textpointer Text04a8
	textpointer Text04a9
	textpointer Text04aa
	textpointer Text04ab
	textpointer Text04ac
	textpointer Text04ad
	textpointer Text04ae
	textpointer Text04af
	textpointer Text04b0
	textpointer Text04b1
	textpointer Text04b2
	textpointer Text04b3
	textpointer Text04b4
	textpointer Text04b5
	textpointer Text04b6
	textpointer Text04b7
	textpointer Text04b8
	textpointer Text04b9
	textpointer Text04ba
	textpointer Text04bb
	textpointer Text04bc
	textpointer Text04bd
	textpointer Text04be
	textpointer Text04bf
	textpointer Text04c0
	textpointer Text04c1
	textpointer Text04c2
	textpointer Text04c3
	textpointer Text04c4
	textpointer Text04c5
	textpointer Text04c6
	textpointer Text04c7
	textpointer Text04c8
	textpointer Text04c9
	textpointer Text04ca
	textpointer Text04cb
	textpointer Text04cc
	textpointer Text04cd
	textpointer Text04ce
	textpointer Text04cf
	textpointer Text04d0
	textpointer Text04d1
	textpointer Text04d2
	textpointer Text04d3
	textpointer Text04d4
	textpointer Text04d5
	textpointer Text04d6
	textpointer Text04d7
	textpointer Text04d8
	textpointer Text04d9
	textpointer Text04da
	textpointer Text04db
	textpointer Text04dc
	textpointer Text04dd
	textpointer Text04de
	textpointer Text04df
	textpointer Text04e0
	textpointer Text04e1
	textpointer Text04e2
	textpointer Text04e3
	textpointer Text04e4
	textpointer Text04e5
	textpointer Text04e6
	textpointer Text04e7
	textpointer Text04e8
	textpointer Text04e9
	textpointer Text04ea
	textpointer Text04eb
	textpointer Text04ec
	textpointer Text04ed
	textpointer Text04ee
	textpointer Text04ef
	textpointer Text04f0
	textpointer Text04f1
	textpointer Text04f2
	textpointer Text04f3
	textpointer Text04f4
	textpointer Text04f5
	textpointer Text04f6
	textpointer Text04f7
	textpointer Text04f8
	textpointer Text04f9
	textpointer Text04fa
	textpointer Text04fb
	textpointer Text04fc
	textpointer Text04fd
	textpointer Text04fe
	textpointer Text04ff
	textpointer Text0500
	textpointer Text0501
	textpointer Text0502
	textpointer Text0503
	textpointer Text0504
	textpointer Text0505
	textpointer Text0506
	textpointer Text0507
	textpointer Text0508
	textpointer Text0509
	textpointer Text050a
	textpointer Text050b
	textpointer Text050c
	textpointer Text050d
	textpointer Text050e
	textpointer Text050f
	textpointer Text0510
	textpointer Text0511
	textpointer Text0512
	textpointer Text0513
	textpointer Text0514
	textpointer Text0515
	textpointer Text0516
	textpointer Text0517
	textpointer Text0518
	textpointer Text0519
	textpointer Text051a
	textpointer Text051b
	textpointer Text051c
	textpointer Text051d
	textpointer Text051e
	textpointer Text051f
	textpointer Text0520
	textpointer Text0521
	textpointer Text0522
	textpointer Text0523
	textpointer Text0524
	textpointer Text0525
	textpointer Text0526
	textpointer Text0527
	textpointer Text0528
	textpointer Text0529
	textpointer Text052a
	textpointer Text052b
	textpointer Text052c
	textpointer Text052d
	textpointer Text052e
	textpointer Text052f
	textpointer Text0530
	textpointer Text0531
	textpointer Text0532
	textpointer Text0533
	textpointer Text0534
	textpointer Text0535
	textpointer Text0536
	textpointer Text0537
	textpointer Text0538
	textpointer Text0539
	textpointer Text053a
	textpointer Text053b
	textpointer Text053c
	textpointer Text053d
	textpointer Text053e
	textpointer Text053f
	textpointer Text0540
	textpointer Text0541
	textpointer Text0542
	textpointer Text0543
	textpointer Text0544
	textpointer Text0545
	textpointer Text0546
	textpointer Text0547
	textpointer Text0548
	textpointer Text0549
	textpointer Text054a
	textpointer Text054b
	textpointer Text054c
	textpointer Text054d
	textpointer Text054e
	textpointer Text054f
	textpointer Text0550
	textpointer Text0551
	textpointer Text0552
	textpointer Text0553
	textpointer Text0554
	textpointer Text0555
	textpointer Text0556
	textpointer Text0557
	textpointer Text0558
	textpointer Text0559
	textpointer Text055a
	textpointer Text055b
	textpointer Text055c
	textpointer Text055d
	textpointer Text055e
	textpointer Text055f
	textpointer Text0560
	textpointer Text0561
	textpointer Text0562
	textpointer Text0563
	textpointer Text0564
	textpointer Text0565
	textpointer Text0566
	textpointer Text0567
	textpointer Text0568
	textpointer Text0569
	textpointer Text056a
	textpointer Text056b
	textpointer Text056c
	textpointer Text056d
	textpointer Text056e
	textpointer Text056f
	textpointer Text0570
	textpointer Text0571
	textpointer Text0572
	textpointer Text0573
	textpointer Text0574
	textpointer Text0575
	textpointer Text0576
	textpointer Text0577
	textpointer Text0578
	textpointer Text0579
	textpointer Text057a
	textpointer Text057b
	textpointer Text057c
	textpointer Text057d
	textpointer Text057e
	textpointer Text057f
	textpointer Text0580
	textpointer Text0581
	textpointer Text0582
	textpointer Text0583
	textpointer Text0584
	textpointer Text0585
	textpointer Text0586
	textpointer Text0587
	textpointer Text0588
	textpointer Text0589
	textpointer Text058a
	textpointer Text058b
	textpointer Text058c
	textpointer Text058d
	textpointer Text058e
	textpointer Text058f
	textpointer Text0590
	textpointer Text0591
	textpointer Text0592
	textpointer Text0593
	textpointer Text0594
	textpointer Text0595
	textpointer Text0596
	textpointer Text0597
	textpointer Text0598
	textpointer Text0599
	textpointer Text059a
	textpointer Text059b
	textpointer Text059c
	textpointer Text059d
	textpointer Text059e
	textpointer Text059f
	textpointer Text05a0
	textpointer Text05a1
	textpointer Text05a2
	textpointer Text05a3
	textpointer Text05a4
	textpointer Text05a5
	textpointer Text05a6
	textpointer Text05a7
	textpointer Text05a8
	textpointer Text05a9
	textpointer Text05aa
	textpointer Text05ab
	textpointer Text05ac
	textpointer Text05ad
	textpointer Text05ae
	textpointer Text05af
	textpointer Text05b0
	textpointer Text05b1
	textpointer Text05b2
	textpointer Text05b3
	textpointer Text05b4
	textpointer Text05b5
	textpointer Text05b6
	textpointer Text05b7
	textpointer Text05b8
	textpointer Text05b9
	textpointer Text05ba
	textpointer Text05bb
	textpointer Text05bc
	textpointer Text05bd
	textpointer Text05be
	textpointer Text05bf
	textpointer Text05c0
	textpointer Text05c1
	textpointer Text05c2
	textpointer Text05c3
	textpointer Text05c4
	textpointer Text05c5
	textpointer Text05c6
	textpointer Text05c7
	textpointer Text05c8
	textpointer Text05c9
	textpointer Text05ca
	textpointer Text05cb
	textpointer Text05cc
	textpointer Text05cd
	textpointer Text05ce
	textpointer Text05cf
	textpointer Text05d0
	textpointer Text05d1
	textpointer Text05d2
	textpointer Text05d3
	textpointer Text05d4
	textpointer Text05d5
	textpointer Text05d6
	textpointer Text05d7
	textpointer Text05d8
	textpointer Text05d9
	textpointer Text05da
	textpointer Text05db
	textpointer Text05dc
	textpointer Text05dd
	textpointer Text05de
	textpointer Text05df
	textpointer Text05e0
	textpointer Text05e1
	textpointer Text05e2
	textpointer Text05e3
	textpointer Text05e4
	textpointer Text05e5
	textpointer Text05e6
	textpointer Text05e7
	textpointer Text05e8
	textpointer Text05e9
	textpointer Text05ea
	textpointer Text05eb
	textpointer Text05ec
	textpointer Text05ed
	textpointer Text05ee
	textpointer Text05ef
	textpointer Text05f0
	textpointer Text05f1
	textpointer Text05f2
	textpointer Text05f3
	textpointer Text05f4
	textpointer Text05f5
	textpointer Text05f6
	textpointer Text05f7
	textpointer Text05f8
	textpointer Text05f9
	textpointer Text05fa
	textpointer Text05fb
	textpointer Text05fc
	textpointer Text05fd
	textpointer Text05fe
	textpointer Text05ff
	textpointer Text0600
	textpointer Text0601
	textpointer Text0602
	textpointer Text0603
	textpointer Text0604
	textpointer Text0605
	textpointer Text0606
	textpointer Text0607
	textpointer Text0608
	textpointer Text0609
	textpointer Text060a
	textpointer Text060b
	textpointer Text060c
	textpointer Text060d
	textpointer Text060e
	textpointer Text060f
	textpointer Text0610
	textpointer Text0611
	textpointer Text0612
	textpointer Text0613
	textpointer Text0614
	textpointer Text0615
	textpointer Text0616
	textpointer Text0617
	textpointer Text0618
	textpointer Text0619
	textpointer Text061a
	textpointer Text061b
	textpointer Text061c
	textpointer Text061d
	textpointer Text061e
	textpointer Text061f
	textpointer Text0620
	textpointer Text0621
	textpointer Text0622
	textpointer Text0623
	textpointer Text0624
	textpointer Text0625
	textpointer Text0626
	textpointer Text0627
	textpointer Text0628
	textpointer Text0629
	textpointer Text062a
	textpointer Text062b
	textpointer Text062c
	textpointer Text062d
	textpointer Text062e
	textpointer Text062f
	textpointer Text0630
	textpointer Text0631
	textpointer Text0632
	textpointer Text0633
	textpointer Text0634
	textpointer Text0635
	textpointer Text0636
	textpointer Text0637
	textpointer Text0638
	textpointer Text0639
	textpointer Text063a
	textpointer Text063b
	textpointer Text063c
	textpointer Text063d
	textpointer Text063e
	textpointer Text063f
	textpointer Text0640
	textpointer Text0641
	textpointer Text0642
	textpointer Text0643
	textpointer Text0644
	textpointer Text0645
	textpointer Text0646
	textpointer Text0647
	textpointer Text0648
	textpointer Text0649
	textpointer Text064a
	textpointer Text064b
	textpointer Text064c
	textpointer Text064d
	textpointer Text064e
	textpointer Text064f
	textpointer Text0650
	textpointer Text0651
	textpointer Text0652
	textpointer Text0653
	textpointer Text0654
	textpointer Text0655
	textpointer Text0656
	textpointer Text0657
	textpointer Text0658
	textpointer Text0659
	textpointer Text065a
	textpointer Text065b
	textpointer Text065c
	textpointer Text065d
	textpointer Text065e
	textpointer Text065f
	textpointer Text0660
	textpointer Text0661
	textpointer Text0662
	textpointer Text0663
	textpointer Text0664
	textpointer Text0665
	textpointer Text0666
	textpointer Text0667
	textpointer Text0668
	textpointer Text0669
	textpointer Text066a
	textpointer Text066b
	textpointer Text066c
	textpointer Text066d
	textpointer Text066e
	textpointer Text066f
	textpointer Text0670
	textpointer Text0671
	textpointer Text0672
	textpointer Text0673
	textpointer Text0674
	textpointer Text0675
	textpointer Text0676
	textpointer Text0677
	textpointer Text0678
	textpointer Text0679
	textpointer Text067a
	textpointer Text067b
	textpointer Text067c
	textpointer Text067d
	textpointer Text067e
	textpointer Text067f
	textpointer Text0680
	textpointer Text0681
	textpointer Text0682
	textpointer Text0683
	textpointer Text0684
	textpointer Text0685
	textpointer Text0686
	textpointer Text0687
	textpointer Text0688
	textpointer Text0689
	textpointer Text068a
	textpointer Text068b
	textpointer Text068c
	textpointer Text068d
	textpointer Text068e
	textpointer Text068f
	textpointer Text0690
	textpointer Text0691
	textpointer Text0692
	textpointer Text0693
	textpointer Text0694
	textpointer Text0695
	textpointer Text0696
	textpointer Text0697
	textpointer Text0698
	textpointer Text0699
	textpointer Text069a
	textpointer Text069b
	textpointer Text069c
	textpointer Text069d
	textpointer Text069e
	textpointer Text069f
	textpointer Text06a0
	textpointer Text06a1
	textpointer Text06a2
	textpointer Text06a3
	textpointer Text06a4
	textpointer Text06a5
	textpointer Text06a6
	textpointer Text06a7
	textpointer Text06a8
	textpointer Text06a9
	textpointer Text06aa
	textpointer Text06ab
	textpointer Text06ac
	textpointer Text06ad
	textpointer Text06ae
	textpointer Text06af
	textpointer Text06b0
	textpointer Text06b1
	textpointer Text06b2
	textpointer Text06b3
	textpointer Text06b4
	textpointer Text06b5
	textpointer Text06b6
	textpointer Text06b7
	textpointer Text06b8
	textpointer Text06b9
	textpointer Text06ba
	textpointer Text06bb
	textpointer Text06bc
	textpointer Text06bd
	textpointer Text06be
	textpointer Text06bf
	textpointer Text06c0
	textpointer Text06c1
	textpointer Text06c2
	textpointer Text06c3
	textpointer Text06c4
	textpointer Text06c5
	textpointer Text06c6
	textpointer Text06c7
	textpointer Text06c8
	textpointer Text06c9
	textpointer Text06ca
	textpointer Text06cb
	textpointer Text06cc
	textpointer Text06cd
	textpointer Text06ce
	textpointer Text06cf
	textpointer Text06d0
	textpointer Text06d1
	textpointer Text06d2
	textpointer Text06d3
	textpointer Text06d4
	textpointer Text06d5
	textpointer Text06d6
	textpointer Text06d7
	textpointer Text06d8
	textpointer Text06d9
	textpointer Text06da
	textpointer Text06db
	textpointer Text06dc
	textpointer Text06dd
	textpointer Text06de
	textpointer Text06df
	textpointer Text06e0
	textpointer Text06e1
	textpointer Text06e2
	textpointer Text06e3
	textpointer Text06e4
	textpointer Text06e5
	textpointer Text06e6
	textpointer Text06e7
	textpointer Text06e8
	textpointer Text06e9
	textpointer Text06ea
	textpointer Text06eb
	textpointer Text06ec
	textpointer Text06ed
	textpointer Text06ee
	textpointer Text06ef
	textpointer Text06f0
	textpointer Text06f1
	textpointer Text06f2
	textpointer Text06f3
	textpointer Text06f4
	textpointer Text06f5
	textpointer Text06f6
	textpointer Text06f7
	textpointer Text06f8
	textpointer Text06f9
	textpointer Text06fa
	textpointer Text06fb
	textpointer Text06fc
	textpointer Text06fd
	textpointer Text06fe
	textpointer Text06ff
	textpointer Text0700
	textpointer Text0701
	textpointer Text0702
	textpointer Text0703
	textpointer Text0704
	textpointer Text0705
	textpointer Text0706
	textpointer Text0707
	textpointer Text0708
	textpointer Text0709
	textpointer Text070a
	textpointer Text070b
	textpointer Text070c
	textpointer Text070d
	textpointer Text070e
	textpointer Text070f
	textpointer Text0710
	textpointer Text0711
	textpointer Text0712
	textpointer Text0713
	textpointer Text0714
	textpointer Text0715
	textpointer Text0716
	textpointer Text0717
	textpointer Text0718
	textpointer Text0719
	textpointer Text071a
	textpointer Text071b
	textpointer Text071c
	textpointer Text071d
	textpointer Text071e
	textpointer Text071f
	textpointer Text0720
	textpointer Text0721
	textpointer Text0722
	textpointer Text0723
	textpointer Text0724
	textpointer Text0725
	textpointer Text0726
	textpointer Text0727
	textpointer Text0728
	textpointer Text0729
	textpointer Text072a
	textpointer Text072b
	textpointer Text072c
	textpointer Text072d
	textpointer Text072e
	textpointer Text072f
	textpointer Text0730
	textpointer Text0731
	textpointer Text0732
	textpointer Text0733
	textpointer Text0734
	textpointer Text0735
	textpointer Text0736
	textpointer Text0737
	textpointer Text0738
	textpointer Text0739
	textpointer Text073a
	textpointer Text073b
	textpointer Text073c
	textpointer Text073d
	textpointer Text073e
	textpointer Text073f
	textpointer Text0740
	textpointer Text0741
	textpointer Text0742
	textpointer Text0743
	textpointer Text0744
	textpointer Text0745
	textpointer Text0746
	textpointer Text0747
	textpointer Text0748
	textpointer Text0749
	textpointer Text074a
	textpointer Text074b
	textpointer Text074c
	textpointer Text074d
	textpointer Text074e
	textpointer Text074f
	textpointer Text0750
	textpointer Text0751
	textpointer Text0752
	textpointer Text0753
	textpointer Text0754
	textpointer Text0755
	textpointer Text0756
	textpointer Text0757
	textpointer Text0758
	textpointer Text0759
	textpointer Text075a
	textpointer Text075b
	textpointer Text075c
	textpointer Text075d
	textpointer Text075e
	textpointer Text075f
	textpointer Text0760
	textpointer Text0761
	textpointer Text0762
	textpointer Text0763
	textpointer Text0764
	textpointer Text0765
	textpointer Text0766
	textpointer Text0767
	textpointer Text0768
	textpointer Text0769
	textpointer Text076a
	textpointer Text076b
	textpointer Text076c
	textpointer Text076d
	textpointer Text076e
	textpointer Text076f
	textpointer Text0770
	textpointer Text0771
	textpointer Text0772
	textpointer Text0773
	textpointer Text0774
	textpointer Text0775
	textpointer Text0776
	textpointer Text0777
	textpointer Text0778
	textpointer Text0779
	textpointer Text077a
	textpointer Text077b
	textpointer Text077c
	textpointer Text077d
	textpointer Text077e
	textpointer Text077f
	textpointer Text0780
	textpointer Text0781
	textpointer Text0782
	textpointer Text0783
	textpointer Text0784
	textpointer Text0785
	textpointer Text0786
	textpointer Text0787
	textpointer Text0788
	textpointer Text0789
	textpointer Text078a
	textpointer Text078b
	textpointer Text078c
	textpointer Text078d
	textpointer Text078e
	textpointer Text078f
	textpointer Text0790
	textpointer Text0791
	textpointer Text0792
	textpointer Text0793
	textpointer Text0794
	textpointer Text0795
	textpointer Text0796
	textpointer Text0797
	textpointer Text0798
	textpointer Text0799
	textpointer Text079a
	textpointer Text079b
	textpointer Text079c
	textpointer Text079d
	textpointer Text079e
	textpointer Text079f
	textpointer Text07a0
	textpointer Text07a1
	textpointer Text07a2
	textpointer Text07a3
	textpointer Text07a4
	textpointer Text07a5
	textpointer Text07a6
	textpointer Text07a7
	textpointer Text07a8
	textpointer Text07a9
	textpointer Text07aa
	textpointer Text07ab
	textpointer Text07ac
	textpointer Text07ad
	textpointer Text07ae
	textpointer Text07af
	textpointer Text07b0
	textpointer Text07b1
	textpointer Text07b2
	textpointer Text07b3
	textpointer Text07b4
	textpointer Text07b5
	textpointer Text07b6
	textpointer Text07b7
	textpointer Text07b8
	textpointer Text07b9
	textpointer Text07ba
	textpointer Text07bb
	textpointer Text07bc
	textpointer Text07bd
	textpointer Text07be
	textpointer Text07bf
	textpointer Text07c0
	textpointer Text07c1
	textpointer Text07c2
	textpointer Text07c3
	textpointer Text07c4
	textpointer Text07c5
	textpointer Text07c6
	textpointer Text07c7
	textpointer Text07c8
	textpointer Text07c9
	textpointer Text07ca
	textpointer Text07cb
	textpointer Text07cc
	textpointer Text07cd
	textpointer Text07ce
	textpointer Text07cf
	textpointer Text07d0
	textpointer Text07d1
	textpointer Text07d2
	textpointer Text07d3
	textpointer Text07d4
	textpointer Text07d5
	textpointer Text07d6
	textpointer Text07d7
	textpointer Text07d8
	textpointer Text07d9
	textpointer Text07da
	textpointer Text07db
	textpointer Text07dc
	textpointer Text07dd
	textpointer Text07de
	textpointer Text07df
	textpointer Text07e0
	textpointer Text07e1
	textpointer Text07e2
	textpointer Text07e3
	textpointer Text07e4
	textpointer Text07e5
	textpointer DefeatedFiveOpponentsText
	textpointer Text07e7
	textpointer ConsecutiveWinRecordIncreasedText
	textpointer Text07e9
	textpointer Text07ea
	textpointer Text07eb
	textpointer Text07ec
	textpointer Text07ed
	textpointer Text07ee
	textpointer Text07ef
	textpointer Text07f0
	textpointer Text07f1
	textpointer Text07f2
	textpointer Text07f3
	textpointer Text07f4
	textpointer Text07f5
	textpointer Text07f6
	textpointer Text07f7
	textpointer Text07f8
	textpointer Text07f9
	textpointer Text07fa
	textpointer Text07fb
	textpointer GrassEnergyName
	textpointer GrassEnergyDescription
	textpointer FireEnergyName
	textpointer FireEnergyDescription
	textpointer WaterEnergyName
	textpointer WaterEnergyDescription
	textpointer LightningEnergyName
	textpointer LightningEnergyDescription
	textpointer FightingEnergyName
	textpointer FightingEnergyDescription
	textpointer PsychicEnergyName
	textpointer PsychicEnergyDescription
	textpointer DoubleColorlessEnergyName
	textpointer DoubleColorlessEnergyDescription
	textpointer BulbasaurName
	textpointer LeechSeedName
	textpointer BulbasaursLeechSeedDescription
	textpointer BulbasaurKind
	textpointer BulbasaurDescription
	textpointer IvysaurName
	textpointer VineWhipName
	textpointer PoisonPowderName
	textpointer InflictPoisonDescription
	textpointer IvysaurDescription
	textpointer VenusaurName
	textpointer SolarPowerName
	textpointer SolarPowerDescription
	textpointer SolarPowerDescriptionCont
	textpointer MegaDrainName
	textpointer VenusaursMegaDrainDescription
	textpointer VenusaursMegaDrainDescriptionCont
	textpointer Venusaur1Description
	textpointer EnergyTransName
	textpointer EnergyTransDescription
	textpointer SolarBeamName
	textpointer Venusaur2Description
	textpointer CaterpieName
	textpointer StringShotName
	textpointer MayInflictParalysisDescription
	textpointer CaterpieKind
	textpointer CaterpieDescription
	textpointer MetapodName
	textpointer StiffenName
	textpointer MetapodsStiffenDescription
	textpointer StunSporeName
	textpointer MetapodKind
	textpointer MetapodDescription
	textpointer ButterfreeName
	textpointer WhirlwindName
	textpointer WhirlwindDescription
	textpointer ButterfreesMegaDrainDescription
	textpointer ButterfreesMegaDrainDescriptionCont
	textpointer ButterfreeKind
	textpointer ButterfreeDescription
	textpointer WeedleName
	textpointer PoisonStingName
	textpointer MayInflictPoisonDescription
	textpointer WeedleKind
	textpointer WeedleDescription
	textpointer KakunaName
	textpointer KakunasStiffenDescription
	textpointer KakunaDescription
	textpointer BeedrillName
	textpointer TwineedleName
	textpointer DoubleAttackX30Description
	textpointer BeedrillKind
	textpointer BeedrillDescription
	textpointer EkansName
	textpointer SpitPoisonName
	textpointer WrapName
	textpointer EkansKind
	textpointer EkansDescription
	textpointer ArbokName
	textpointer TerrorStrikeName
	textpointer TerrorStrikeDescription
	textpointer PoisonFangName
	textpointer ArbokKind
	textpointer ArbokDescription
	textpointer NidoranFName
	textpointer FurySweepesName
	textpointer TripleAttackX10Description
	textpointer CallforFamilyName
	textpointer NidoranFsCallforFamilyDescription
	textpointer NidoranFKind
	textpointer NidoranFDescription
	textpointer NidorinaName
	textpointer SupersonicName
	textpointer MayInflictConfusionDescription
	textpointer DoubleKickName
	textpointer NidorinaDescription
	textpointer NidoqueenName
	textpointer BoyfriendsName
	textpointer BoyfriendsDescription
	textpointer MegaPunchName
	textpointer NidoqueenKind
	textpointer NidoqueenDescription
	textpointer NidoranMName
	textpointer HornHazardName
	textpointer MayDoNothingDescription
	textpointer NidoranMDescription
	textpointer NidorinoName
	textpointer HornDrillName
	textpointer NidorinoDescription
	textpointer NidokingName
	textpointer ThrashName
	textpointer ThrashDescriptipn
	textpointer ToxicName
	textpointer ToxicDescription
	textpointer NidokingDescription
	textpointer ZubatName
	textpointer LeechLifeName
	textpointer ZubatsLeechLifeDescription
	textpointer ZubatKind
	textpointer ZubatDescription
	textpointer GolbatName
	textpointer WingAttackName
	textpointer GolbatsLeechLifeDescription
	textpointer GolbatDescription
	textpointer OddishName
	textpointer SproutName
	textpointer SproutDescription
	textpointer OddishKind
	textpointer OddishDescription
	textpointer GloomName
	textpointer FoulOdorName
	textpointer FoulOdorDescription
	textpointer GloomDescription
	textpointer VileplumeName
	textpointer HealName
	textpointer HealDescription
	textpointer PetalDanceName
	textpointer PetalDanceDescription
	textpointer VileplumeKind
	textpointer VileplumeDescription
	textpointer ParasName
	textpointer ScratchName
	textpointer SporeName
	textpointer InflictSleepDescription
	textpointer ParasKind
	textpointer ParasDescription
	textpointer ParasectName
	textpointer SlashName
	textpointer ParasectDescription
	textpointer VenonatName
	textpointer VenonatLeechLifeDescription
	textpointer VenonatKind
	textpointer VenonatDescription
	textpointer VenomothName
	textpointer ShiftName
	textpointer ShiftDescription
	textpointer VenomPowderName
	textpointer VenomPowderDescription
	textpointer VenomothKind
	textpointer VenomothDescription
	textpointer BellsproutName
	textpointer BellsproutsCallforFamilyDescription
	textpointer BellsproutDescription
	textpointer WeepinbellName
	textpointer RazorLeafName
	textpointer WeepinbellKind
	textpointer WeepinbellDescription
	textpointer VictreebelName
	textpointer LureName
	textpointer VictreebelsLureDescription
	textpointer AcidName
	textpointer VictreebelsAcidDescription
	textpointer VictreebelDescription
	textpointer GrimerName
	textpointer NastyGooName
	textpointer MinimizeName
	textpointer GrimersMinimizeDescription
	textpointer GrimerKindOrSludgeName
	textpointer GrimerDescription
	textpointer MukName
	textpointer ToxicGasName
	textpointer ToxicGasDescription
	textpointer MukDescription
	textpointer ExeggcuteName
	textpointer DrowzeeKindOrHypnosisName
	textpointer ExeggcutesLeechSeedDescription
	textpointer ExeggcuteKind
	textpointer ExeggcuteDescription
	textpointer ExeggutorName
	textpointer TeleportName
	textpointer TeleportDescription
	textpointer BigEggsplosionName
	textpointer BigEggsplosionDescription
	textpointer ExeggutorKind
	textpointer ExeggutorDescription
	textpointer KoffingName
	textpointer FoulGasName
	textpointer FoulGasDescription
	textpointer KoffingKind
	textpointer KoffingDescription
	textpointer WeezingName
	textpointer SmogName
	textpointer SelfdestructName
	textpointer WeezingsSelfdestructDescription
	textpointer WeezingDescription
	textpointer TangelaName
	textpointer BindName
	textpointer TangelaKind
	textpointer Tangela1Description
	textpointer PoisonWhipName
	textpointer Tangela2Description
	textpointer ScytherName
	textpointer SwordsDanceName
	textpointer SwordsDanceDescription
	textpointer ScytherKind
	textpointer ScytherDescription
	textpointer PinsirName
	textpointer IronGripName
	textpointer GuillotineName
	textpointer PinsirKind
	textpointer PinsirDescription
	textpointer CharmanderName
	textpointer EmberName
	textpointer EmberDescription
	textpointer CharmanderKind
	textpointer CharmanderDescription
	textpointer CharmeleonName
	textpointer FlamethrowerName
	textpointer CharmeleonsFlamethrowerDescription
	textpointer CharmeleonKind
	textpointer CharmeleonDescription
	textpointer CharizardName
	textpointer EnergyBurnName
	textpointer EnergyBurnDescription
	textpointer FireSpinName
	textpointer FireSpinDescription
	textpointer CharizardDescription
	textpointer VulpixName
	textpointer ConfuseRayName
	textpointer VulpixKind
	textpointer VulpixDescription
	textpointer NinetailsName
	textpointer NinetailsLureDescription
	textpointer FireBlastName
	textpointer FireBlastDescription
	textpointer Ninetails1Description
	textpointer MixUpName
	textpointer MixUpDescription
	textpointer MixUpDescriptionCont
	textpointer DancingEmbersName
	textpointer DancingEmbersDescription
	textpointer Ninetails2Description
	textpointer GrowlitheName
	textpointer FlareName
	textpointer GrowlitheKind
	textpointer GrowlitheDescription
	textpointer ArcanineName
	textpointer QuickAttackName
	textpointer QuickAttackDescription
	textpointer FlamesofRageName
	textpointer FlamesofRageDescription
	textpointer ArcanineKind
	textpointer Arcanine1Description
	textpointer ArcaninesFlamethrowerDescription
	textpointer TakeDownName
	textpointer TakeDownDescription
	textpointer Arcanine2Description
	textpointer PonytaName
	textpointer SmashKickName
	textpointer FlameTailName
	textpointer PonytaKind
	textpointer PonytaDescription
	textpointer RapidashName
	textpointer StompName
	textpointer StompDescription
	textpointer AgilityName
	textpointer RapidashsAgilityDescription
	textpointer RapidashDescription
	textpointer MagmarName
	textpointer FirePunchName
	textpointer FirePunchDescription
	textpointer MagmarKind
	textpointer Magmar1Description
	textpointer SmokescreenName
	textpointer MagmarsSmokescreenDescription
	textpointer Magmar2Description
	textpointer FlareonName
	textpointer EeveeName
	textpointer BiteName
	textpointer RageName
	textpointer FlareonsRageDescription
	textpointer Flareon1Description
	textpointer FlareonsFlamethrowerDescription
	textpointer Flareon2Description
	textpointer MoltresName
	textpointer WildfireName
	textpointer WildfireDescription
	textpointer DiveBombName
	textpointer Moltres1Description
	textpointer FiregiverName
	textpointer FiregiverDescription
	textpointer Moltres2Description
	textpointer SquirtleName
	textpointer BubbleName
	textpointer WithdrawName
	textpointer SquirtlesWithdrawDescription
	textpointer SquirtleKind
	textpointer SquirtleDescription
	textpointer WartortleName
	textpointer WartortlesWithdrawDescription
	textpointer WartortleKind
	textpointer WartortleDescription
	textpointer BlastoiseName
	textpointer RainDanceName
	textpointer RainDanceDescription
	textpointer RainDanceDescriptionCont
	textpointer HydroPumpName
	textpointer HydroPumpDescription
	textpointer BlastoiseKind
	textpointer BlastoiseDescription
	textpointer PsyduckName
	textpointer HeadacheName
	textpointer HeadacheDescription
	textpointer PsyduckKind
	textpointer PsyduckDescription
	textpointer GolduckName
	textpointer PsyshockName
	textpointer HyperBeamName
	textpointer Discard1EnergyFromTargetDescription
	textpointer GolduckDescription
	textpointer PoliwagName
	textpointer WaterGunName
	textpointer PoliwagsWaterGunDescription
	textpointer PoliwagKind
	textpointer PoliwagDescription
	textpointer PoliwhirlName
	textpointer AmnesiaName
	textpointer PoliwhirlsAmnesiaDescription
	textpointer DoubleslapName
	textpointer PoliwhirlsDescription
	textpointer PoliwrathName
	textpointer PoliwrathsWaterGunDescription
	textpointer WhirlpoolName
	textpointer PoliwrathDescription
	textpointer TentacoolName
	textpointer CowardiceName
	textpointer CowardiceDescription
	textpointer TentacoolKind
	textpointer TentacoolDescription
	textpointer TentacruelName
	textpointer JellyfishStingName
	textpointer TentacruelDescription
	textpointer SeelName
	textpointer HeadbuttName
	textpointer SeelKind
	textpointer SeelDescription
	textpointer DewgongName
	textpointer AuroraBeamName
	textpointer IceBeamName
	textpointer DewgongDescription
	textpointer ShellderName
	textpointer HideinShellName
	textpointer HideinShellDescription
	textpointer ShellderKind
	textpointer ShellderDescription
	textpointer CloysterName
	textpointer ClampName
	textpointer ClampDescription
	textpointer SpikeCannonName
	textpointer CloysterDescription
	textpointer KrabbyName
	textpointer KrabbysCallforFamilyDescription
	textpointer KrabbyKind
	textpointer KrabbyDescription
	textpointer KinglerName
	textpointer FlailName
	textpointer KinglersFlailDescription
	textpointer CrabhammerName
	textpointer KinglerKind
	textpointer KinglerDescription
	textpointer HorseaName
	textpointer OpponentAttackMayDoNothingDescription
	textpointer HorseaKind
	textpointer HorseaDescription
	textpointer SeadraName
	textpointer SeadrasWaterGunDescription
	textpointer SeadrasAgilityDescription
	textpointer SeadraDescription
	textpointer GoldeenName
	textpointer HornAttackName
	textpointer GoldeenKind
	textpointer GoldeenDescription
	textpointer SeakingName
	textpointer WaterfallName
	textpointer SeakingDescription
	textpointer StaryuName
	textpointer SlapName
	textpointer StaryuKind
	textpointer StaryuDescription
	textpointer StarmieName
	textpointer RecoverName
	textpointer StarmiesRecoverDescription
	textpointer StarFreezeName
	textpointer StarmieKind
	textpointer StarmieDescription
	textpointer MagikarpName
	textpointer TackleName
	textpointer MagikarpsFlailDescription
	textpointer MagikarpKind
	textpointer MagikarpDescription
	textpointer GyaradosName
	textpointer DragonRageName
	textpointer BubblebeamName
	textpointer GyaradosKind
	textpointer GyaradosDescription
	textpointer LaprasName
	textpointer LaprasWaterGunDescription
	textpointer LaprasKind
	textpointer LaprasDescription
	textpointer VaporeonName
	textpointer FocusEnergyName
	textpointer FocusEnergyDescription
	textpointer VaporeonKind
	textpointer Vaporeon1Description
	textpointer VaporeonsWaterGunDescription
	textpointer Vaporeon2Description
	textpointer OmanyteName
	textpointer MysteriousFossilName
	textpointer ClairvoyanceName
	textpointer ClairvoyanceDescription
	textpointer OmanytesWaterGunDescription
	textpointer OmanyteKind
	textpointer OmanyteDescription
	textpointer OmastarName
	textpointer OmastarsWaterGunDescription
	textpointer OmastarDescription
	textpointer ArticunoName
	textpointer FreezeDryName
	textpointer BlizzardName
	textpointer BlizzardDescription
	textpointer ArticunoKind
	textpointer Articuno1Description
	textpointer QuickfreezeName
	textpointer QuickfreezeDescription
	textpointer IceBreathName
	textpointer IceBreathDescription
	textpointer Articuno2Description
	textpointer PikachuName
	textpointer GnawName
	textpointer ThunderJoltName
	textpointer ThunderJoltDescription
	textpointer PikachuKind
	textpointer Pikachu1Description
	textpointer SparkName
	textpointer SparkDescription
	textpointer Pikachu2Description
	textpointer GrowlName
	textpointer GrowlDescription
	textpointer ThundershockName
	textpointer Pikachu3Description
	textpointer FlyingPikachuName
	textpointer FlyName
	textpointer FlyDescription
	textpointer FlyingPikachuDescription
	textpointer SurfingPikachuName
	textpointer SurfName
	textpointer SurfingPikachuDescription
	textpointer RaichuName
	textpointer RaichusAgilityDescription
	textpointer ThunderName
	textpointer RaichusThunderDescription
	textpointer Raichu1Description
	textpointer GigashockName
	textpointer GigashockDescription
	textpointer Raichu2Description
	textpointer MagnemiteName
	textpointer ThunderWaveName
	textpointer MagnemitesSelfdestructDescription
	textpointer MagnemiteKind
	textpointer Magnemite1Description
	textpointer MagneticStormName
	textpointer MagneticStormDescription
	textpointer Magnemite2Description
	textpointer MagnetonName
	textpointer Magneton1sSelfdestructDescription
	textpointer Magneton1Description
	textpointer SonicboomName
	textpointer SonicboomDescription
	textpointer Magneton2sSelfdestructDescription
	textpointer Magneton2Description
	textpointer VoltorbName
	textpointer VoltorbKind
	textpointer VoltorbDescription
	textpointer ElectrodeName
	textpointer EnergySpikeName
	textpointer EnergySpikeDescription
	textpointer Electrode1Description
	textpointer ChainLightningName
	textpointer ChainLightningDescription
	textpointer Electrode2Description
	textpointer ElectabuzzName
	textpointer LightScreenName
	textpointer LightScreenDescription
	textpointer LightScreenDescriptionCont
	textpointer ElectabuzzsQuickAttackDescription
	textpointer ElectabuzzKind
	textpointer Electabuzz1Description
	textpointer ThunderpunchName
	textpointer ThunderpunchDescription
	textpointer Electabuzz2Description
	textpointer JolteonName
	textpointer DoubleAttackX20Description
	textpointer StunNeedleName
	textpointer JolteonKind
	textpointer Jolteon1Description
	textpointer PinMissileName
	textpointer QuadrupleAttackX20Description
	textpointer Jolteon2Description
	textpointer ZapdosName
	textpointer ThunderstormName
	textpointer ThunderstormDescription
	textpointer Zapdos1Description
	textpointer ZapdosThunderDescription
	textpointer ThunderboltName
	textpointer ThunderboltDescription
	textpointer Zapdos2Description
	textpointer PealofThunderName
	textpointer PealofThunderDescription
	textpointer BigThunderName
	textpointer BigThunderDescription
	textpointer Zapdos3Description
	textpointer SandshrewName
	textpointer SandAttackName
	textpointer SandshrewDescription
	textpointer SandslashName
	textpointer TripleAttackX20Description
	textpointer SandslashDescription
	textpointer DiglettName
	textpointer DigName
	textpointer MudSlapName
	textpointer DiglettKind
	textpointer DiglettDescription
	textpointer DugtrioName
	textpointer EarthquakeName
	textpointer EarthquakeDescription
	textpointer DugtrioDescription
	textpointer MankeyName
	textpointer PeekName
	textpointer PeekDescription
	textpointer PeekDescriptionCont
	textpointer MankeyKind
	textpointer MankeyDescription
	textpointer PrimeapeName
	textpointer TantrumName
	textpointer TantrumDescription
	textpointer PrimeapeDescription
	textpointer MachopName
	textpointer LowKickName
	textpointer MachopKindOrSuperpowerName
	textpointer MachopDescription
	textpointer MachokeName
	textpointer KarateChopName
	textpointer KarateChopDescription
	textpointer SubmissionName
	textpointer SubmissionDescription
	textpointer MachokeDescription
	textpointer MachampName
	textpointer StrikesBackName
	textpointer StrikesBackDescription
	textpointer StrikesBackDescriptionCont
	textpointer SeismicTossName
	textpointer MachampDescription
	textpointer GeodudeName
	textpointer StoneBarrageName
	textpointer StoneBarrageDescription
	textpointer GeodudeKind
	textpointer GeodudeDescription
	textpointer GravelerName
	textpointer HardenName
	textpointer GravelersHardenDescription
	textpointer RockThrowName
	textpointer GravelerDescription
	textpointer GolemName
	textpointer AvalancheName
	textpointer GolemsSelfdestructDescription
	textpointer GolemKind
	textpointer GolemDescription
	textpointer OnixName
	textpointer OnixsHardenDescription
	textpointer OnixKind
	textpointer OnixDescription
	textpointer CuboneName
	textpointer SnivelName
	textpointer SnivelDescription
	textpointer CubonesRageDescription
	textpointer CuboneKind
	textpointer CuboneDescription
	textpointer MarowakName
	textpointer BonemerangName
	textpointer CallforFriendName
	textpointer CallforFriendDescription
	textpointer MarowakKind
	textpointer Marowak1Description
	textpointer BoneAttackName
	textpointer BoneAttackDescription
	textpointer WailName
	textpointer WailDescription
	textpointer Marowak2Description
	textpointer HitmonleeName
	textpointer StretchKickName
	textpointer StretchKickDescription
	textpointer HighJumpKickName
	textpointer HitmonleeKind
	textpointer HitmonleeDescription
	textpointer HitmonchanName
	textpointer JabName
	textpointer SpecialPunch
	textpointer HitmonchanKind
	textpointer HitmonchanDescription
	textpointer RhyhornName
	textpointer LeerName
	textpointer LeerDescription
	textpointer RhyhornKind
	textpointer RhyhornDescription
	textpointer RhydonName
	textpointer RamName
	textpointer RamDescription
	textpointer RamDescriptionCont
	textpointer RhydonDescription
	textpointer KabutoName
	textpointer KabutoArmorName
	textpointer KabutoArmorDescription
	textpointer KabutoArmorDescriptionCont
	textpointer KabutoDescription
	textpointer KabutopsName
	textpointer SharpSickleName
	textpointer AbsorbName
	textpointer AbsorbDescription
	textpointer AbsorbDescriptionCont
	textpointer KabutopsDescription
	textpointer AerodactylName
	textpointer PrehistoricPowerName
	textpointer PrehistoricPowerDescription
	textpointer AerodactylKind
	textpointer AerodactylDescription
	textpointer AbraName
	textpointer AbraKind
	textpointer AbraDescription
	textpointer KadabraName
	textpointer KadabrasRecoverDescription
	textpointer SuperPsiName
	textpointer KadabraDescription
	textpointer AlakazamName
	textpointer DamageSwapName
	textpointer DamageSwapDescription
	textpointer AlakazamDescription
	textpointer SlowpokeName
	textpointer SlowpokesAmnesiaDescription
	textpointer SlowpokeKind
	textpointer Slowpoke1Description
	textpointer SpacingOutName
	textpointer SpacingOutDescription
	textpointer ScavengeName
	textpointer ScavengeDescription
	textpointer SlowbroName
	textpointer StrangeBehaviorName
	textpointer StrangeBehaviorDescription
	textpointer SlowbroKind
	textpointer SlowbroDescription
	textpointer GastlyName
	textpointer SleepingGasName
	textpointer MayInflictSleepDescription
	textpointer DestinyBondName
	textpointer DestinyBondDescription
	textpointer GastlyKind
	textpointer Gastly1Description
	textpointer LickName
	textpointer EnergyConversionName
	textpointer EnergyConversionDescription
	textpointer Gastly2Description
	textpointer HaunterName
	textpointer TransparencyName
	textpointer TransparencyDescription
	textpointer NightmareName
	textpointer HaunterDescription
	textpointer DreamEaterName
	textpointer DreamEaterDescription
	textpointer GengarName
	textpointer CurseName
	textpointer CurseDescription
	textpointer DarkMindName
	textpointer DarkMindDescription
	textpointer GengarKind
	textpointer GengarDescription
	textpointer DrowzeeName
	textpointer PoundName
	textpointer DrowzeeDescription
	textpointer HypnoName
	textpointer ProphecyName
	textpointer ProphecyDescription
	textpointer HypnoDescription
	textpointer MrMimeName
	textpointer InvisibleWallName
	textpointer InvisibleWallDescription
	textpointer InvisibleWallDescriptionCont
	textpointer MeditateName
	textpointer MrMimesMeditateDescription
	textpointer MrMimeKindOrBarrierName
	textpointer MrMimeDescription
	textpointer JynxName
	textpointer DoubleAttackX10Description
	textpointer JynxsMeditateDescription
	textpointer JynxKind
	textpointer JynxDescription
	textpointer MewtwoName
	textpointer PsychicName
	textpointer PsychicDescription
	textpointer BarrierDescription
	textpointer MewtwoKind
	textpointer Mewtwo1Description
	textpointer EnergyAbsorptionName
	textpointer EnergyAbsorptionDescription
	textpointer PsyburnName
	textpointer Mewtwo2Description
	textpointer MewName
	textpointer NeutralizingShieldName
	textpointer NeutralizingShieldDescription
	textpointer MewKind
	textpointer Mew1Description
	textpointer MysteryAttackName
	textpointer MysteryAttackDescription
	textpointer Mew2Description
	textpointer PsywaveName
	textpointer PsywaveDescription
	textpointer DevolutionBeamName
	textpointer DevolutionBeamDescription
	textpointer PidgeyName
	textpointer PidgeyKind
	textpointer PidgeyDescription
	textpointer PidgeottoName
	textpointer MirrorMoveName
	textpointer PidgeottosMirrorMoveDescription
	textpointer PidgeottoKind
	textpointer PidgeottoDescription
	textpointer PidgeotName
	textpointer SlicingWindName
	textpointer SlicingWildDescription
	textpointer GaleName
	textpointer GaleDescription
	textpointer Pidgeot1Description
	textpointer HurricaneName
	textpointer HurricaneDescription
	textpointer Pidgeot2Description
	textpointer RattataName
	textpointer RattataKind
	textpointer RattataDescription
	textpointer RaticateName
	textpointer SuperFangName
	textpointer SuperFangDescription
	textpointer RaticateDescription
	textpointer SpearowName
	textpointer PeckName
	textpointer SpearowsMirrorMoveDescription
	textpointer SpearowDescription
	textpointer FearowName
	textpointer FearowsAgilityDescription
	textpointer DrillPeckName
	textpointer FearowKind
	textpointer FearowDescription
	textpointer ClefairyName
	textpointer SingName
	textpointer MetronomeName
	textpointer ClefairysMetronomeDescription
	textpointer ClefairyKind
	textpointer ClefairyDescription
	textpointer ClefableName
	textpointer ClefablesMetronomeDescription
	textpointer ClefablesMinimizeDescription
	textpointer ClefableDescription
	textpointer JigglypuffName
	textpointer FirstAidName
	textpointer FirstAidDescription
	textpointer DoubleEdgeName
	textpointer JigglypuffsDoubleEdgeDescription
	textpointer JigglypuffKind
	textpointer Jigglypuff1Description
	textpointer FriendshipSongName
	textpointer FriendshipSongDescription
	textpointer ExpandName
	textpointer ExpandDescription
	textpointer Jigglypuff2Description
	textpointer LullabyName
	textpointer Jigglypuff3Description
	textpointer WigglytuffName
	textpointer DotheWaveName
	textpointer DotheWaveDescription
	textpointer WigglytuffDescription
	textpointer MeowthName
	textpointer CatPunchName
	textpointer CatPunchDescription
	textpointer MeowthKind
	textpointer Meowth1Description
	textpointer PayDayName
	textpointer PayDayDescription
	textpointer Meowth2Description
	textpointer PersianName
	textpointer PounceName
	textpointer PounceDescription
	textpointer PersianKind
	textpointer PersianDescription
	textpointer FarfetchdName
	textpointer LeekSlapName
	textpointer LeekSlapDescription
	textpointer PotSmashName
	textpointer FarfetchdKind
	textpointer FarfetchdDescription
	textpointer DoduoName
	textpointer FuryAttackName
	textpointer DoduoKind
	textpointer DoduoDescription
	textpointer DodrioName
	textpointer RetreatAidName
	textpointer RetreatAidDescription
	textpointer DodriosRageDescription
	textpointer DodrioKind
	textpointer DodrioDescription
	textpointer LickitungName
	textpointer TongueWrapName
	textpointer LickitungKind
	textpointer LickitungDescription
	textpointer ChanseyName
	textpointer ScrunchName
	textpointer ScrunchDescription
	textpointer ChanseysDoubleEdgeDescription
	textpointer ChanseyDescription
	textpointer KangaskhanName
	textpointer FetchName
	textpointer FetchDescription
	textpointer CometPunchName
	textpointer KangaskhanKind
	textpointer KangaskhanDescription
	textpointer TaurosName
	textpointer RampageName
	textpointer RampageDescription
	textpointer TaurosKind
	textpointer TaurosDescription
	textpointer DittoName
	textpointer MorphName
	textpointer MorphDescription
	textpointer MorphDescriptionCont
	textpointer DittoKind
	textpointer DittoDescription
	textpointer TailWagName
	textpointer TailWagDescription
	textpointer EeveeKind
	textpointer EeveeDescription
	textpointer PorygonName
	textpointer Conversion1Name
	textpointer Conversion1Description
	textpointer Conversion2Name
	textpointer Conversion2Description
	textpointer PorygonKind
	textpointer PorygonDescription
	textpointer SnorlaxName
	textpointer ThickSkinnedName
	textpointer ThickSkinnedDescription
	textpointer BodySlamName
	textpointer SnorlaxKind
	textpointer SnorlaxDescription
	textpointer DratiniName
	textpointer DratiniDescription
	textpointer DragonairName
	textpointer SlamName
	textpointer DragonairDescription
	textpointer DragoniteName
	textpointer HealingWindName
	textpointer HealingWindDescription
	textpointer Dragonite1Description
	textpointer StepInName
	textpointer StepInDescription
	textpointer DoubleAttackX40Description
	textpointer DragoniteDescription
	textpointer ProfessorOakName
	textpointer ProfessorOakDescription
	textpointer ImposterProfessorOakName
	textpointer ImposterProfessorOakDescription
	textpointer BillName
	textpointer BillDescription
	textpointer MrFujiName
	textpointer MrFujiDescription
	textpointer LassName
	textpointer LassDescription
	textpointer ImakuniName
	textpointer ImakuniDescription
	textpointer PokemonTraderName
	textpointer PokemonTraderDescription
	textpointer PokemonBreederName
	textpointer PokemonBreederDescription
	textpointer ClefairyDollName
	textpointer ClefairyDollDescription
	textpointer ClefairyDollDescriptionCont
	textpointer MysteriousFossilDescription
	textpointer MysteriousFossilDescriptionCont
	textpointer EnergyRetrievalName
	textpointer EnergyRetrievalDescription
	textpointer SuperEnergyRetrievalName
	textpointer SuperEnergyRetrievalDescription
	textpointer EnergySearchName
	textpointer EnergySearchDescription
	textpointer EnergyRemovalName
	textpointer EnergyRemovalDescription
	textpointer SuperEnergyRemovalName
	textpointer SuperEnergyRemovalDescription
	textpointer SwitchName
	textpointer SwitchDescription
	textpointer PokemonCenterName
	textpointer PokemonCenterDescription
	textpointer PokeBallName
	textpointer PokeBallDescription
	textpointer ScoopUpName
	textpointer ScoopUpDescription
	textpointer ComputerSearchName
	textpointer ComputerSearchDescription
	textpointer PokedexName
	textpointer PokedexDescription
	textpointer PlusPowerName
	textpointer PlusPowerDescription
	textpointer DefenderName
	textpointer DefenderDescription
	textpointer ItemFinderName
	textpointer ItemFinderDescription
	textpointer GustofWindName
	textpointer GustofWindDescription
	textpointer DevolutionSprayName
	textpointer DevolutionSprayDescription
	textpointer DevolutionSprayDescriptionCont
	textpointer PotionName
	textpointer PotionDescription
	textpointer SuperPotionName
	textpointer SuperPotionDescription
	textpointer FullHealName
	textpointer FullHealDescription
	textpointer ReviveName
	textpointer ReviveDescription
	textpointer MaintenanceName
	textpointer MaintenanceDescription
	textpointer PokemonFluteName
	textpointer PokemonFluteDescription
	textpointer GamblerName
	textpointer GamblerDescription
	textpointer RecycleName
	textpointer RecycleDescription
