BOOSTER_CARD_TYPE_GRASS     EQU $00
BOOSTER_CARD_TYPE_FIRE      EQU $01
BOOSTER_CARD_TYPE_LIGHTNING EQU $03
BOOSTER_CARD_TYPE_WATER     EQU $02
BOOSTER_CARD_TYPE_FIGHTING  EQU $04
BOOSTER_CARD_TYPE_PSYCHIC   EQU $05
BOOSTER_CARD_TYPE_COLORLESS EQU $06
BOOSTER_CARD_TYPE_TRAINER   EQU $07
BOOSTER_CARD_TYPE_ENERGY    EQU $08
BOOSTER_CARD_TYPE_AMOUNT    EQU $09

BOOSTER_ColoNeutral              EQU $00
BOOSTER_ColoGrass                EQU $01
BOOSTER_ColoFire                 EQU $02
BOOSTER_ColoWater                EQU $03
BOOSTER_ColoLightning            EQU $04
BOOSTER_ColoFighting             EQU $05
BOOSTER_ColoTrainer              EQU $06
BOOSTER_EvoNeutral               EQU $07
BOOSTER_EvoGrass                 EQU $08
BOOSTER_EvoNeutralFireEnergy     EQU $09
BOOSTER_EvoWater                 EQU $0a
BOOSTER_EvoFighting              EQU $0b
BOOSTER_EvoPsychic               EQU $0c
BOOSTER_EvoTrainer               EQU $0d
BOOSTER_MysteryNeutral           EQU $0e
BOOSTER_MysteryGrassColorless    EQU $0f
BOOSTER_MysteryWaterColorless    EQU $10
BOOSTER_LightningColorless       EQU $11
BOOSTER_MysteryFightingColorless EQU $12
BOOSTER_MysteryTrainerColorless  EQU $13
BOOSTER_LabTrainerLessFighting   EQU $14
BOOSTER_LabGrass                 EQU $15
BOOSTER_LabWater                 EQU $16
BOOSTER_LabPsychic               EQU $17
BOOSTER_LabTrainer               EQU $18
BOOSTER_EnergyLightningFire      EQU $19
BOOSTER_EnergyWaterFighting      EQU $1a
BOOSTER_EnergyGrassPsychic       EQU $1b
BOOSTER_RandomEnergies           EQU $1c
NO_BOOSTER                       EQU $ff
