	const_def 1
	const GRASS_ENERGY            ; $01
	const FIRE_ENERGY             ; $02
	const WATER_ENERGY            ; $03
	const LIGHTNING_ENERGY        ; $04
	const FIGHTING_ENERGY         ; $05
	const PSYCHIC_ENERGY          ; $06
	const DOUBLE_COLORLESS_ENERGY ; $07
	const BULBASAUR               ; $08
	const IVYSAUR                 ; $09
	const VENUSAUR1               ; $0a
	const VENUSAUR2               ; $0b
	const CATERPIE                ; $0c
	const METAPOD                 ; $0d
	const BUTTERFREE              ; $0e
	const WEEDLE                  ; $0f
	const KAKUNA                  ; $10
	const BEEDRILL                ; $11
	const EKANS                   ; $12
	const ARBOK                   ; $13
	const NIDORANF                ; $14
	const NIDORINA                ; $15
	const NIDOQUEEN               ; $16
	const NIDORANM                ; $17
	const NIDORINO                ; $18
	const NIDOKING                ; $19
	const ZUBAT                   ; $1a
	const GOLBAT                  ; $1b
	const ODDISH                  ; $1c
	const GLOOM                   ; $1d
	const VILEPLUME               ; $1e
	const PARAS                   ; $1f
	const PARASECT                ; $20
	const VENONAT                 ; $21
	const VENOMOTH                ; $22
	const BELLSPROUT              ; $23
	const WEEPINBELL              ; $24
	const VICTREEBEL              ; $25
	const GRIMER                  ; $26
	const MUK                     ; $27
	const EXEGGCUTE               ; $28
	const EXEGGUTOR               ; $29
	const KOFFING                 ; $2a
	const WEEZING                 ; $2b
	const TANGELA1                ; $2c
	const TANGELA2                ; $2d
	const SCYTHER                 ; $2e
	const PINSIR                  ; $2f
	const CHARMANDER              ; $30
	const CHARMELEON              ; $31
	const CHARIZARD               ; $32
	const VULPIX                  ; $33
	const NINETAILS1              ; $34
	const NINETAILS2              ; $35
	const GROWLITHE               ; $36
	const ARCANINE1               ; $37
	const ARCANINE2               ; $38
	const PONYTA                  ; $39
	const RAPIDASH                ; $3a
	const MAGMAR1                 ; $3b
	const MAGMAR2                 ; $3c
	const FLAREON1                ; $3d
	const FLAREON2                ; $3e
	const MOLTRES1                ; $3f
	const MOLTRES2                ; $40
	const SQUIRTLE                ; $41
	const WARTORTLE               ; $42
	const BLASTOISE               ; $43
	const PSYDUCK                 ; $44
	const GOLDUCK                 ; $45
	const POLIWAG                 ; $46
	const POLIWHIRL               ; $47
	const POLIWRATH               ; $48
	const TENTACOOL               ; $49
	const TENTACRUEL              ; $4a
	const SEEL                    ; $4b
	const DEWGONG                 ; $4c
	const SHELLDER                ; $4d
	const CLOYSTER                ; $4e
	const KRABBY                  ; $4f
	const KINGLER                 ; $50
	const HORSEA                  ; $51
	const SEADRA                  ; $52
	const GOLDEEN                 ; $53
	const SEAKING                 ; $54
	const STARYU                  ; $55
	const STARMIE                 ; $56
	const MAGIKARP                ; $57
	const GYARADOS                ; $58
	const LAPRAS                  ; $59
	const VAPOREON1               ; $5a
	const VAPOREON2               ; $5b
	const OMANYTE                 ; $5c
	const OMASTAR                 ; $5d
	const ARTICUNO1               ; $5e
	const ARTICUNO2               ; $5f
	const PIKACHU1                ; $60
	const PIKACHU2                ; $61
	const PIKACHU3                ; $62
	const PIKACHU4                ; $63
	const FLYING_PIKACHU          ; $64
	const SURFING_PIKACHU1        ; $65
	const SURFING_PIKACHU2        ; $66
	const RAICHU1                 ; $67
	const RAICHU2                 ; $68
	const MAGNEMITE1              ; $69
	const MAGNEMITE2              ; $6a
	const MAGNETON1               ; $6b
	const MAGNETON2               ; $6c
	const VOLTORB                 ; $6d
	const ELECTRODE1              ; $6e
	const ELECTRODE2              ; $6f
	const ELECTABUZZ1             ; $70
	const ELECTABUZZ2             ; $71
	const JOLTEON1                ; $72
	const JOLTEON2                ; $73
	const ZAPDOS1                 ; $74
	const ZAPDOS2                 ; $75
	const ZAPDOS3                 ; $76
	const SANDSHREW               ; $77
	const SANDSLASH               ; $78
	const DIGLETT                 ; $79
	const DUGTRIO                 ; $7a
	const MANKEY                  ; $7b
	const PRIMEAPE                ; $7c
	const MACHOP                  ; $7d
	const MACHOKE                 ; $7e
	const MACHAMP                 ; $7f
	const GEODUDE                 ; $80
	const GRAVELER                ; $81
	const GOLEM                   ; $82
	const ONIX                    ; $83
	const CUBONE                  ; $84
	const MAROWAK1                ; $85
	const MAROWAK2                ; $86
	const HITMONLEE               ; $87
	const HITMONCHAN              ; $88
	const RHYHORN                 ; $89
	const RHYDON                  ; $8a
	const KABUTO                  ; $8b
	const KABUTOPS                ; $8c
	const AERODACTYL              ; $8d
	const ABRA                    ; $8e
	const KADABRA                 ; $8f
	const ALAKAZAM                ; $90
	const SLOWPOKE1               ; $91
	const SLOWPOKE2               ; $92
	const SLOWBRO                 ; $93
	const GASTLY1                 ; $94
	const GASTLY2                 ; $95
	const HAUNTER1                ; $96
	const HAUNTER2                ; $97
	const GENGAR                  ; $98
	const DROWZEE                 ; $99
	const HYPNO                   ; $9a
	const MR_MIME                 ; $9b
	const JYNX                    ; $9c
	const MEWTWO1                 ; $9d
	const MEWTWO2                 ; $9e
	const MEWTWO3                 ; $9f
	const MEW1                    ; $a0
	const MEW2                    ; $a1
	const MEW3                    ; $a2
	const PIDGEY                  ; $a3
	const PIDGEOTTO               ; $a4
	const PIDGEOT1                ; $a5
	const PIDGEOT2                ; $a6
	const RATTATA                 ; $a7
	const RATICATE                ; $a8
	const SPEAROW                 ; $a9
	const FEAROW                  ; $aa
	const CLEFAIRY                ; $ab
	const CLEFABLE                ; $ac
	const JIGGLYPUFF1             ; $ad
	const JIGGLYPUFF2             ; $ae
	const JIGGLYPUFF3             ; $af
	const WIGGLYTUFF              ; $b0
	const MEOWTH1                 ; $b1
	const MEOWTH2                 ; $b2
	const PERSIAN                 ; $b3
	const FARFETCHD               ; $b4
	const DODUO                   ; $b5
	const DODRIO                  ; $b6
	const LICKITUNG               ; $b7
	const CHANSEY                 ; $b8
	const KANGASKHAN              ; $b9
	const TAUROS                  ; $ba
	const DITTO                   ; $bb
	const EEVEE                   ; $bc
	const PORYGON                 ; $bd
	const SNORLAX                 ; $be
	const DRATINI                 ; $bf
	const DRAGONAIR               ; $c0
	const DRAGONITE1              ; $c1
	const DRAGONITE2              ; $c2
	const PROFESSOR_OAK           ; $c3
	const IMPOSTER_PROFESSOR_OAK  ; $c4
	const BILL                    ; $c5
	const MR_FUJI                 ; $c6
	const LASS                    ; $c7
	const IMAKUNI_CARD            ; $c8
	const POKEMON_TRADER          ; $c9
	const POKEMON_BREEDER         ; $ca
	const CLEFAIRY_DOLL           ; $cb
	const MYSTERIOUS_FOSSIL       ; $cc
	const ENERGY_RETRIEVAL        ; $cd
	const SUPER_ENERGY_RETRIEVAL  ; $ce
	const ENERGY_SEARCH           ; $cf
	const ENERGY_REMOVAL          ; $d0
	const SUPER_ENERGY_REMOVAL    ; $d1
	const SWITCH                  ; $d2
	const POKEMON_CENTER          ; $d3
	const POKE_BALL               ; $d4
	const SCOOP_UP                ; $d5
	const COMPUTER_SEARCH         ; $d6
	const POKEDEX                 ; $d7
	const PLUSPOWER               ; $d8
	const DEFENDER                ; $d9
	const ITEM_FINDER             ; $da
	const GUST_OF_WIND            ; $db
	const DEVOLUTION_SPRAY        ; $dc
	const POTION                  ; $dd
	const SUPER_POTION            ; $de
	const FULL_HEAL               ; $df
	const REVIVE                  ; $e0
	const MAINTENANCE             ; $e1
	const POKEMON_FLUTE           ; $e2
	const GAMBLER                 ; $e3
	const RECYCLE                 ; $e4
NUM_CARDS EQU const_value - 1
