GRASS_ENERGY            EQU $01
FIRE_ENERGY             EQU $02
WATER_ENERGY            EQU $03
LIGHTNING_ENERGY        EQU $04
FIGHTING_ENERGY         EQU $05
PSYCHIC_ENERGY          EQU $06
DOUBLE_COLORLESS_ENERGY EQU $07
BULBASAUR               EQU $08
IVYSAUR                 EQU $09
VENUSAUR1               EQU $0A
VENUSAUR2               EQU $0B
CATERPIE                EQU $0C
METAPOD                 EQU $0D
BUTTERFREE              EQU $0E
WEEDLE                  EQU $0F
KAKUNA                  EQU $10
BEEDRILL                EQU $11
EKANS                   EQU $12
ARBOK                   EQU $13
NIDORANF                EQU $14
NIDORINA                EQU $15
NIDOQUEEN               EQU $16
NIDORANM                EQU $17
NIDORINO                EQU $18
NIDOKING                EQU $19
ZUBAT                   EQU $1A
GOLBAT                  EQU $1B
ODDISH                  EQU $1C
GLOOM                   EQU $1D
VILEPLUME               EQU $1E
PARAS                   EQU $1F
PARASECT                EQU $20
VENONAT                 EQU $21
VENOMOTH                EQU $22
BELLSPROUT              EQU $23
WEEPINBELL              EQU $24
VICTREEBEL              EQU $25
GRIMER                  EQU $26
MUK                     EQU $27
EXEGGCUTE               EQU $28
EXEGGUTOR               EQU $29
KOFFING                 EQU $2A
WEEZING                 EQU $2B
TANGELA1                EQU $2C
TANGELA2                EQU $2D
SCYTHER                 EQU $2E
PINSIR                  EQU $2F
CHARMANDER              EQU $30
CHARMELEON              EQU $31
CHARIZARD               EQU $32
VULPIX                  EQU $33
NINETAILS1              EQU $34
NINETAILS2              EQU $35
GROWLITHE               EQU $36
ARCANINE1               EQU $37
ARCANINE2               EQU $38
PONYTA                  EQU $39
RAPIDASH                EQU $3A
MAGMAR1                 EQU $3B
MAGMAR2                 EQU $3C
FLAREON1                EQU $3D
FLAREON2                EQU $3E
MOLTRES1                EQU $3F
MOLTRES2                EQU $40
SQUIRTLE                EQU $41
WARTORTLE               EQU $42
BLASTOISE               EQU $43
PSYDUCK                 EQU $44
GOLDUCK                 EQU $45
POLIWAG                 EQU $46
POLIWHIRL               EQU $47
POLIWRATH               EQU $48
TENTACOOL               EQU $49
TENTACRUEL              EQU $4A
SEEL                    EQU $4B
DEWGONG                 EQU $4C
SHELLDER                EQU $4D
CLOYSTER                EQU $4E
KRABBY                  EQU $4F
KINGLER                 EQU $50
HORSEA                  EQU $51
SEADRA                  EQU $52
GOLDEEN                 EQU $53
SEAKING                 EQU $54
STARYU                  EQU $55
STARMIE                 EQU $56
MAGIKARP                EQU $57
GYARADOS                EQU $58
LAPRAS                  EQU $59
VAPOREON1               EQU $5A
VAPOREON2               EQU $5B
OMANYTE                 EQU $5C
OMASTAR                 EQU $5D
ARTICUNO1               EQU $5E
ARTICUNO2               EQU $5F
PIKACHU1                EQU $60
PIKACHU2                EQU $61
PIKACHU3                EQU $62
PIKACHU4                EQU $63
FLYING_PIKACHU          EQU $64
SURFING_PIKACHU1        EQU $65
SURFING_PIKACHU2        EQU $66
RAICHU1                 EQU $67
RAICHU2                 EQU $68
MAGNEMITE1              EQU $69
MAGNEMITE2              EQU $6A
MAGNETON1               EQU $6B
MAGNETON2               EQU $6C
VOLTORB                 EQU $6D
ELECTRODE1              EQU $6E
ELECTRODE2              EQU $6F
ELECTABUZZ1             EQU $70
ELECTABUZZ2             EQU $71
JOLTEON1                EQU $72
JOLTEON2                EQU $73
ZAPDOS1                 EQU $74
ZAPDOS2                 EQU $75
ZAPDOS3                 EQU $76
SANDSHREW               EQU $77
SANDSLASH               EQU $78
DIGLETT                 EQU $79
DUGTRIO                 EQU $7A
MANKEY                  EQU $7B
PRIMEAPE                EQU $7C
MACHOP                  EQU $7D
MACHOKE                 EQU $7E
MACHAMP                 EQU $7F
GEODUDE                 EQU $80
GRAVELER                EQU $81
GOLEM                   EQU $82
ONIX                    EQU $83
CUBONE                  EQU $84
MAROWAK1                EQU $85
MAROWAK2                EQU $86
HITMONLEE               EQU $87
HITMONCHAN              EQU $88
RHYHORN                 EQU $89
RHYDON                  EQU $8A
KABUTO                  EQU $8B
KABUTOPS                EQU $8C
AERODACTYL              EQU $8D
ABRA                    EQU $8E
KADABRA                 EQU $8F
ALAKAZAM                EQU $90
SLOWPOKE1               EQU $91
SLOWPOKE2               EQU $92
SLOWBRO                 EQU $93
GASTLY1                 EQU $94
GASTLY2                 EQU $95
HAUNTER1                EQU $96
HAUNTER2                EQU $97
GENGAR                  EQU $98
DROWZEE                 EQU $99
HYPNO                   EQU $9A
MR_MIME                 EQU $9B
JYNX                    EQU $9C
MEWTWO1                 EQU $9D
MEWTWO2                 EQU $9E
MEWTWO3                 EQU $9F
MEW1                    EQU $A0
MEW2                    EQU $A1
MEW3                    EQU $A2
PIDGEY                  EQU $A3
PIDGEOTTO               EQU $A4
PIDGEOT1                EQU $A5
PIDGEOT2                EQU $A6
RATTATA                 EQU $A7
RATICATE                EQU $A8
SPEAROW                 EQU $A9
FEAROW                  EQU $AA
CLEFAIRY                EQU $AB
CLEFABLE                EQU $AC
JIGGLYPUFF1             EQU $AD
JIGGLYPUFF2             EQU $AE
JIGGLYPUFF3             EQU $AF
WIGGLYTUFF              EQU $B0
MEOWTH1                 EQU $B1
MEOWTH2                 EQU $B2
PERSIAN                 EQU $B3
FARFETCHD               EQU $B4
DODUO                   EQU $B5
DODRIO                  EQU $B6
LICKITUNG               EQU $B7
CHANSEY                 EQU $B8
KANGASKHAN              EQU $B9
TAUROS                  EQU $BA
DITTO                   EQU $BB
EEVEE                   EQU $BC
PORYGON                 EQU $BD
SNORLAX                 EQU $BE
DRATINI                 EQU $BF
DRAGONAIR               EQU $C0
DRAGONITE1              EQU $C1
DRAGONITE2              EQU $C2
PROFESSOR_OAK           EQU $C3
IMPOSTER_PROFESSOR_OAK  EQU $C4
BILL                    EQU $C5
MR_FUJI                 EQU $C6
LASS                    EQU $C7
IMAKUNI_CARD            EQU $C8
POKEMON_TRADER          EQU $C9
POKEMON_BREEDER         EQU $CA
CLEFAIRY_DOLL           EQU $CB
MYSTERIOUS_FOSSIL       EQU $CC
ENERGY_RETRIEVAL        EQU $CD
SUPER_ENERGY_RETRIEVAL  EQU $CE
ENERGY_SEARCH           EQU $CF
ENERGY_REMOVAL          EQU $D0
SUPER_ENERGY_REMOVAL    EQU $D1
SWITCH                  EQU $D2
POKEMON_CENTER          EQU $D3
POKE_BALL               EQU $D4
SCOOP_UP                EQU $D5
COMPUTER_SEARCH         EQU $D6
POKEDEX                 EQU $D7
PLUSPOWER               EQU $D8
DEFENDER                EQU $D9
ITEM_FINDER             EQU $DA
GUST_OF_WIND            EQU $DB
DEVOLUTION_SPRAY        EQU $DC
POTION                  EQU $DD
SUPER_POTION            EQU $DE
FULL_HEAL               EQU $DF
REVIVE                  EQU $E0
MAINTENANCE             EQU $E1
POKEMON_FLUTE           EQU $E2
GAMBLER                 EQU $E3
RECYCLE                 EQU $E4

NUM_CARDS               EQUS "RECYCLE"
