	const_def
	const UNNAMED_DECK                ; $00
	const UNNAMED_DECK_2              ; $01
	const SAMS_PRACTICE_DECK          ; $02
	const PRACTICE_PLAYER_DECK        ; $03
	const SAMS_NORMAL_DECK            ; $04
	const CHARMANDER_AND_FRIENDS_DECK ; $05
	const CHARMANDER_EXTRA_DECK       ; $06
	const SQUIRTLE_AND_FRIENDS_DECK   ; $07
	const SQUIRTLE_EXTRA_DECK         ; $08
	const BULBASAUR_AND_FRIENDS_DECK  ; $09
	const BULBASAUR_EXTRA_DECK        ; $0A
	const LIGHTNING_AND_FIRE_DECK     ; $0B
	const WATER_AND_FIGHTING_DECK     ; $0C
	const GRASS_AND_PSYCHIC_DECK      ; $0D
	const LEGENDARY_MOLTRES_DECK      ; $0E
	const LEGENDARY_ZAPDOS_DECK       ; $0F
	const LEGENDARY_ARTICUNO_DECK     ; $10
	const LEGENDARY_DRAGONITE_DECK    ; $11
	const FIRST_STRIKE_DECK           ; $12
	const ROCK_CRUSHER_DECK           ; $13
	const GO_GO_RAIN_DANCE_DECK       ; $14
	const ZAPPING_SELFDESTRUCT_DECK   ; $15
	const FLOWER_POWER_DECK           ; $16
	const STRANGE_PSYSHOCK_DECK       ; $17
	const WONDERS_OF_SCIENCE_DECK     ; $18
	const FIRE_CHARGE_DECK            ; $19
	const IM_RONALD_DECK              ; $1A
	const POWERFUL_RONALD_DECK        ; $1B
	const INVINCIBLE_RONALD_DECK      ; $1C
	const LEGENDARY_RONALD_DECK       ; $1D
	const MUSCLES_FOR_BRAINS_DECK     ; $1E
	const HEATED_BATTLE_DECK          ; $1F
	const LOVE_TO_BATTLE_DECK         ; $20
	const EXCAVATION_DECK             ; $21
	const BLISTERING_POKEMON_DECK     ; $22
	const HARD_POKEMON_DECK           ; $23
	const WATERFRONT_POKEMON_DECK     ; $24
	const LONELY_FRIENDS_DECK         ; $25
	const SOUND_OF_THE_WAVES_DECK     ; $26
	const PIKACHU_DECK                ; $27
	const BOOM_BOOM_SELFDESTRUCT_DECK ; $28
	const POWER_GENERATOR_DECK        ; $29
	const ETCETERA_DECK               ; $2A
	const FLOWER_GARDEN_DECK          ; $2B
	const KALEIDOSCOPE_DECK           ; $2C
	const GHOST_DECK                  ; $2D
	const NAP_TIME_DECK               ; $2E
	const STRANGE_POWER_DECK          ; $2F
	const FLYIN_POKEMON_DECK          ; $30
	const LOVELY_NIDORAN_DECK         ; $31
	const POISON_DECK                 ; $32
	const ANGER_DECK                  ; $33
	const FLAMETHROWER_DECK           ; $34
	const RESHUFFLE_DECK              ; $35
	const IMAKUNI_DECK                ; $36
DECKS_END EQU const_value + -1
