; in-duel action structs
RSRESET
DEF DUEL_ACTION_STRUCT_ACTION_INDEX RB   ; $0
DEF DUEL_ACTION_STRUCT_CARD_INDEX   RB   ; $1
DEF DUEL_ACTION_STRUCT_ARGS         RB 7 ; $2
; DEF MAX_NUM_DUEL_ACTION_ARGS      EQU _RS - DUEL_ACTION_STRUCT_ARGS ; 7
DEF DUEL_ACTION_STRUCT_TERMINATOR   RB   ; $9
DEF DUEL_ACTION_ARGS_BUFFER_SIZE    EQU _RS - DUEL_ACTION_STRUCT_ARGS ; 8
DEF DUEL_ACTION_STRUCT_SIZE         EQU _RS ; 10

; common argument sets

; duel set-up
RSRESET
DEF DUELSETUP_ARGS_HAS_BASIC_PKMN RB ; $0

; prize cards
RSRESET
DEF SELECTPRIZE_ARGS_BITFIELD              RB ; $0
DEF SELECTPRIZE_ARGS_SELECTED_CARD_INDICES RB MAX_PRIZE_CARDS ; $1

; play pkmn/energy card from hand/deck
RSRESET
DEF PLAYCARD_ARGS_CARD_INDEX                RB ; $0
DEF PLAYCARD_ARGS_TARGET_PLAY_AREA_LOCATION RB ; $1

; new arena pkmn
RSRESET
DEF NEWARENAPKMN_ARGS_FROM_PLAY_AREA_LOCATION RB ; $0

; retreat
RSRESET
DEF RETREAT_ARGS_STATUS    RB ; $0
DEF RETREAT_ARGS_BENCH     RB ; $1
DEF RETREAT_ARGS_COST_LIST RB MAX_RETREAT_COSTS ; $2

; declare
RSRESET
DEF DECLARE_PKMNPOWER_ARGS_CARD_INDEX RB ; $0

RSRESET
DEF DECLARE_ATTACK_ARGS_ATTACK_INDEX RB ; $0

; pkmn powers
RSRESET
DEF PKMNPOWER_ARGS_USER_PLAY_AREA_LOCATION RB ; $0
rsunion
	; general single effect
	DEF PKMNPOWER_ARGS_EFFECT RB ; $1
rsnextu
	; choose 1 pkmn
	DEF PKMNPOWER_ARGS_TARGET_PLAY_AREA_LOCATION RB ; $1
rsnextu
	; coin flip + choose 1 pkmn
	DEF PKMNPOWER_COIN_ARGS_COIN_RESULT               RB ; $1
	DEF PKMNPOWER_COIN_ARGS_TARGET_PLAY_AREA_LOCATION RB ; $2
rsnextu
	; move from-to
	DEF PKMNPOWER_MOVE_ARGS_FROM_PLAY_AREA_LOCATION RB ; $1
	rsunion
		; move from a location to another
		DEF PKMNPOWER_MOVE_ARGS_TO_PLAY_AREA_LOCATION RB ; $2
	rsnextu
		; move card from a location to another
		DEF PKMNPOWER_MOVE_CARD_ARGS_CARD_INDEX            RB ; $2
		DEF PKMNPOWER_MOVE_CARD_ARGS_TO_PLAY_AREA_LOCATION RB ; $3
	endrsunion
endrsunion

; general single target/effect
RSRESET
DEF ATTACK_OR_TRAINER_ARGS_EFFECT RB ; $0

; choose pkmn + x
RSRESET
DEF ATTACK_OR_TRAINER_ARGS_TARGET1_PLAY_AREA_LOCATION RB ; $0
DEF ATTACK_OR_TRAINER_ARGS_TARGET2_PLAY_AREA_LOCATION RB ; $1
DEF ATTACK_OR_TRAINER_ARGS_TARGET3_PLAY_AREA_LOCATION RB ; $2
	; gigashock
	DEF GIGASHOCK_ARGS_TERMINATOR RB ; $3

; choose 1 pkmn from the entire play area
RSRESET
DEF ATTACK_OR_TRAINER_ENTIRE_ARGS_WHOSE_PLAY_AREA           RB ; $0
DEF ATTACK_OR_TRAINER_ENTIRE_ARGS_TARGET_PLAY_AREA_LOCATION RB ; $1

; either pay cost (discard, return to deck, etc.) or choose cards
; from deck, discard pile, hand, defending/attacking pkmn, etc.
RSRESET
DEF ATTACK_OR_TRAINER_CHOOSE_CARDS_ARGS_CARD1_INDEX RB ; $0
DEF ATTACK_OR_TRAINER_CHOOSE_CARDS_ARGS_CARD2_INDEX RB ; $1
	; energy absorption
	DEF ENERGYABSORPTION_ARGS_TERMINATOR RB ; $2

; pay cost, then choose
RSRESET
DEF ATTACK_OR_TRAINER_COST_1_AND_CHOOSE_ARGS_COST_CARD_INDEX    RB ; $0
DEF ATTACK_OR_TRAINER_COST_1_AND_CHOOSE_ARGS_TARGET_CARD1_INDEX RB ; $1
DEF ATTACK_OR_TRAINER_COST_1_AND_CHOOSE_ARGS_TARGET_CARD2_INDEX RB ; $2
	; energy retrieval
	DEF ENERGYRETRIEVAL_ARGS_TERMINATOR RB ; $3

RSRESET
DEF ATTACK_OR_TRAINER_COST_2_AND_CHOOSE_ARGS_COST_CARD1_INDEX   RB ; $0
DEF ATTACK_OR_TRAINER_COST_2_AND_CHOOSE_ARGS_COST_CARD2_INDEX   RB ; $1
DEF ATTACK_OR_TRAINER_COST_2_AND_CHOOSE_ARGS_TARGET_CARD1_INDEX RB ; $2
DEF ATTACK_OR_TRAINER_COST_2_AND_CHOOSE_ARGS_TARGET_CARD2_INDEX RB ; $3
DEF ATTACK_OR_TRAINER_COST_2_AND_CHOOSE_ARGS_TARGET_CARD3_INDEX RB ; $4
DEF ATTACK_OR_TRAINER_COST_2_AND_CHOOSE_ARGS_TARGET_CARD4_INDEX RB ; $5

; choose 1 attack
RSRESET
DEF ATTACK_OR_TRAINER_CHOOSE_ATTACK_ARGS_ATTACK_INDEX RB ; $0

; coin flip (TAILS/HEADS, number of tails/heads) + x
; but not for recycle
RSRESET
DEF ATTACK_OR_TRAINER_COIN_ARGS_COIN_RESULT RB ; $0
rsunion
	; choose 1 pkmn
	DEF ATTACK_OR_TRAINER_COIN_ARGS_TARGET_PLAY_AREA_LOCATION RB ; $1
rsnextu
	; choose card
	DEF ATTACK_OR_TRAINER_COIN_ARGS_TARGET_CARD_INDEX RB ; $1
rsnextu
	; thunderstorm
	DEF THUNDERSTORM_ARGS_TARGET_RESULTS RB MAX_BENCH_POKEMON ; $1
	DEF THUNDERSTORM_ARGS_TERMINATOR     RB ; $6
endrsunion

; prophecy
RSRESET
DEF PROPHECY_ARGS_WHOSE_DECK   RB   ; $0
DEF PROPHECY_ARGS_CARD_INDICES RB 3 ; $1
DEF PROPHECY_ARGS_TERMINATOR   RB   ; $4

; wildfire
RSRESET
DEF WILDFIRE_ARGS_NUM_CARDS RB ; $0

; potion
RSRESET
DEF POTION_ARGS_TARGET_PLAY_AREA_LOCATION RB ; $0
DEF POTION_ARGS_HEAL_AMOUNT               RB ; $1

; super potion
RSRESET
DEF SUPERPOTION_ARGS_COST_ENERGY_CARD_INDEX     RB ; $0
DEF SUPERPOTION_ARGS_TARGET_PLAY_AREA_LOCATION  RB ; $1
DEF SUPERPOTION_ARGS_HEAL_AMOUNT                RB ; $2

; (super) energy removal
RSRESET
DEF ENERGYREMOVAL_ARGS_TARGET1_PLAY_AREA_LOCATION RB ; $0
DEF ENERGYREMOVAL_ARGS_TARGET1_ENERGY_CARD_INDEX  RB ; $1
DEF ENERGYREMOVAL_ARGS_TARGET2_PLAY_AREA_LOCATION RB ; $2
DEF ENERGYREMOVAL_ARGS_TARGET2_ENERGY_CARD1_INDEX RB ; $3
DEF ENERGYREMOVAL_ARGS_TARGET2_ENERGY_CARD2_INDEX RB ; $4
DEF ENERGYREMOVAL_ARGS_TERMINATOR                 RB ; $5

; scoop-up
RSRESET
DEF SCOOPUP_ARGS_TARGET_PLAY_AREA_LOCATION         RB ; $0
DEF SCOOPUP_ARGS_NEW_ARENA_FROM_PLAY_AREA_LOCATION RB ; $1

; devolution spray
RSRESET
DEF DEVOLUTIONSPRAY_ARGS_TARGET_PLAY_AREA_LOCATION RB ; $0
DEF DEVOLUTIONSPRAY_ARGS_UPPER_EVO_CARD_INDEX      RB ; $1
DEF DEVOLUTIONSPRAY_ARGS_LOWER_EVO_CARD_INDEX      RB ; $2
DEF DEVOLUTIONSPRAY_ARGS_TERMINATOR                RB ; $3

; pokedex
RSRESET
DEF POKEDEX_ARGS_CARD1_INDEX RB ; $0
DEF POKEDEX_ARGS_CARD2_INDEX RB ; $1
DEF POKEDEX_ARGS_CARD3_INDEX RB ; $2
DEF POKEDEX_ARGS_CARD4_INDEX RB ; $3
DEF POKEDEX_ARGS_CARD5_INDEX RB ; $4
DEF POKEDEX_ARGS_TERMINATOR  RB ; $5

; AI-side buffer
RSRESET
DEF AI_TRAINER_ARGS             RB 6 ; $0
; DEF MAX_NUM_AI_TRAINER_ARGS   EQU _RS ; 6
DEF AI_TRAINER_ARGS_TERMINATOR  RB   ; $6
DEF AI_TRAINER_ARGS_BUFFER_SIZE EQU _RS ; 7

RSRESET
DEF AI_TRAINER_ARGS_DECLARE_CARD_INDEX RB ; $0

; some cards use different offset than in duel action

; super potion
RSRESET
DEF AI_SUPERPOTION_ARGS_TARGET_PLAY_AREA_LOCATION RB ; $0

; pokemon breeder
; reverse order against PLAYCARD_ARGS_*
RSRESET
DEF AI_POKEMONBREEDER_ARGS_TARGET_PLAY_AREA_LOCATION RB ; $0
DEF AI_POKEMONBREEDER_ARGS_EVO_CARD_INDEX            RB ; $1

; pluspower
RSRESET
DEF AI_PLUSPOWER_ARGS_ATTACK_INDEX RB ; $0

; pokedex
; starting at 1
RSSET 1
DEF AI_POKEDEX_ARGS_CARD1_INDEX RB ; $1
DEF AI_POKEDEX_ARGS_CARD2_INDEX RB ; $2
DEF AI_POKEDEX_ARGS_CARD3_INDEX RB ; $3
DEF AI_POKEDEX_ARGS_CARD4_INDEX RB ; $4
DEF AI_POKEDEX_ARGS_CARD5_INDEX RB ; $5

; maintenance
; starting at 1
RSSET 1
DEF AI_MAINTENANCE_ARGS_CARD1_INDEX RB ; $1
DEF AI_MAINTENANCE_ARGS_CARD2_INDEX RB ; $2

; itemfinder, computer search
; target card arg at first instead of last
RSRESET
DEF AI_ITEMFINDER_COMPUTERSEARCH_ARGS_TARGET_CARD_INDEX RB ; $0
DEF AI_ITEMFINDER_COMPUTERSEARCH_ARGS_COST_CARD1_INDEX  RB ; $1
DEF AI_ITEMFINDER_COMPUTERSEARCH_ARGS_COST_CARD2_INDEX  RB ; $2
