; in-duel action structs
RSRESET
DEF DUEL_ACTION_STRUCT_ACTION_INDEX RB   ; $0
DEF DUEL_ACTION_STRUCT_CARD_INDEX   RB   ; $1
DEF DUEL_ACTION_STRUCT_ARGS         RB 7 ; $2
DEF DUEL_ACTION_STRUCT_TERMINATOR   RB   ; $9

DEF DUEL_ACTION_ARGS_SIZE   EQU DUEL_ACTION_STRUCT_TERMINATOR - DUEL_ACTION_STRUCT_ARGS ; 7
DEF DUEL_ACTION_STRUCT_SIZE EQU _RS ; 10

DEF AI_TRAINER_ARGS_SIZE EQU 6

; common sets of argument offset in DUEL_ACTION_STRUCT_ARGS

; play pkmn/energy card from hand/deck
RSRESET
DEF PLAYCARD_ARGS_CARD_INDEX   RB ; $0
DEF PLAYCARD_ARGS_TO_PLAY_AREA RB ; $1

; duel set-up
RSRESET
DEF DUELSETUP_ARGS_HAS_BASIC_PKMN RB ; $0

; new arena pkmn
RSRESET
DEF NEWARENAPKMN_ARGS_FROM_PLAY_AREA RB ; $0

; retreat
RSRESET
DEF RETREAT_ARGS_STATUS    RB   ; $0
DEF RETREAT_ARGS_BENCH     RB   ; $1
DEF RETREAT_ARGS_COST_LIST RB 5 ; $2

; declare / begin using
RSRESET
DEF DECLARE_PKMNPOWER_ARGS_CARD_INDEX RB ; $0

RSRESET
DEF DECLARE_ATTACK_ARGS_ATTACK_INDEX RB ; $0

; pkmn powers
RSRESET
DEF PKMNPOWER_ARGS_USER_PLAY_AREA RB ; $0
rsunion
	; choose 1 pkmn
	DEF PKMNPOWER_TARGET_ARGS_TO_PLAY_AREA RB ; $1
rsnextu
	; coin flip + choose 1 pkmn
	DEF PKMNPOWER_COIN_ARGS_COIN_RESULT  RB ; $1
	DEF PKMNPOWER_COIN_ARGS_TO_PLAY_AREA RB ; $2
rsnextu
	; move from-to
	DEF PKMNPOWER_MOVE_ARGS_FROM_PLAY_AREA RB ; $1
	DEF PKMNPOWER_MOVE_ARGS_TO_PLAY_AREA   RB ; $2
rsnextu
	; energy trans
	DEF ENERGYTRANS_ARGS_FROM_PLAY_AREA RB ; $1
	DEF ENERGYTRANS_ARGS_ENERGY_INDEX   RB ; $2
	DEF ENERGYTRANS_ARGS_TO_PLAY_AREA   RB ; $3
rsnextu
	; shift
	DEF VENOMOTH_SHIFT_ARGS_TARGET_COLOR RB ; $1
rsnextu
	; peek
	DEF MANKEY_PEEK_ARGS_TARGET RB ; $1
endrsunion

; attacks and trainers
; choose 1 pkmn + x (chosen either by player or opponent)
RSRESET
DEF ATTACK_OR_TRAINER_TARGET_ARGS_TO_PLAY_AREA        RB ; $0
DEF ATTACK_OR_TRAINER_TARGET_ARGS_ATTACHED_CARD_INDEX RB ; $1

; choose 1 pkmn, either yours or opponent's
RSRESET
DEF ATTACK_OR_TRAINER_ANY_TARGET_ARGS_WHOSE_PLAY_AREA RB ; $0
DEF ATTACK_OR_TRAINER_ANY_TARGET_ARGS_TO_PLAY_AREA    RB ; $1

; choose cards from deck, discard pile, defending/attacking pkmn, etc.
RSRESET
DEF ATTACK_OR_TRAINER_CHOOSE_CARDS_ARGS_CARD1_INDEX RB ; $0
DEF ATTACK_OR_TRAINER_CHOOSE_CARDS_ARGS_CARD2_INDEX RB ; $1
; rsunion
	; terminator for energy absorption
	DEF ENERGYABSORPTION_ARGS_TERMINATOR RB ; $2
; endrsunion

; coin flip + x, but not for recycle
RSRESET
DEF ATTACK_OR_TRAINER_COIN_ARGS_COIN_RESULT  RB ; $0
DEF ATTACK_OR_TRAINER_COIN_ARGS_TO_PLAY_AREA RB ; $1

; choose 1 attack
RSRESET
DEF ATTACK_OR_TRAINER_CHOOSE_ATTACK_ARGS_ATTACK_INDEX RB ; $0

; misc attacks
; wildfire
RSRESET
DEF WILDFIRE_ARGS_NUM_CARDS RB ; $0

; gigashock
RSRESET
DEF GIGASHOCK_ARGS_TARGETS_PLAY_AREA RB 3 ; $0
DEF GIGASHOCK_ARGS_TERMINATOR        RB   ; $3

; thunderstorm
RSRESET
DEF THUNDERSTORM_ARGS_NUM_TAILS    RB ; $0
DEF THUNDERSTORM_ARGS_COIN_RESULTS RB MAX_BENCH_POKEMON ; $1
; DEF THUNDERSTORM_ARGS_TERMINATOR   RB ; $6

; prophecy
RSRESET
DEF PROPHECY_ARGS_WHOSE_DECK   RB   ; $0
DEF PROPHECY_ARGS_CARD_INDICES RB 3 ; $1

; scavenge
RSRESET
DEF SCAVENGE_ARGS_DISCARD_ENERGY_INDEX RB ; $0
DEF SCAVENGE_ARGS_TRAINER_CARD_INDEX   RB ; $1

; mystery attack
RSRESET
DEF MYSTERYATTACK_ARGS_EFFECT_INDEX RB ; $0

; conversion 1/2
RSRESET
DEF CONVERSION_1_OR_2_ARGS_NEW_COLOR RB ; $0

; misc trainers
; potion
RSRESET
DEF POTION_ARGS_TO_PLAY_AREA RB ; $0
DEF POTION_ARGS_HEAL_AMOUNT  RB ; $1

; super potion
RSRESET
DEF SUPERPOTION_ARGS_DISCARD_ENERGY_INDEX RB ; $0
DEF SUPERPOTION_ARGS_TO_PLAY_AREA         RB ; $1
DEF SUPERPOTION_ARGS_HEAL_AMOUNT          RB ; $2
	; shorter args for AI
	RSRESET
	DEF AI_SUPERPOTION_ARGS_TO_PLAY_AREA RB ; $0

; energy retrieval
RSRESET
DEF ENERGYRETRIEVAL_ARGS_DISCARD_CARD_INDEX RB ; $0
DEF ENERGYRETRIEVAL_ARGS_ENERGY1_INDEX      RB ; $1
DEF ENERGYRETRIEVAL_ARGS_ENERGY2_INDEX      RB ; $2
DEF ENERGYRETRIEVAL_ARGS_TERMINATOR         RB ; $3

; super energy retrieval
RSRESET
DEF SUPERENERGYRETRIEVAL_ARGS_DISCARD_CARD1_INDEX RB ; $0
DEF SUPERENERGYRETRIEVAL_ARGS_DISCARD_CARD2_INDEX RB ; $1
DEF SUPERENERGYRETRIEVAL_ARGS_ENERGY1_INDEX       RB ; $2
DEF SUPERENERGYRETRIEVAL_ARGS_ENERGY2_INDEX       RB ; $3
DEF SUPERENERGYRETRIEVAL_ARGS_ENERGY3_INDEX       RB ; $4
DEF SUPERENERGYRETRIEVAL_ARGS_ENERGY4_INDEX       RB ; $5
DEF SUPERENERGYRETRIEVAL_ARGS_TERMINATOR          RB ; $6

; super energy removal
RSRESET
DEF SUPERENERGYREMOVAL_ARGS_OWN_PKMN_PLAY_AREA RB ; $0
DEF SUPERENERGYREMOVAL_ARGS_OWN_ENERGY_INDEX   RB ; $1
DEF SUPERENERGYREMOVAL_ARGS_OPP_PKMN_PLAY_AREA RB ; $2
DEF SUPERENERGYREMOVAL_ARGS_OPP_ENERGY1_INDEX  RB ; $3
DEF SUPERENERGYREMOVAL_ARGS_OPP_ENERGY2_INDEX  RB ; $4
DEF SUPERENERGYREMOVAL_ARGS_TERMINATOR         RB ; $5

; item finder and computer search
RSRESET
DEF ITEMFINDER_OR_COMPUTERSEARCH_ARGS_DISCARD_CARD1_INDEX RB ; $0
DEF ITEMFINDER_OR_COMPUTERSEARCH_ARGS_DISCARD_CARD2_INDEX RB ; $1
DEF ITEMFINDER_OR_COMPUTERSEARCH_ARGS_TARGET_CARD_INDEX   RB ; $2
	; different arg order for AI
	RSRESET
	DEF AI_ITEMFINDER_OR_COMPUTERSEARCH_ARGS_TARGET_CARD_INDEX   RB ; $0
	DEF AI_ITEMFINDER_OR_COMPUTERSEARCH_ARGS_DISCARD_CARD1_INDEX RB ; $1
	DEF AI_ITEMFINDER_OR_COMPUTERSEARCH_ARGS_DISCARD_CARD2_INDEX RB ; $2

; poke ball
RSRESET
DEF POKEBALL_ARGS_COIN_RESULT       RB ; $0
DEF POKEBALL_ARGS_SEARCH_CARD_INDEX RB ; $1
	; different arg for AI
	RSRESET
	DEF AI_POKEBALL_ARGS_SEARCH_CARD_INDEX RB ; $0

; pokedex
RSRESET
DEF POKEDEX_ARGS_CARD1_INDEX RB ; $0
DEF POKEDEX_ARGS_CARD2_INDEX RB ; $1
DEF POKEDEX_ARGS_CARD3_INDEX RB ; $2
DEF POKEDEX_ARGS_CARD4_INDEX RB ; $3
DEF POKEDEX_ARGS_CARD5_INDEX RB ; $4
DEF POKEDEX_ARGS_TERMINATOR  RB ; $5
	; different arg offset for AI
	RSSET 1
	DEF AI_POKEDEX_ARGS_CARD1_INDEX RB ; $0
	DEF AI_POKEDEX_ARGS_CARD2_INDEX RB ; $1
	DEF AI_POKEDEX_ARGS_CARD3_INDEX RB ; $2
	DEF AI_POKEDEX_ARGS_CARD4_INDEX RB ; $3
	DEF AI_POKEDEX_ARGS_CARD5_INDEX RB ; $4

; pluspower (ai only)
RSRESET
DEF AI_PLUSPOWER_ARGS_ATTACK_INDEX RB ; $0

; pokemon breeder
; same as PLAYCARD_ARGS_* for player
; RSRESET
; DEF POKEMONBREEDER_ARGS_EVO_CARD_INDEX RB ; $0
; DEF POKEMONBREEDER_ARGS_TO_PLAY_AREA   RB ; $1
	; different arg order for AI
	RSRESET
	DEF AI_POKEMONBREEDER_ARGS_TO_PLAY_AREA   RB ; $0
	DEF AI_POKEMONBREEDER_ARGS_EVO_CARD_INDEX RB ; $1

; scoop up
RSRESET
DEF SCOOPUP_ARGS_TO_PLAY_AREA        RB ; $0
DEF SCOOPUP_ARGS_FROM_BENCH_TO_ARENA RB ; $1

; pokemon trader
RSRESET
DEF POKEMONTRADER_ARGS_HAND_CARD_INDEX RB ; $0
DEF POKEMONTRADER_ARGS_DECK_CARD_INDEX RB ; $1

; maintenance
RSRESET
DEF MAINTENANCE_ARGS_RETURN_CARD1_INDEX RB ; $0
DEF MAINTENANCE_ARGS_RETURN_CARD2_INDEX RB ; $1
	; different arg offset for AI
	RSSET 1
	DEF AI_MAINTENANCE_ARGS_RETURN_CARD1_INDEX RB ; $1
	DEF AI_MAINTENANCE_ARGS_RETURN_CARD2_INDEX RB ; $2

; devolution spray
RSRESET
DEF DEVOLUTIONSPRAY_ARGS_TO_PLAY_AREA         RB ; $0
DEF DEVOLUTIONSPRAY_ARGS_UPPER_EVO_CARD_INDEX RB ; $1
DEF DEVOLUTIONSPRAY_ARGS_LOWER_EVO_CARD_INDEX RB ; $2
DEF DEVOLUTIONSPRAY_ARGS_TERMINATOR           RB ; $3

; prize cards
RSRESET
DEF SELECTPRIZE_ARGS_BITFIELD              RB   ; $0
DEF SELECTPRIZE_ARGS_SELECTED_CARD_INDICES RB 6 ; $1
