; wCardPageNumber constants
CARDPAGE_POKEMON_OVERVIEW    EQU $01
CARDPAGE_POKEMON_MOVE1_1     EQU $02
CARDPAGE_POKEMON_MOVE1_2     EQU $03
CARDPAGE_POKEMON_MOVE2_1     EQU $04
CARDPAGE_POKEMON_MOVE2_2     EQU $05
CARDPAGE_POKEMON_DESCRIPTION EQU $06
CARDPAGE_ENERGY              EQU $09
CARDPAGE_TRAINER_1           EQU $0d
CARDPAGE_TRAINER_2           EQU $0e

; wMovePageNumber constants
MOVEPAGE_MOVE1_1 EQU $00
MOVEPAGE_MOVE1_2 EQU $01
MOVEPAGE_MOVE2_1 EQU $02
MOVEPAGE_MOVE2_2 EQU $03

; wCardPageType constants
CARDPAGETYPE_NOT_PLAY_AREA EQU $00
CARDPAGETYPE_PLAY_AREA     EQU $01

; card type header constants ($10-tile headers in DuelCardHeaderGraphics)
HEADER_TRAINER EQU $00
HEADER_ENERGY  EQU $01
HEADER_POKEMON EQU $02

; Box message id's
	const_def
	const BOXMSG_PLAYERS_TURN
	const BOXMSG_OPPONENTS_TURN
	const BOXMSG_BETWEEN_TURNS
	const BOXMSG_DECISION
	const BOXMSG_BENCH_POKEMON
	const BOXMSG_ARENA_POKEMON
	const BOXMSG_COIN_TOSS

; wDuelDisplayedScreen constants
DUEL_MAIN_SCENE     EQU $01
PLAY_AREA_CARD_LIST EQU $02
COIN_TOSS           EQU $06
DRAW_CARDS          EQU $07
LARGE_CARD_PICTURE  EQU $08
SHUFFLE_DECK        EQU $09
CHECK_PLAY_AREA     EQU $0a

; wCardListItemSelectionMenuType constants
;NONE        EQU $00
PLAY_CHECK   EQU $01
SELECT_CHECK EQU $02

; wInPlayAreaCurPosition constants
	const_def
	const INPLAYAREA_PLAYER_BENCH_1      ; $00
	const INPLAYAREA_PLAYER_BENCH_2      ; $01
	const INPLAYAREA_PLAYER_BENCH_3      ; $02
	const INPLAYAREA_PLAYER_BENCH_4      ; $03
	const INPLAYAREA_PLAYER_BENCH_5      ; $04
	const INPLAYAREA_PLAYER_ACTIVE       ; $05
	const INPLAYAREA_PLAYER_HAND         ; $06
	const INPLAYAREA_PLAYER_DISCARD_PILE ; $07
	const INPLAYAREA_OPP_ACTIVE          ; $08
	const INPLAYAREA_OPP_HAND            ; $09
	const INPLAYAREA_OPP_DISCARD_PILE    ; $0a
	const INPLAYAREA_OPP_BENCH_1         ; $0b
	const INPLAYAREA_OPP_BENCH_2         ; $0c
	const INPLAYAREA_OPP_BENCH_3         ; $0d
	const INPLAYAREA_OPP_BENCH_4         ; $0e
	const INPLAYAREA_OPP_BENCH_5         ; $0f
	const INPLAYAREA_PLAYER_PLAY_AREA    ; $10
	const INPLAYAREA_OPP_PLAY_AREA       ; $11
