; in-duel action structs
RSRESET
DEF DUEL_ACTION_STRUCT_ACTION_INDEX RB   ; $0
DEF DUEL_ACTION_STRUCT_CARD_INDEX   RB   ; $1
DEF DUEL_ACTION_STRUCT_ARGS         RB 7 ; $2
DEF DUEL_ACTION_STRUCT_TERMINATOR   RB   ; $9

DEF DUEL_ACTION_ARGS_SIZE   EQU DUEL_ACTION_STRUCT_TERMINATOR - DUEL_ACTION_STRUCT_ARGS ; 7
DEF DUEL_ACTION_STRUCT_SIZE EQU _RS ; 10

; common sets of argument offset in DUEL_ACTION_STRUCT_ARGS
; play pkmn/energy card from hand
RSRESET
DEF PLAYCARD_ARGS_CARD_INDEX   RB ; $0
DEF PLAYCARD_ARGS_TO_PLAY_AREA RB ; $1

; retreat
RSRESET
DEF RETREAT_ARGS_STATUS    RB   ; $0
DEF RETREAT_ARGS_BENCH     RB   ; $1
DEF RETREAT_ARGS_COST_LIST RB 5 ; $2

; pkmn powers
RSRESET
DEF PKMNPOWER_ARGS_PLAY_AREA RB ; $0

; choose-1-pkmn effect
DEF PKMNPOWER_TARGET_ARGS_TO_PLAY_AREA RB ; $1

; coin flip + choose-1-pkmn effect
RSSET PKMNPOWER_ARGS_PLAY_AREA + 1
DEF PKMNPOWER_COIN_ARGS_COIN_RESULT  RB ; $1
DEF PKMNPOWER_COIN_ARGS_TO_PLAY_AREA RB ; $2

; move from-to effect
RSSET PKMNPOWER_ARGS_PLAY_AREA + 1
DEF PKMNPOWER_MOVE_ARGS_FROM_PLAY_AREA RB ; $1
DEF PKMNPOWER_MOVE_ARGS_TO_PLAY_AREA   RB ; $2

; energy trans
RSSET PKMNPOWER_ARGS_PLAY_AREA + 1
DEF ENERGYTRANS_ARGS_FROM_PLAY_AREA RB ; $1
DEF ENERGYTRANS_ARGS_ENERGY_INDEX   RB ; $2
DEF ENERGYTRANS_ARGS_TO_PLAY_AREA   RB ; $3

; shift
RSSET PKMNPOWER_ARGS_PLAY_AREA + 1
DEF VENOMOTH_SHIFT_ARGS_TARGET_COLOR RB ; $1

; peek
RSSET PKMNPOWER_ARGS_PLAY_AREA + 1
DEF MANKEY_PEEK_ARGS_TARGET RB ; $1

; trainers
; potion
RSRESET
DEF POTION_ARGS_TO_PLAY_AREA RB ; $0
DEF POTION_ARGS_HEAL_AMOUNT  RB ; $1

; super potion
RSRESET
DEF SUPERPOTION_ARGS_DISCARD_ENERGY_INDEX RB ; $0
DEF SUPERPOTION_ARGS_TO_PLAY_AREA         RB ; $1
DEF SUPERPOTION_ARGS_HEAL_AMOUNT          RB ; $2

; prize cards
RSRESET
DEF SELECTPRIZE_ARGS_BITFIELD              RB   ; $0
DEF SELECTPRIZE_ARGS_SELECTED_CARD_INDICES RB 6 ; $1
