; cgb palette size
DEF palettes EQUS "* PAL_SIZE"

DEF NUM_BACKGROUND_PALETTES EQU 8
DEF NUM_OBJECT_PALETTES     EQU 8

DEF PALRGB_WHITE EQU (COLOR_CH_MAX << B_COLOR_BLUE) | (COLOR_CH_MAX << B_COLOR_GREEN) | (COLOR_CH_MAX << B_COLOR_RED)

; tile size
DEF tiles EQUS "* TILE_SIZE"

DEF TILE_SIZE_1BPP EQU 8 ; bytes
DEF tiles_1bpp EQUS "* TILE_SIZE_1BPP"

DEF CARD_HEADER_TILE_SIZE  EQU 8 * 2 ; tiles
DEF REGULAR_ICON_TILE_SIZE EQU 2 * 2 ; tiles

; icon tile offsets

; card symbols
DEF CARD_TYPE_ICON_TILE_START EQU $d0

RSSET CARD_TYPE_ICON_TILE_START
DEF ICON_TILE_BASIC_POKEMON   RL ; $d0

DEF ICON_TILE_EVO_OR_TRAINER_OFFSET EQU _RS - ICON_TILE_BASIC_POKEMON ; $04
DEF ICON_TILE_STAGE_1_POKEMON RL ; $d4
DEF ICON_TILE_STAGE_2_POKEMON RL ; $d8
DEF ICON_TILE_TRAINER         RL ; $dc
DEF NUM_EVO_OR_TRAINER_ICON_TILES EQU _RS - ICON_TILE_STAGE_1_POKEMON ; $0c

DEF ICON_TILE_POKEMON_TYPES EQU _RS ; $e0
DEF ICON_TILE_FIRE            RL ; $e0
DEF ICON_TILE_GRASS           RL ; $e4
DEF ICON_TILE_LIGHTNING       RL ; $e8
DEF ICON_TILE_WATER           RL ; $ec
DEF ICON_TILE_FIGHTING        RL ; $f0
DEF ICON_TILE_PSYCHIC         RL ; $f4
DEF ICON_TILE_COLORLESS       RL ; $f8
DEF ICON_TILE_ENERGY          RL ; $fc

DEF NUM_CARD_TYPE_ICON_TILES EQU _RS - CARD_TYPE_ICON_TILE_START ; $30

; CardSymbolTable uses different order
	const_def
	const CARD_SYMBOL_FIRE            ; $0
	const CARD_SYMBOL_GRASS           ; $1
	const CARD_SYMBOL_LIGHTNING       ; $2
	const CARD_SYMBOL_WATER           ; $3
	const CARD_SYMBOL_FIGHTING        ; $4
	const CARD_SYMBOL_PSYCHIC         ; $5
	const CARD_SYMBOL_COLORLESS       ; $6
	const CARD_SYMBOL_ENERGY          ; $7
	const CARD_SYMBOL_BASIC_POKEMON   ; $8
	const CARD_SYMBOL_STAGE_1_POKEMON ; $9
	const CARD_SYMBOL_STAGE_2_POKEMON ; $a
	const CARD_SYMBOL_TRAINER         ; $b

; check pokemon screen symbols
RSRESET
DEF ICON_TILE_CHECK_POKEMON_SCREEN_BASIC                 RL ; $00
DEF ICON_TILE_CHECK_POKEMON_SCREEN_STAGE1                RL ; $04
DEF ICON_TILE_CHECK_POKEMON_SCREEN_STAGE2                RL ; $08
DEF ICON_TILE_CHECK_POKEMON_SCREEN_STAGE2_WITHOUT_STAGE1 RL ; $0c
DEF NUM_CHECK_POKEMON_SCREEN_STAGE_ICON_TILES EQU _RS ; $10

DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_ACT   RB 3 ; $10
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BPX   RW   ; $13
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP1   RB   ; $15
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP2   RB   ; $16
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP3   RB   ; $17
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP4   RB   ; $18
DEF ICON_TILE_CHECK_POKEMON_SCREEN_PLAYER_BP5   RB   ; $19
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_ACT RB 3 ; $1a
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BPX RW   ; $1d
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP1 RB   ; $1f
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP2 RB   ; $20
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP3 RB   ; $21
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP4 RB   ; $22
DEF ICON_TILE_CHECK_POKEMON_SCREEN_OPPONENT_BP5 RB   ; $23
DEF NUM_CHECK_POKEMON_SCREEN_ICON_TILES EQU _RS ; $24

; play area screen symbols
RSRESET
DEF ICON_TILE_PLAY_AREA_SCREEN_HAND                        RL ; $00
DEF ICON_TILE_PLAY_AREA_SCREEN_DECK                        RL ; $04
DEF ICON_TILE_PLAY_AREA_SCREEN_DISCARD_PILE                RL ; $08
DEF ICON_TILE_PLAY_AREA_SCREEN_PRIZE                       RL ; $0c
DEF ICON_TILE_PLAY_AREA_SCREEN_PRIZE_EMPTY                 RL ; $10
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_BASIC                 RL ; $14
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_STAGE1                RL ; $18
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_STAGE2                RL ; $1c
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_STAGE2_WITHOUT_STAGE1 RL ; $20
DEF ICON_TILE_PLAY_AREA_SCREEN_BENCH_EMPTY                 RL ; $24
DEF ICON_TILE_PLAY_AREA_SCREEN_TARGET_ARROW                RB ; $28
DEF ICON_TILE_PLAY_AREA_SCREEN_29                          RL ; $29
DEF NUM_PLAY_AREA_SCREEN_ICON_TILES EQU _RS ; $2d

; setup symbols
RSRESET
DEF ICON_TILE_SETUP_FACEDOWN_ARENA RB 4 * 3 ; $0
DEF ICON_TILE_SETUP_FACEDOWN_PRIZE RB       ; $c
DEF NUM_SETUP_ICON_TILES EQU _RS ; $d

; coin toss result symbols
RSRESET
DEF ICON_TILE_COIN_TOSS_HEADS RL ; $0
DEF ICON_TILE_COIN_TOSS_TAILS RL ; $4
DEF NUM_COIN_TOSS_RESULT_ICON_TILES EQU _RS ; $8

; card / duel menu borders
RSRESET
DEF BORDER_TILE_TOP_LEFT     RB ; $0
DEF BORDER_TILE_TOP_RIGHT    RB ; $1
DEF BORDER_TILE_BOTTOM_LEFT  RB ; $2
DEF BORDER_TILE_BOTTOM_RIGHT RB ; $3
DEF BORDER_TILE_TOP          RB ; $4
DEF BORDER_TILE_BOTTOM       RB ; $5
DEF BORDER_TILE_LEFT         RB ; $6
DEF BORDER_TILE_RIGHT        RB ; $7
DEF NUM_CARD_OR_DUEL_MENU_BORDER_TILES EQU _RS ; $8

; real-set symbols
RSRESET
DEF ICON_TILE_JUNGLE RL ; $0
DEF ICON_TILE_FOSSIL RL ; $4
DEF ICON_TILE_GB     RL ; $8

; draw card screen symbols
RSRESET
DEF ICON_TILE_DRAW_CARDS_SCREEN_DECK RL ; $0
DEF ICON_TILE_DRAW_CARDS_SCREEN_HAND RL ; $4
DEF NUM_DRAW_CARDS_SCREEN_ICON_TILES EQU _RS ; $8

; duel box messages
DEF DUEL_BOX_MESSAGE_TILE_SIZE EQU 10 * 4 ; tiles

; printer tile offsets in sGfxBuffer1
RSRESET
DEF PRINTER_TILE_SYMBOLS   RB NUM_PRINTER_SYM_CHARS              ; $00
DEF PRINTER_TILE_BORDERS   RB NUM_CARD_OR_DUEL_MENU_BORDER_TILES ; $30
DEF PRINTER_TILE_CARD_TYPE RL                                    ; $38

; graphics table constants
; (see src/engine/gfx/gfx_table_pointers.asm)
RSRESET
DEF GFXTABLE_TILEMAPS          RW ; $0
DEF GFXTABLE_TILESETS          RW ; $2
DEF GFXTABLE_SPRITES           RW ; $4
DEF GFXTABLE_SPRITE_ANIMATIONS RW ; $6
DEF GFXTABLE_PALETTES          RW ; $8
