	const_def
	const MUSIC_STOP          ; $00
	const MUSIC_TITLESCREEN   ; $01
	const MUSIC_DUELTHEME1    ; $02
	const MUSIC_DUELTHEME2    ; $03
	const MUSIC_DUELTHEME3    ; $04
	const MUSIC_PAUSEMENU     ; $05
	const MUSIC_PCMAINMENU    ; $06
	const MUSIC_DECKMACHINE   ; $07
	const MUSIC_CARDPOP       ; $08
	const MUSIC_OVERWORLD     ; $09
	const MUSIC_POKEMONDOME   ; $0A
	const MUSIC_CHALLENGEHALL ; $0B
	const MUSIC_CLUB1         ; $0C
	const MUSIC_CLUB2         ; $0D
	const MUSIC_CLUB3         ; $0E
	const MUSIC_RONALD        ; $0F
	const MUSIC_IMAKUNI       ; $10
	const MUSIC_HALLOFHONOR   ; $11
	const MUSIC_CREDITS       ; $12
	const MUSIC_UNUSED_13     ; $13
	const MUSIC_UNUSED_14     ; $14
	const MUSIC_MATCHSTART1   ; $15
	const MUSIC_MATCHSTART2   ; $16
	const MUSIC_MATCHSTART3   ; $17
	const MUSIC_MATCHVICTORY  ; $18
	const MUSIC_MATCHLOSS     ; $19
	const MUSIC_DARKDIDDLY    ; $1A
	const MUSIC_UNUSED_1B     ; $1B
	const MUSIC_BOOSTERPACK   ; $1C
	const MUSIC_MEDAL         ; $1D
	const MUSIC_UNUSED_1E     ; $1E
