	const_def
	const MUSIC_STOP           ; $00
	const MUSIC_TITLESCREEN    ; $01
	const MUSIC_DUEL_THEME_1   ; $02
	const MUSIC_DUEL_THEME_2   ; $03
	const MUSIC_DUEL_THEME_3   ; $04
	const MUSIC_PAUSE_MENU     ; $05
	const MUSIC_PC_MAIN_MENU   ; $06
	const MUSIC_DECK_MACHINE   ; $07
	const MUSIC_CARD_POP       ; $08
	const MUSIC_OVERWORLD      ; $09
	const MUSIC_POKEMON_DOME   ; $0A
	const MUSIC_CHALLENGE_HALL ; $0B
	const MUSIC_CLUB_1         ; $0C
	const MUSIC_CLUB_2         ; $0D
	const MUSIC_CLUB_3         ; $0E
	const MUSIC_RONALD         ; $0F
	const MUSIC_IMAKUNI        ; $10
	const MUSIC_HALL_OF_HONOR  ; $11
	const MUSIC_CREDITS        ; $12
	const MUSIC_UNUSED_13      ; $13
	const MUSIC_UNUSED_14      ; $14
	const MUSIC_MATCH_START_1  ; $15
	const MUSIC_MATCH_START_2  ; $16
	const MUSIC_MATCH_START_3  ; $17
	const MUSIC_MATCH_VICTORY  ; $18
	const MUSIC_MATCH_LOSS     ; $19
	const MUSIC_DARK_DIDDLY    ; $1A
	const MUSIC_UNUSED_1B      ; $1B
	const MUSIC_BOOSTER_PACK   ; $1C
	const MUSIC_MEDAL          ; $1D
	const MUSIC_UNUSED_1E      ; $1E
