start_script EQUS "rst $20"

OWScript_EndScriptLoop_0              EQU $00
OWScript_CloseTextBox_index           EQU $01
OWScript_PrintTextString_index        EQU $02
Func_ccdc_index                       EQU $03
OWScript_AskQuestionJump_index        EQU $04
OWScript_StartBattle_index            EQU $05
Func_cd83_index                       EQU $06
Func_cda8_index                       EQU $07
OWScript_PrintTextCloseBox_index      EQU $08
Func_cdcb_index                       EQU $09
Func_ce26_index                       EQU $0a
Func_ce84_index                       EQU $0b
OWScript_GiveBoosterPacks_index       EQU $0c
Func_cf0c_index                       EQU $0d
Func_cf12_index                       EQU $0e
Func_cf3f_index                       EQU $0f
Func_cf4c_index                       EQU $10
Func_cf53_index                       EQU $11
Func_cf7b_index                       EQU $12
Func_cf2d_index                       EQU $13
Func_cf96_index                       EQU $14
Func_cfc6_index                       EQU $15
Func_cfd4_index                       EQU $16
Func_d00b_index                       EQU $17
Func_d025_index                       EQU $18
Func_d032_index                       EQU $19
Func_d03f_index                       EQU $1a
OWScript_ScriptJump_index             EQU $1b
Func_d04f_index                       EQU $1c
Func_d055_index                       EQU $1d
OWScript_MovePlayer_index             EQU $1e
Func_cee2_index                       EQU $1f
Func_d080_index                       EQU $20
Func_d088_index                       EQU $21
Func_d095_index                       EQU $22
Func_d0be_index                       EQU $23
Func_d0ce_index                       EQU $24
Func_d0d9_index                       EQU $25
Func_d0f2_index                       EQU $26
Func_ce4a_index                       EQU $27
Func_ceba_index                       EQU $28
Func_d103_index                       EQU $29
Func_d125_index                       EQU $2a
Func_d135_index                       EQU $2b
Func_d16b_index                       EQU $2c
Func_cd4f_index                       EQU $2d
Func_cd94_index                       EQU $2e
Func_ce52_index                       EQU $2f
Func_cdd8_index                       EQU $30
Func_cdf5_index                       EQU $31
Func_d195_index                       EQU $32
Func_d1ad_index                       EQU $33
Func_d1b3_index                       EQU $34
OWScript_EndScriptCloseText_index     EQU $35
Func_d244_index                       EQU $36
Func_d24c_index                       EQU $37
DeckMachine_d336_index                EQU $38
Func_d271_index                       EQU $39
Func_d36d_index                       EQU $3a
Func_ce6f_index                       EQU $3b
Func_d209_index                       EQU $3c
Func_d38f_index                       EQU $3d
Func_d396_index                       EQU $3e
Func_cd76_index                       EQU $3f
Func_d39d_index                       EQU $40
Func_d3b9_index                       EQU $41
Func_d3c9_index                       EQU $42
Func_d3d1_index                       EQU $43
Func_d3d4_index                       EQU $44
Func_d3e0_index                       EQU $45
Func_d3fe_index                       EQU $46
Func_d408_index                       EQU $47
Func_d40f_index                       EQU $48
Func_d416_index                       EQU $49
Func_d423_index                       EQU $4a
Func_d429_index                       EQU $4b
Func_d41d_index                       EQU $4c
Func_d42f_index                       EQU $4d
Func_d435_index                       EQU $4e
Func_cce4_index                       EQU $4f
Func_d2f6_index                       EQU $50
Func_d317_index                       EQU $51
Func_d43d_index                       EQU $52
OWScript_EndScriptLoop_53             EQU $53
OWScript_EndScriptLoop_54             EQU $54
OWScript_EndScriptLoop_55             EQU $55
OWScript_EndScriptLoop_56             EQU $56
OWScript_EndScriptLoop_57             EQU $57
OWScript_CustomModifyEventFlags_index EQU $58
Func_d460_index                       EQU $59
OWScript_JumpIfFlagSet_index          EQU $5a
Func_d484_index                       EQU $5b
Func_d49e_index                       EQU $5c
Func_d4a6_index                       EQU $5d
Func_d4ae_index                       EQU $5e
OWScript_SetEventFlags_index          EQU $5f
Func_d4c3_index                       EQU $60
Func_d4ca_index                       EQU $61
OWScript_JumpIfFlagNotSet_index       EQU $62
Func_d452_index                       EQU $63
OWScript_EndScriptLoop_64             EQU $64
OWScript_EndScriptLoop_65             EQU $65
OWScript_EndScriptLoop_66             EQU $66
OWScript_EndScriptLoop_67             EQU $67

; Script Flags
FLAG_BEAT_SARA      EQU $15
FLAG_BEAT_AMANDA    EQU $16

