	const_def
	const PALETTE_DEFAULT_CGB               ; $00
	const PALETTE_OVERWORLD_MAP             ; $01
	const PALETTE_MASON_LABORATORY          ; $02
	const PALETTE_ISHIHARAS_HOUSE           ; $03
	const PALETTE_FIGHTING_CLUB_ENTRANCE    ; $04
	const PALETTE_ROCK_CLUB_ENTRANCE        ; $05
	const PALETTE_WATER_CLUB_ENTRANCE       ; $06
	const PALETTE_LIGHTNING_CLUB_ENTRANCE   ; $07
	const PALETTE_GRASS_CLUB_ENTRANCE       ; $08
	const PALETTE_PSYCHIC_CLUB_ENTRANCE     ; $09
	const PALETTE_SCIENCE_CLUB_ENTRANCE     ; $0a
	const PALETTE_FIRE_CLUB_ENTRANCE        ; $0b
	const PALETTE_CLUB_LOBBY                ; $0c
	const PALETTE_FIGHTING_CLUB             ; $0d
	const PALETTE_ROCK_CLUB                 ; $0e
	const PALETTE_WATER_CLUB                ; $0f
	const PALETTE_LIGHTNING_CLUB            ; $10
	const PALETTE_GRASS_CLUB                ; $11
	const PALETTE_PSYCHIC_CLUB              ; $12
	const PALETTE_SCIENCE_CLUB              ; $13
	const PALETTE_FIRE_CLUB                 ; $14
	const PALETTE_CHALLENGE_HALL            ; $15
	const PALETTE_POKEMON_DOME_ENTRANCE     ; $16
	const PALETTE_POKEMON_DOME              ; $17
	const PALETTE_HALL_OF_HONOR             ; $18
	const PALETTE_TITLE_SCREEN              ; $19
	const PALETTE_COPYRIGHT                 ; $1a
	const PALETTE_NINTENDO                  ; $1b
	const PALETTE_COMPANIES                 ; $1c
	const PALETTE_OVERWORLD_OAM             ; $1d
	const PALETTE_TITLE_SCREEN_ORBS         ; $1e
	const PALETTE_GLOW                      ; $1f
	const PALETTE_PARALYSIS                 ; $20
	const PALETTE_SLEEP                     ; $21
	const PALETTE_STAR                      ; $22
	const PALETTE_POISON                    ; $23
	const PALETTE_HIT                       ; $24
	const PALETTE_DAMAGE                    ; $25
	const PALETTE_THUNDER                   ; $26
	const PALETTE_LIGHTNING                 ; $27
	const PALETTE_SPARK                     ; $28
	const PALETTE_BIG_LIGHTNING             ; $29
	const PALETTE_FLAME                     ; $2a
	const PALETTE_FIRE_SPIN                 ; $2b
	const PALETTE_FIRE_BIRD                 ; $2c
	const PALETTE_WATER_DROP                ; $2d
	const PALETTE_WATER_GUN                 ; $2e
	const PALETTE_WHIRLPOOL                 ; $2f
	const PALETTE_HYDRO_PUMP                ; $30
	const PALETTE_SNOW                      ; $31
	const PALETTE_PSYCHIC                   ; $32
	const PALETTE_LEER                      ; $33
	const PALETTE_BEAM                      ; $34
	const PALETTE_HYPER_BEAM                ; $35
	const PALETTE_ROCK_THROW                ; $36
	const PALETTE_PUNCH                     ; $37
	const PALETTE_STRETCH_KICK              ; $38
	const PALETTE_SLASH                     ; $39
	const PALETTE_WHIP                      ; $3a
	const PALETTE_SONICBOOM                 ; $3b
	const PALETTE_DRILL                     ; $3c
	const PALETTE_POT                       ; $3d
	const PALETTE_BONE                      ; $3e
	const PALETTE_PLANET                    ; $3f
	const PALETTE_NEEDLES                   ; $40
	const PALETTE_WHITE_GAS                 ; $41
	const PALETTE_POWDER                    ; $42
	const PALETTE_GOO                       ; $43
	const PALETTE_BUBBLE                    ; $44
	const PALETTE_STRING                    ; $45
	const PALETTE_HEART                     ; $46
	const PALETTE_LURE                      ; $47
	const PALETTE_SKULL                     ; $48
	const PALETTE_SMALL_STAR                ; $49
	const PALETTE_NOTE                      ; $4a
	const PALETTE_SOUND                     ; $4b
	const PALETTE_PETAL                     ; $4c
	const PALETTE_PROTECT                   ; $4d
	const PALETTE_BARRIER                   ; $4e
	const PALETTE_SPEED                     ; $4f
	const PALETTE_WHIRLWIND                 ; $50
	const PALETTE_CRY                       ; $51
	const PALETTE_QUESTION_MARK             ; $52
	const PALETTE_EXPLOSION                 ; $53
	const PALETTE_HEAL                      ; $54
	const PALETTE_DRAIN                     ; $55
	const PALETTE_DARK_GAS                  ; $56
	const PALETTE_SMALL_GLOW                ; $57
	const PALETTE_BALL                      ; $58
	const PALETTE_CAT_PAW                   ; $59
	const PALETTE_WAVE                      ; $a5
	const PALETTE_DUEL_CARD                 ; $5b
	const PALETTE_COIN                      ; $5c
	const PALETTE_DUEL_RESULT               ; $5d
	const PALETTE_TEST_BLACK_RED            ; $5e
	const PALETTE_TEST_WHITE_RED            ; $5f
	const PALETTE_TEST_BLACK_GREEN          ; $60
	const PALETTE_TEST_WHITE_GREEN          ; $61
	const PALETTE_TEST_COLOR_WHEEL          ; $62
	const PALETTE_COLOR_TEST                ; $63
	const PALETTE_JAPANESE_TITLE_SCREEN_CGB ; $64
	const PALETTE_COLOSSEUM_BOOSTER_CGB     ; $65
	const PALETTE_EVOLUTION_BOOSTER_CGB     ; $66
	const PALETTE_MYSTERY_BOOSTER_CGB       ; $67
	const PALETTE_LABORATORY_BOOSTER_CGB    ; $68
	const PALETTE_CHARIZARD_INTRO_CGB       ; $69
	const PALETTE_SCYTHER_INTRO_CGB         ; $6a
	const PALETTE_AERODACTYL_INTRO_CGB      ; $6b
	const PALETTE_DEFAULT_DMG               ; $6c
	const PALETTE_JAPANESE_TITLE_SCREEN_DMG ; $6d
	const PALETTE_COLOR_PALETTE             ; $6e
	const PALETTE_GB_LINK_BG                ; $6f
	const PALETTE_GB_PRINTER_BG             ; $70
	const PALETTE_CARD_POP_BG               ; $71
	const PALETTE_GB_LINK_OAM               ; $72
	const PALETTE_GB_PRINTER_OAM            ; $73
	const PALETTE_CARD_POP_OAM              ; $74
	const PALETTE_BOOSTER_OAM               ; $75
	const PALETTE_MEDALS                    ; $76
	const PALETTE_PLAYER_PIC                ; $77
	const PALETTE_LINK_OPP_PIC              ; $78
	const PALETTE_RONALD_PIC                ; $79
	const PALETTE_SAM_PIC                   ; $7a
	const PALETTE_IMAKUNI_PIC               ; $7b
	const PALETTE_NIKKI_PIC                 ; $7c
	const PALETTE_RICK_PIC                  ; $7d
	const PALETTE_KEN_PIC                   ; $7e
	const PALETTE_AMY_PIC                   ; $7f
	const PALETTE_ISAAC_PIC                 ; $80
	const PALETTE_MITCH_PIC                 ; $81
	const PALETTE_GENE_PIC                  ; $82
	const PALETTE_MURRAY_PIC                ; $83
	const PALETTE_COURTNEY_PIC              ; $84
	const PALETTE_STEVE_PIC                 ; $85
	const PALETTE_JACK_PIC                  ; $86
	const PALETTE_ROD_PIC                   ; $87
	const PALETTE_JOSEPH_PIC                ; $88
	const PALETTE_DAVID_PIC                 ; $89
	const PALETTE_ERIK_PIC                  ; $8a
	const PALETTE_JOHN_PIC                  ; $8b
	const PALETTE_ADAM_PIC                  ; $8c
	const PALETTE_JONATHAN_PIC              ; $8d
	const PALETTE_JOSHUA_PIC                ; $8e
	const PALETTE_NICHOLAS_PIC              ; $8f
	const PALETTE_BRANDON_PIC               ; $90
	const PALETTE_MATTHEW_PIC               ; $91
	const PALETTE_RYAN_PIC                  ; $92
	const PALETTE_ANDREW_PIC                ; $93
	const PALETTE_CHRIS_PIC                 ; $94
	const PALETTE_MICHAEL_PIC               ; $95
	const PALETTE_DANIEL_PIC                ; $96
	const PALETTE_ROBERT_PIC                ; $97
	const PALETTE_BRITTANY_PIC              ; $98
	const PALETTE_KRISTIN_PIC               ; $99
	const PALETTE_HEATHER_PIC               ; $9a
	const PALETTE_SARA_PIC                  ; $9b
	const PALETTE_AMANDA_PIC                ; $9c
	const PALETTE_JENNIFER_PIC              ; $9d
	const PALETTE_JESSICA_PIC               ; $9e
	const PALETTE_STEPHANIE_PIC             ; $9f
	const PALETTE_AARON_PIC                 ; $a0

DEF NUM_PALETTES EQU const_value
