	const_def
	const SCENE_TITLE_SCREEN                  ; $00
	const SCENE_COLOSSEUM_BOOSTER             ; $01
	const SCENE_EVOLUTION_BOOSTER             ; $02
	const SCENE_MYSTERY_BOOSTER               ; $03
	const SCENE_LABORATORY_BOOSTER            ; $04
	const SCENE_CHARIZARD_INTRO               ; $05
	const SCENE_SCYTHER_INTRO                 ; $06
	const SCENE_AERODACTYL_INTRO              ; $07
	const SCENE_GRADIENT_BLACK_AND_RED        ; $08
	const SCENE_GRADIENT_WHITE_AND_RED        ; $09
	const SCENE_GRADIENT_BLACK_AND_GREEN      ; $0a
	const SCENE_GRADIENT_WHITE_AND_GREEN      ; $0b
	const SCENE_COLOR_WHEEL                   ; $0c
	const SCENE_COLOR_TEST                    ; $0d
	const SCENE_GAMEBOY_LINK_CONNECTING       ; $0e
	const SCENE_GAMEBOY_LINK_TRANSMITTING     ; $0f
	const SCENE_GAMEBOY_LINK_NOT_CONNECTED    ; $10
	const SCENE_GAMEBOY_PRINTER_TRANSMITTING  ; $11
	const SCENE_GAMEBOY_PRINTER_NOT_CONNECTED ; $12
	const SCENE_CARD_POP                      ; $13
	const SCENE_CARD_POP_ERROR                ; $14
	const SCENE_JAPANESE_TITLE_SCREEN         ; $15
	const SCENE_NINTENDO                      ; $16
	const SCENE_COMPANIES                     ; $17
	const SCENE_JAPANESE_TITLE_SCREEN_2       ; $18
	const SCENE_COPYRIGHT                     ; $19
	const SCENE_JAPANESE_TITLE_SCREEN_2_COPY  ; $1a
	const SCENE_COLOR_PALETTE                 ; $1b

DEF NUM_SCENES EQU const_value
