	const_def
	const EVENT_TEMP_TRADED_WITH_ISHIHARA              ; $00
	const EVENT_TEMP_GIFTED_TO_MAN1                    ; $01
	const EVENT_TEMP_TALKED_TO_IMAKUNI                 ; $02
	const EVENT_TEMP_DUELED_IMAKUNI                    ; $03
	const EVENT_TEMP_TRADED_WITH_LASS2                 ; $04
	const EVENT_TEMP_05                                ; $05
	const EVENT_TEMP_06                                ; $06
	const EVENT_TEMP_07                                ; $07
	const EVENT_BEAT_NIKKI                             ; $08
	const EVENT_BEAT_RICK                              ; $09
	const EVENT_BEAT_KEN                               ; $0a
	const EVENT_BEAT_AMY                               ; $0b
	const EVENT_BEAT_ISAAC                             ; $0c
	const EVENT_BEAT_MURRAY                            ; $0d
	const EVENT_BEAT_GENE                              ; $0e
	const EVENT_BEAT_MITCH                             ; $0f
	const EVENT_MEDAL_FLAGS                            ; $10
	const EVENT_PUPIL_MICHAEL_STATE                    ; $11
	const EVENT_GAL1_TRADE_STATE                       ; $12
	const EVENT_IMAKUNI_STATE                          ; $13
	const EVENT_LASS1_MENTIONED_IMAKUNI                ; $14
	const EVENT_BEAT_SARA                              ; $15
	const EVENT_BEAT_AMANDA                            ; $16
	const EVENT_PUPIL_CHRIS_STATE                      ; $17
	const EVENT_MATTHEW_STATE                          ; $18
	const EVENT_CHAP2_TRADE_STATE                      ; $19
	const EVENT_DAVID_STATE                            ; $1a
	const EVENT_BEAT_JOSEPH                            ; $1b
	const EVENT_ISHIHARA_MENTIONED                     ; $1c
	const EVENT_ISHIHARA_MET                           ; $1d
	const EVENT_ISHIHARAS_HOUSE_MENTIONED              ; $1e
	const EVENT_ISHIHARA_TRADE_STATE                   ; $1f
	const EVENT_PUPIL_JESSICA_STATE                    ; $20
	const EVENT_LAD2_STATE                             ; $21
	const EVENT_RECEIVED_LEGENDARY_CARDS               ; $22
	const EVENT_KEN_HAD_ENOUGH_CARDS                   ; $23
	const EVENT_KEN_TALKED                             ; $24
	const EVENT_BEAT_JENNIFER                          ; $25
	const EVENT_BEAT_NICHOLAS                          ; $26
	const EVENT_BEAT_BRANDON                           ; $27
	const EVENT_ISAAC_TALKED                           ; $28
	const EVENT_MAN1_TALKED                            ; $29
	const EVENT_MAN1_WAITING_FOR_CARD                  ; $2a
	const EVENT_MAN1_REQUESTED_CARD_ID                 ; $2b
	const EVENT_MAN1_GIFT_SEQUENCE_STATE               ; $2c
	const EVENT_MAN1_GIFTED_CARD_FLAGS                 ; $2d
	const EVENT_MEDAL_COUNT                            ; $2e
	const EVENT_DANIEL_TALKED                          ; $2f
	const EVENT_MURRAY_TALKED                          ; $30
	const EVENT_PAPPY1_STATE                           ; $31
	const EVENT_RONALD_PSYCHIC_CLUB_LOBBY_ENCOUNTER    ; $32
	const EVENT_JOSHUA_STATE                           ; $33
	const EVENT_IMAKUNI_ROOM                           ; $34
	const EVENT_NIKKI_STATE                            ; $35
	const EVENT_IMAKUNI_WIN_COUNT                      ; $36
	const EVENT_LASS2_TRADE_STATE                      ; $37
	const EVENT_ISHIHARA_WANTS_TO_TRADE                ; $38
	const EVENT_ISHIHARA_CONGRATULATED_PLAYER          ; $39
	const EVENT_BEAT_KRISTIN                           ; $3a
	const EVENT_BEAT_HEATHER                           ; $3b
	const EVENT_BEAT_BRITTANY                          ; $3c
	const EVENT_DRMASON_CONGRATULATED_PLAYER           ; $3d
	const EVENT_MASON_LAB_STATE                        ; $3e
	const EVENT_CHALLENGE_CUP_1_STATE                  ; $3f
	const EVENT_CHALLENGE_CUP_2_STATE                  ; $40
	const EVENT_CHALLENGE_CUP_3_STATE                  ; $41
	const EVENT_CHALLENGE_CUP_STARTING                 ; $42
	const EVENT_CHALLENGE_CUP_STAGE_VISITED            ; $43
	const EVENT_CHALLENGE_CUP_NUMBER                   ; $44
	const EVENT_CHALLENGE_CUP_OPPONENT_NUMBER          ; $45
	const EVENT_CHALLENGE_CUP_OPPONENT_CHOSEN          ; $46
	const EVENT_CHALLENGE_CUP_IN_MENU                  ; $47
	const EVENT_CHALLENGE_CUP_1_RESULT                 ; $48
	const EVENT_CHALLENGE_CUP_2_RESULT                 ; $49
	const EVENT_CHALLENGE_CUP_3_RESULT                 ; $4a
	const EVENT_RONALD_FIRST_CLUB_ENTRANCE_ENCOUNTER   ; $4b
	const EVENT_RONALD_FIRST_DUEL_STATE                ; $4c
	const EVENT_RONALD_SECOND_DUEL_STATE               ; $4d
	const EVENT_RONALD_TALKED                          ; $4e
	const EVENT_RONALD_POKEMON_DOME_ENTRANCE_ENCOUNTER ; $4f
	const EVENT_RONALD_CHALLENGE_HALL_LOBBY_CONVO_1    ; $50
	const EVENT_RONALD_CHALLENGE_HALL_LOBBY_CONVO_2    ; $51
	const EVENT_RONALD_CHALLENGE_HALL_LOBBY_CONVO_3    ; $52
	const EVENT_RONALD_CHALLENGE_HALL_LOBBY_CONVO_4    ; $53
	const EVENT_RONALD_CHALLENGE_HALL_LOBBY_CONVO_5    ; $54
	const EVENT_RONALD_CHALLENGE_HALL_LOBBY_CONVO_6    ; $55
	const EVENT_RONALD_CHALLENGE_HALL_LOBBY_CONVO_7    ; $56
	const EVENT_RONALD_CHALLENGE_HALL_LOBBY_CONVO_8    ; $57
	const EVENT_RONALD_CHALLENGE_HALL_LOBBY_STATE      ; $58
	const EVENT_PLAYER_ENTERED_CHALLENGE_CUP           ; $59
	const EVENT_FIGHTING_DECK_MACHINE_ACTIVE           ; $5a
	const EVENT_ROCK_DECK_MACHINE_ACTIVE               ; $5b
	const EVENT_WATER_DECK_MACHINE_ACTIVE              ; $5c
	const EVENT_LIGHTNING_DECK_MACHINE_ACTIVE          ; $5d
	const EVENT_GRASS_DECK_MACHINE_ACTIVE              ; $5e
	const EVENT_PSYCHIC_DECK_MACHINE_ACTIVE            ; $5f
	const EVENT_SCIENCE_DECK_MACHINE_ACTIVE            ; $60
	const EVENT_FIRE_DECK_MACHINE_ACTIVE               ; $61
	const EVENT_ALL_DECK_MACHINE_FLAGS                 ; $62
	const EVENT_HALL_OF_HONOR_DOORS_OPEN               ; $63
	const EVENT_CHALLENGED_GRAND_MASTERS               ; $64
	const EVENT_POKEMON_DOME_STATE                     ; $65
	const EVENT_POKEMON_DOME_IN_MENU                   ; $66
	const EVENT_CHALLENGED_RONALD                      ; $67
	const EVENT_COURTNEY_STATE                         ; $68
	const EVENT_STEVE_STATE                            ; $69
	const EVENT_JACK_STATE                             ; $6a
	const EVENT_ROD_STATE                              ; $6b
	const EVENT_RONALD_POKEMON_DOME_STATE              ; $6c
	const EVENT_RECEIVED_ZAPDOS                        ; $6d
	const EVENT_RECEIVED_MOLTRES                       ; $6e
	const EVENT_RECEIVED_ARTICUNO                      ; $6f
	const EVENT_RECEIVED_DRAGONITE                     ; $70
	const EVENT_LEGENDARY_CARDS_RECEIVED_FLAGS         ; $71
	const EVENT_GIFT_CENTER_MENU_CHOICE                ; $72
	const EVENT_AARON_BOOSTER_REWARD                   ; $73
	const EVENT_CONSOLE                                ; $74
	const EVENT_SAM_MENU_CHOICE                        ; $75
	const EVENT_AARON_DECK_MENU_CHOICE                 ; $76
EVENT_FLAG_AMOUNT EQU const_value

EVENT_FLAG_BYTES EQU $40

; EVENT_PUPIL_MICHAEL_STATE
; EVENT_PUPIL_CHRIS_STATE
; EVENT_PUPIL_JESSICA_STATE
PUPIL_INACTIVE  EQU 0
PUPIL_ACTIVE    EQU 1
PUPIL_TALKED    EQU 2
PUPIL_DEFEATED  EQU 8
PUPIL_REVISITED EQU 9

; EVENT_GAL1_TRADE_STATE
GAL1_TRADE_NOT_OFFERED EQU 0
GAL1_TRADE_OFFERED     EQU 1
GAL1_TRADE_COMPLETED   EQU 2

; EVENT_IMAKUNI_STATE
IMAKUNI_NOT_MENTIONED EQU 0
IMAKUNI_MENTIONED     EQU 1
IMAKUNI_TALKED        EQU 2

; EVENT_MATTHEW_STATE
MATTHEW_TALKED   EQU 1
MATTHEW_DEFEATED EQU 2

; EVENT_CHAP2_TRADE_STATE
CHAP2_TRADE_NOT_OFFERED EQU 0
CHAP2_TRADE_OFFERED     EQU 1
CHAP2_TRADE_COMPLETED   EQU 2

; EVENT_DAVID_STATE
DAVID_TALKED   EQU 1
DAVID_DEFEATED EQU 2

; EVENT_ISHIHARA_TRADE_STATE
ISHIHARA_INTRODUCTION    EQU 0
ISHIHARA_TRADE_1_RUMORED EQU 1
ISHIHARA_TRADE_1_OFFERED EQU 2
ISHIHARA_TRADE_2_RUMORED EQU 3
ISHIHARA_TRADE_2_OFFERED EQU 4
ISHIHARA_TRADE_3_RUMORED EQU 5
ISHIHARA_TRADE_3_OFFERED EQU 6
ISHIHARA_TRADES_COMPLETE EQU 7
ISHIHARA_LEFT            EQU 8

; EVENT_LAD2_STATE
LAD2_SLOWPOKE_AVAILABLE EQU 1
LAD2_SLOWPOKE_GONE      EQU 2

; EVENT_MAN1_GIFT_SEQUENCE_STATE
MAN1_GIFT_SEQUENCE_COMPLETE EQU 6

; EVENT_PAPPY1_STATE
PAPPY1_TALKED             EQU 1
PAPPY1_CHALLENGE_ACCEPTED EQU 2
PAPPY1_CHALLENGE_COMPLETE EQU 3

; EVENT_JOSHUA_STATE
JOSHUA_TALKED   EQU 1
JOSHUA_DEFEATED EQU 2

; EVENT_IMAKUNI_ROOM
IMAKUNI_FIGHTING_CLUB  EQU 0
IMAKUNI_SCIENCE_CLUB   EQU 1
IMAKUNI_LIGHTNING_CLUB EQU 2
IMAKUNI_WATER_CLUB     EQU 3

; EVENT_NIKKI_STATE
NIKKI_IN_ISHIHARAS_HOUSE EQU 1
NIKKI_IN_GRASS_CLUB      EQU 2

; EVENT_LASS2_TRADE_STATE
LASS2_TRADE_1_AVAILABLE EQU 0
LASS2_TRADE_1_OFFERED   EQU 1
LASS2_TRADE_2_AVAILABLE EQU 2
LASS2_TRADE_2_OFFERED   EQU 3
LASS2_TRADE_3_AVAILABLE EQU 4
LASS2_TRADE_3_OFFERED   EQU 5
LASS2_TRADES_COMPLETE   EQU 6

; EVENT_MASON_LAB_STATE
MASON_LAB_IN_PRACTICE_DUEL      EQU 1
MASON_LAB_RECEIVED_STARTER_DECK EQU 3

; EVENT_CHALLENGE_CUP_1_STATE
; EVENT_CHALLENGE_CUP_2_STATE
; EVENT_CHALLENGE_CUP_3_STATE
; EVENT_CHALLENGE_CUP_1_RESULT
; EVENT_CHALLENGE_CUP_2_RESULT
; EVENT_CHALLENGE_CUP_3_RESULT
CHALLENGE_CUP_NOT_STARTED    EQU 0
CHALLENGE_CUP_READY_TO_START EQU 1
CHALLENGE_CUP_WON            EQU 2
CHALLENGE_CUP_LOST           EQU 3
CHALLENGE_CUP_OVER           EQU 7

; EVENT_RONALD_FIRST_DUEL_STATE
; EVENT_RONALD_SECOND_DUEL_STATE
RONALD_DUEL_WON  EQU 1
RONALD_DUEL_LOST EQU 2

; EVENT_POKEMON_DOME_STATE
POKEMON_DOME_CHALLENGED EQU 1
POKEMON_DOME_DEFEATED   EQU 2

; EVENT_COURTNEY_STATE
COURTNEY_CHALLENGED EQU 1
COURTNEY_DEFEATED   EQU 2

; EVENT_STEVE_STATE
STEVE_CHALLENGED EQU 1
STEVE_DEFEATED   EQU 2

; EVENT_JACK_STATE
JACK_CHALLENGED EQU 1
JACK_DEFEATED   EQU 2

; EVENT_ROD_STATE
ROD_CHALLENGED EQU 1
ROD_DEFEATED   EQU 2

; EVENT_RONALD_POKEMON_DOME_STATE
RONALD_CHALLENGED EQU 1
RONALD_DEFEATED   EQU 2

; EVENT_GIFT_CENTER_MENU_CHOICE
GIFT_CENTER_MENU_SEND_CARD    EQU 0
GIFT_CENTER_MENU_RECEIVE_CARD EQU 1
GIFT_CENTER_MENU_SEND_DECK    EQU 2
GIFT_CENTER_MENU_RECEIVE_DECK EQU 3
GIFT_CENTER_MENU_EXIT         EQU 4

; EVENT_SAM_MENU_CHOICE
; normal menu
SAM_MENU_NORMAL_DUEL   EQU 0
SAM_MENU_PRACTICE_DUEL EQU 1
SAM_MENU_RULES         EQU 2
SAM_MENU_NOTHING       EQU 3
; rules menu
SAM_MENU_ENERGY           EQU 0
SAM_MENU_ATTACKING        EQU 1
SAM_MENU_RETREATING       EQU 2
SAM_MENU_EVOLVING         EQU 3
SAM_MENU_POKEMON_POWER    EQU 4
SAM_MENU_ENDING_YOUR_TURN EQU 5
SAM_MENU_WIN_OR_LOSS      EQU 6
SAM_MENU_NOTHING_TO_ASK   EQU 7

; EVENT_AARON_DECK_MENU_CHOICE
AARON_DECK_MENU_CANCEL EQU 3

NORTH    EQU $00
EAST     EQU $01
SOUTH    EQU $02
WEST     EQU $03
NO_MOVE  EQU %10000000 ; For rotations without movement

VARIABLE_CARD	EQU 0 ; use the card located in wd697 instead of using the script's argument
