	const_def
	const EVENT_FLAG_00    
	const EVENT_FLAG_01    
	const EVENT_FLAG_02    
	const EVENT_FLAG_03    
	const EVENT_FLAG_04    
	const EVENT_FLAG_05    
	const EVENT_FLAG_06    
	const EVENT_FLAG_07    
	const EVENT_FLAG_08    
	const EVENT_FLAG_09    
	const EVENT_FLAG_0A    
	const EVENT_BEAT_AMY   
	const EVENT_FLAG_0C    
	const EVENT_FLAG_0D    
	const EVENT_FLAG_0E    
	const EVENT_FLAG_0F    
	const EVENT_FLAG_10    
	const EVENT_FLAG_11    
	const EVENT_FLAG_12    
	const EVENT_FLAG_13    
	const EVENT_FLAG_14    
	const EVENT_BEAT_SARA  
	const EVENT_BEAT_AMANDA
	const EVENT_FLAG_17    
	const EVENT_FLAG_18    
	const EVENT_FLAG_19    
	const EVENT_FLAG_1A    
	const EVENT_FLAG_1B    
	const EVENT_FLAG_1C    
	const EVENT_FLAG_1D    
	const EVENT_FLAG_1E    
	const EVENT_FLAG_1F    
	const EVENT_FLAG_20    
	const EVENT_FLAG_21    
	const EVENT_FLAG_22    
	const EVENT_FLAG_23    
	const EVENT_FLAG_24    
	const EVENT_FLAG_25    
	const EVENT_FLAG_26    
	const EVENT_FLAG_27    
	const EVENT_FLAG_28    
	const EVENT_FLAG_29    
	const EVENT_FLAG_2A    
	const EVENT_FLAG_2B    
	const EVENT_FLAG_2C    
	const EVENT_FLAG_2D    
	const EVENT_FLAG_2E    
	const EVENT_FLAG_2F    
	const EVENT_FLAG_30    
	const EVENT_FLAG_31    
	const EVENT_FLAG_32    
	const EVENT_JOSHUA_STATE
	const EVENT_FLAG_34    
	const EVENT_FLAG_35    
	const EVENT_FLAG_36    
	const EVENT_FLAG_37    
	const EVENT_FLAG_38    
	const EVENT_FLAG_39    
	const EVENT_FLAG_3A    
	const EVENT_FLAG_3B    
	const FLAG_BEAT_BRITTANY
	const EVENT_FLAG_3D    
	const EVENT_FLAG_3E    
	const EVENT_FLAG_3F    
	const EVENT_FLAG_40    
	const EVENT_FLAG_41    
	const EVENT_FLAG_42    
	const EVENT_FLAG_43    
	const EVENT_FLAG_44    
	const EVENT_FLAG_45    
	const EVENT_FLAG_46    
	const EVENT_FLAG_47    
	const EVENT_FLAG_48    
	const EVENT_FLAG_49    
	const EVENT_FLAG_4A    
	const EVENT_FLAG_4B    
	const EVENT_FLAG_4C    
	const EVENT_FLAG_4D    
	const EVENT_FLAG_4E    
	const EVENT_FLAG_4F    
	const EVENT_FLAG_50    
	const EVENT_FLAG_51    
	const EVENT_FLAG_52    
	const EVENT_FLAG_53    
	const EVENT_FLAG_54    
	const EVENT_FLAG_55    
	const EVENT_FLAG_56    
	const EVENT_FLAG_57    
	const EVENT_FLAG_58    
	const EVENT_FLAG_59    
	const EVENT_FLAG_5A    
	const EVENT_FLAG_5B    
	const EVENT_FLAG_5C    
	const EVENT_FLAG_5D    
	const EVENT_FLAG_5E    
	const EVENT_FLAG_5F    
	const EVENT_FLAG_60    
	const EVENT_FLAG_61    
	const EVENT_FLAG_62    
	const EVENT_FLAG_63    
	const EVENT_FLAG_64    
	const EVENT_FLAG_65    
	const EVENT_FLAG_66    
	const EVENT_FLAG_67    
	const EVENT_FLAG_68    
	const EVENT_FLAG_69    
	const EVENT_FLAG_6A    
	const EVENT_FLAG_6B    
	const EVENT_FLAG_6C    
	const EVENT_FLAG_6D    
	const EVENT_FLAG_6E    
	const EVENT_FLAG_6F    
	const EVENT_FLAG_70    
	const EVENT_FLAG_71    
	const EVENT_FLAG_72    
	const EVENT_FLAG_73    
	const EVENT_FLAG_74    
	const EVENT_FLAG_75    
	const EVENT_FLAG_76    
EVENT_FLAG_AMOUNT EQU const_value

NO_JUMP EQU $0000

NORTH    EQU $00
EAST     EQU $01
SOUTH    EQU $02
WEST     EQU $03
