	const_def
	const SFX_STOP                 ; $00
	const SFX_CURSOR               ; $01
	const SFX_CONFIRM              ; $02
	const SFX_CANCEL               ; $03
	const SFX_DENIED               ; $04
	const SFX_UNUSED_05            ; $05
	const SFX_UNUSED_06            ; $06
	const SFX_CARD_SHUFFLE         ; $07
	const SFX_PLACE_PRIZE          ; $08
	const SFX_UNUSED_09            ; $09
	const SFX_UNUSED_0A            ; $0a
	const SFX_COIN_TOSS            ; $0b
	const SFX_WARP                 ; $0c
	const SFX_UNUSED_0D            ; $0d
	const SFX_UNUSED_0E            ; $0e
	const SFX_POKEMON_DOME_DOORS   ; $0f
	const SFX_LEGENDARY_CARDS      ; $10
	const SFX_GLOW                 ; $11
	const SFX_PARALYSIS            ; $12
	const SFX_SLEEP                ; $13
	const SFX_CONFUSION            ; $14
	const SFX_POISON               ; $15
	const SFX_SINGLE_HIT           ; $16
	const SFX_BIG_HIT              ; $17
	const SFX_THUNDER_SHOCK        ; $18
	const SFX_LIGHTNING            ; $19
	const SFX_BORDER_SPARK         ; $1a
	const SFX_BIG_LIGHTNING        ; $1b
	const SFX_SMALL_FLAME          ; $1c
	const SFX_BIG_FLAME            ; $1d
	const SFX_FIRE_SPIN            ; $1e
	const SFX_DIVE_BOMB            ; $1f
	const SFX_WATER_JETS           ; $20
	const SFX_WATER_GUN            ; $21
	const SFX_WHIRLPOOL            ; $22
	const SFX_HYDRO_PUMP           ; $23
	const SFX_BLIZZARD             ; $24
	const SFX_PSYCHIC              ; $25
	const SFX_LEER                 ; $26
	const SFX_BEAM                 ; $27
	const SFX_HYPER_BEAM           ; $28
	const SFX_ROCK_THROW           ; $29
	const SFX_STONE_BARRAGE        ; $2a
	const SFX_PUNCH                ; $2b
	const SFX_STRETCH_KICK         ; $2c
	const SFX_SLASH                ; $2d
	const SFX_SONICBOOM            ; $2e
	const SFX_FURY_SWIPES          ; $2f
	const SFX_DRILL                ; $30
	const SFX_POT_SMASH            ; $31
	const SFX_BONEMERANG           ; $32
	const SFX_SEISMIC_TOSS         ; $33
	const SFX_NEEDLES              ; $34
	const SFX_WHITE_GAS            ; $35
	const SFX_POWDER               ; $36
	const SFX_GOO                  ; $37
	const SFX_BUBBLES              ; $38
	const SFX_STRING_SHOT          ; $39
	const SFX_BOYFRIENDS           ; $3a
	const SFX_LURE                 ; $3b
	const SFX_TOXIC                ; $3c
	const SFX_CONFUSE_RAY          ; $3d
	const SFX_SING                 ; $3e
	const SFX_SUPERSONIC           ; $3f
	const SFX_PETAL_DANCE          ; $40
	const SFX_PROTECT              ; $41
	const SFX_BARRIER              ; $42
	const SFX_SPEED                ; $43
	const SFX_WHIRLWIND            ; $44
	const SFX_CRY                  ; $45
	const SFX_QUESTION_MARK        ; $46
	const SFX_SELFDESTRUCT         ; $47
	const SFX_BIG_SELFDESTRUCT     ; $48
	const SFX_HEAL                 ; $49
	const SFX_DRAIN                ; $4a
	const SFX_DARK_GAS             ; $4b
	const SFX_HEALING_WIND         ; $4c
	const SFX_BENCH_WHIRLWIND      ; $4d
	const SFX_EXPAND               ; $4e
	const SFX_CAT_PUNCH            ; $4f
	const SFX_THUNDER_WAVE         ; $50
	const SFX_FIREGIVER            ; $51
	const SFX_THUNDERPUNCH         ; $52
	const SFX_FIRE_PUNCH           ; $53
	const SFX_COIN_TOSS_HEADS      ; $54
	const SFX_COIN_TOSS_TAILS      ; $55
	const SFX_SAVE_GAME            ; $56
	const SFX_PLAYER_WALK_MAP      ; $57
	const SFX_INTRO_ORB            ; $58
	const SFX_INTRO_ORB_SWOOP      ; $59
	const SFX_INTRO_ORB_TITLE      ; $5a
	const SFX_INTRO_ORB_SCATTER    ; $5b
	const SFX_FIREGIVER_START      ; $5c
	const SFX_RECEIVE_CARD_POP     ; $5d
	const SFX_POKEMON_EVOLUTION    ; $5e
	const SFX_UNUSED_5F            ; $5f

DEF NUM_SFX EQU const_value
