; wSpriteAnimBuffer
SPRITE_ANIM_BUFFER_CAPACITY EQU 16 ; sprites

; sprite_anim_struct constants
	const_def
	const SPRITE_ANIM_ENABLED
	const SPRITE_ANIM_ATTRIBUTES
	const SPRITE_ANIM_COORD_X
	const SPRITE_ANIM_COORD_Y
	const SPRITE_ANIM_TILE_ID
	const SPRITE_ANIM_ID
	const SPRITE_ANIM_BANK
	const SPRITE_ANIM_POINTER
const_value = const_value+1 ; pointer
	const SPRITE_ANIM_FRAME_OFFSET_POINTER
const_value = const_value+1 ; pointer
	const SPRITE_ANIM_FRAME_BANK
	const SPRITE_ANIM_FRAME_DATA_POINTER
const_value = const_value+1 ; pointer
	const SPRITE_ANIM_COUNTER
	const SPRITE_ANIM_FLAGS
SPRITE_ANIM_LENGTH EQU const_value

; SPRITE_ANIM_FLAGS values
	const_def
	const SPRITE_ANIM_FLAG_X_SUBTRACT
	const SPRITE_ANIM_FLAG_Y_SUBTRACT
	const SPRITE_ANIM_FLAG_SPEED
	const SPRITE_ANIM_FLAG_3
	const SPRITE_ANIM_FLAG_4
	const SPRITE_ANIM_FLAG_5
	const SPRITE_ANIM_FLAG_6
	const SPRITE_ANIM_FLAG_SKIP_DRAW

SPRITE_FRAME_OFFSET_SIZE EQU 4
