; wSpriteAnimBuffer
SPRITE_ANIM_BUFFER_CAPACITY EQU 16 ; sprites

; sprite_anim_struct constants
	const_def
	const SPRITE_ANIM_FIELD_00
	const SPRITE_ANIM_FIELD_01
	const SPRITE_ANIM_COORD_X
	const SPRITE_ANIM_COORD_Y
	const SPRITE_ANIM_TILE_ID
	const SPRITE_ANIM_FIELD_05
	const SPRITE_ANIM_FIELD_06
	const SPRITE_ANIM_FIELD_07
	const SPRITE_ANIM_FIELD_08
	const SPRITE_ANIM_FIELD_09
	const SPRITE_ANIM_FIELD_0A
	const SPRITE_ANIM_FIELD_0B
	const SPRITE_ANIM_FIELD_0C
	const SPRITE_ANIM_FIELD_0D
	const SPRITE_ANIM_MOVEMENT_COUNTER
	const SPRITE_ANIM_FIELD_0F
SPRITE_ANIM_LENGTH EQU const_value
