	const_def
	const TILESET_OVERWORLD_MAP               ; $00
	const TILESET_MASON_LABORATORY            ; $01
	const TILESET_ISHIHARA                    ; $02
	const TILESET_CLUB_ENTRANCE               ; $03
	const TILESET_CLUB_LOBBY                  ; $04
	const TILESET_FIGHTING_CLUB               ; $05
	const TILESET_ROCK_CLUB                   ; $06
	const TILESET_WATER_CLUB                  ; $07
	const TILESET_LIGHTNING_CLUB              ; $08
	const TILESET_GRASS_CLUB                  ; $09
	const TILESET_PSYCHIC_CLUB                ; $0a
	const TILESET_SCIENCE_CLUB                ; $0b
	const TILESET_FIRE_CLUB                   ; $0c
	const TILESET_CHALLENGE_HALL              ; $0d
	const TILESET_POKEMON_DOME_ENTRANCE       ; $0e
	const TILESET_POKEMON_DOME                ; $0f
	const TILESET_HALL_OF_HONOR               ; $10
	const TILESET_CARD_POP                    ; $11
	const TILESET_MEDAL                       ; $12
	const TILESET_GAMEBOY_LINK                ; $13
	const TILESET_GAMEBOY_PRINTER             ; $14
	const TILESET_COLOSSEUM_1                 ; $15
	const TILESET_COLOSSEUM_2                 ; $16
	const TILESET_EVOLUTION_1                 ; $17
	const TILESET_EVOLUTION_2                 ; $18
	const TILESET_MYSTERY_1                   ; $19
	const TILESET_MYSTERY_2                   ; $1a
	const TILESET_LABORATORY_1                ; $1b
	const TILESET_LABORATORY_2                ; $1c
	const TILESET_CHARIZARD_INTRO_1           ; $1d
	const TILESET_CHARIZARD_INTRO_2           ; $1e
	const TILESET_SCYTHER_INTRO_1             ; $1f
	const TILESET_SCYTHER_INTRO_2             ; $20
	const TILESET_AERODACTYL_INTRO_1          ; $21
	const TILESET_AERODACTYL_INTRO_2          ; $22
	const TILESET_JAPANESE_TITLE_SCREEN       ; $23
	const TILESET_JAPANESE_TITLE_SCREEN_CGB   ; $24
	const TILESET_SOLID_TILES_1               ; $25
	const TILESET_JAPANESE_TITLE_SCREEN_2     ; $26
	const TILESET_JAPANESE_TITLE_SCREEN_2_CGB ; $27
	const TILESET_SOLID_TILES_2               ; $28
	const TILESET_PLAYER                      ; $29
	const TILESET_RONALD                      ; $2a
	const TILESET_TITLE_SCREEN                ; $2b
	const TILESET_TITLE_SCREEN_CGB            ; $2c
	const TILESET_COPYRIGHT                   ; $2d
	const TILESET_NINTENDO                    ; $2e
	const TILESET_COMPANIES                   ; $2f
	const TILESET_SAM                         ; $30
	const TILESET_IMAKUNI                     ; $31
	const TILESET_NIKKI                       ; $32
	const TILESET_RICK                        ; $33
	const TILESET_KEN                         ; $34
	const TILESET_AMY                         ; $35
	const TILESET_ISAAC                       ; $36
	const TILESET_MITCH                       ; $37
	const TILESET_GENE                        ; $38
	const TILESET_MURRAY                      ; $39
	const TILESET_COURTNEY                    ; $3a
	const TILESET_STEVE                       ; $3b
	const TILESET_JACK                        ; $3c
	const TILESET_ROD                         ; $3d
	const TILESET_JOSEPH                      ; $3e
	const TILESET_DAVID                       ; $3f
	const TILESET_ERIK                        ; $40
	const TILESET_JOHN                        ; $41
	const TILESET_ADAM                        ; $42
	const TILESET_JONATHAN                    ; $43
	const TILESET_JOSHUA                      ; $44
	const TILESET_NICHOLAS                    ; $45
	const TILESET_BRANDON                     ; $46
	const TILESET_MATTHEW                     ; $47
	const TILESET_RYAN                        ; $48
	const TILESET_ANDREW                      ; $49
	const TILESET_CHRIS                       ; $4a
	const TILESET_MICHAEL                     ; $4b
	const TILESET_DANIEL                      ; $4c
	const TILESET_ROBERT                      ; $4d
	const TILESET_BRITTANY                    ; $4e
	const TILESET_KRISTIN                     ; $4f
	const TILESET_HEATHER                     ; $50
	const TILESET_SARA                        ; $51
	const TILESET_AMANDA                      ; $52
	const TILESET_JENNIFER                    ; $53
	const TILESET_JESSICA                     ; $54
	const TILESET_STEPHANIE                   ; $55
	const TILESET_AARON                       ; $56

DEF NUM_TILESETS EQU const_value
