	const_def
	const TILEMAP_OVERWORLD_MAP               ; $00
	const TILEMAP_OVERWORLD_MAP_CGB           ; $01
	const TILEMAP_MASON_LABORATORY            ; $02
	const TILEMAP_MASON_LABORATORY_CGB        ; $03
	const TILEMAP_UNUSED_1                    ; $04
	const TILEMAP_UNUSED_2                    ; $05
	const TILEMAP_DECK_MACHINE_ROOM           ; $06
	const TILEMAP_DECK_MACHINE_ROOM_CGB       ; $07
	const TILEMAP_UNUSED_3                    ; $08
	const TILEMAP_UNUSED_4                    ; $09
	const TILEMAP_ISHIHARA                    ; $0a
	const TILEMAP_ISHIHARA_CGB                ; $0b
	const TILEMAP_FIGHTING_CLUB_ENTRANCE      ; $0c
	const TILEMAP_FIGHTING_CLUB_ENTRANCE_CGB  ; $0d
	const TILEMAP_ROCK_CLUB_ENTRANCE          ; $0e
	const TILEMAP_ROCK_CLUB_ENTRANCE_CGB      ; $0f
	const TILEMAP_WATER_CLUB_ENTRANCE         ; $10
	const TILEMAP_WATER_CLUB_ENTRANCE_CGB     ; $11
	const TILEMAP_LIGHTNING_CLUB_ENTRANCE     ; $12
	const TILEMAP_LIGHTNING_CLUB_ENTRANCE_CGB ; $13
	const TILEMAP_GRASS_CLUB_ENTRANCE         ; $14
	const TILEMAP_GRASS_CLUB_ENTRANCE_CGB     ; $15
	const TILEMAP_PSYCHIC_CLUB_ENTRANCE       ; $16
	const TILEMAP_PSYCHIC_CLUB_ENTRANCE_CGB   ; $17
	const TILEMAP_SCIENCE_CLUB_ENTRANCE       ; $18
	const TILEMAP_SCIENCE_CLUB_ENTRANCE_CGB   ; $19
	const TILEMAP_FIRE_CLUB_ENTRANCE          ; $1a
	const TILEMAP_FIRE_CLUB_ENTRANCE_CGB      ; $1b
	const TILEMAP_CHALLENGE_HALL_ENTRANCE     ; $1c
	const TILEMAP_CHALLENGE_HALL_ENTRANCE_CGB ; $1d
	const TILEMAP_CLUB_LOBBY                  ; $1e
	const TILEMAP_CLUB_LOBBY_CGB              ; $1f
	const TILEMAP_FIGHTING_CLUB               ; $20
	const TILEMAP_FIGHTING_CLUB_CGB           ; $21
	const TILEMAP_ROCK_CLUB                   ; $22
	const TILEMAP_ROCK_CLUB_CGB               ; $23
	const TILEMAP_WATER_CLUB                  ; $24
	const TILEMAP_WATER_CLUB_CGB              ; $25
	const TILEMAP_LIGHTNING_CLUB              ; $26
	const TILEMAP_LIGHTNING_CLUB_CGB          ; $27
	const TILEMAP_GRASS_CLUB                  ; $28
	const TILEMAP_GRASS_CLUB_CGB              ; $29
	const TILEMAP_PSYCHIC_CLUB                ; $2a
	const TILEMAP_PSYCHIC_CLUB_CGB            ; $2b
	const TILEMAP_SCIENCE_CLUB                ; $2c
	const TILEMAP_SCIENCE_CLUB_CGB            ; $2d
	const TILEMAP_FIRE_CLUB                   ; $2e
	const TILEMAP_FIRE_CLUB_CGB               ; $2f
	const TILEMAP_CHALLENGE_HALL              ; $30
	const TILEMAP_CHALLENGE_HALL_CGB          ; $31
	const TILEMAP_POKEMON_DOME_ENTRANCE       ; $32
	const TILEMAP_POKEMON_DOME_ENTRANCE_CGB   ; $33
	const TILEMAP_UNUSED_5                    ; $34
	const TILEMAP_UNUSED_6                    ; $35
	const TILEMAP_POKEMON_DOME                ; $36
	const TILEMAP_POKEMON_DOME_CGB            ; $37
	const TILEMAP_UNUSED_7                    ; $38
	const TILEMAP_UNUSED_8                    ; $39
	const TILEMAP_HALL_OF_HONOR               ; $3a
	const TILEMAP_HALL_OF_HONOR_CGB           ; $3b
	const TILEMAP_CARD_POP_1                  ; $3c
	const TILEMAP_CARD_POP_1_CGB              ; $3d
	const TILEMAP_GRASS_MEDAL                 ; $3e
	const TILEMAP_SCIENCE_MEDAL               ; $3f
	const TILEMAP_FIRE_MEDAL                  ; $40
	const TILEMAP_WATER_MEDAL                 ; $41
	const TILEMAP_LIGHTNING_MEDAL             ; $42
	const TILEMAP_FIGHTING_MEDAL              ; $43
	const TILEMAP_ROCK_MEDAL                  ; $44
	const TILEMAP_PSYCHIC_MEDAL               ; $45
	const TILEMAP_CARD_POP_2                  ; $46
	const TILEMAP_CARD_POP_2_CGB              ; $47
	const TILEMAP_CARD_POP_2_UNKNOWN_1        ; $48
	const TILEMAP_CARD_POP_2_UNKNOWN_2        ; $49
	const TILEMAP_CARD_POP_3                  ; $4a
	const TILEMAP_CARD_POP_3_CGB              ; $4b
	const TILEMAP_COLOSSEUM                   ; $4c
	const TILEMAP_COLOSSEUM_CGB               ; $4d
	const TILEMAP_EVOLUTION                   ; $4e
	const TILEMAP_EVOLUTION_CGB               ; $4f
	const TILEMAP_MYSTERY                     ; $50
	const TILEMAP_MYSTERY_CGB                 ; $51
	const TILEMAP_LABORATORY                  ; $52
	const TILEMAP_LABORATORY_CGB              ; $53
	const TILEMAP_CHARIZARD_INTRO             ; $54
	const TILEMAP_CHARIZARD_INTRO_CGB         ; $55
	const TILEMAP_SCYTHER_INTRO               ; $56
	const TILEMAP_SCYTHER_INTRO_CGB           ; $57
	const TILEMAP_AERODACTYL_INTRO            ; $58
	const TILEMAP_AERODACTYL_INTRO_CGB        ; $59
	const TILEMAP_TITLE_SCREEN_1              ; $5a
	const TILEMAP_TITLE_SCREEN_2              ; $5b
	const TILEMAP_SOLID_TILES_1               ; $5c
	const TILEMAP_SOLID_TILES_2               ; $5d
	const TILEMAP_SOLID_TILES_3               ; $5e
	const TILEMAP_TITLE_SCREEN_3              ; $5f
	const TILEMAP_TITLE_SCREEN_4              ; $60
	const TILEMAP_SOLID_TILES_4               ; $61
	const TILEMAP_PLAYER                      ; $62
	const TILEMAP_OPPONENT                    ; $63
	const TILEMAP_TITLE_SCREEN_5              ; $64
	const TILEMAP_TITLE_SCREEN_6              ; $65
	const TILEMAP_COPYRIGHT                   ; $66
	const TILEMAP_COPYRIGHT_CGB               ; $67
	const TILEMAP_NINTENDO                    ; $68
	const TILEMAP_COMPANIES                   ; $69
