; These are all the asm constants needed to make the Virtual Console patch.

; [menu 900b]
EXPORT NORTH
EXPORT WEST
; [menu 851 c]
EXPORT SOUTH

; [menu 849]
EXPORT OWMAP_LIGHTNING_CLUB

; [menu 850]
EXPORT DEF NO_INPUT EQU $00
EXPORT PAD_DOWN
EXPORT PAD_UP
EXPORT PAD_LEFT
EXPORT PAD_RIGHT
EXPORT PAD_START
EXPORT PAD_B
EXPORT PAD_A
EXPORT DEF PAD_UP_A EQU PAD_UP | PAD_A

; [menu 851 b]
EXPORT LIGHTNING_CLUB
EXPORT ISHIHARAS_HOUSE
EXPORT FIGHTING_CLUB
EXPORT PSYCHIC_CLUB
EXPORT SCIENCE_CLUB

; [menu 900b]
EXPORT DOUBLE_SPACED
EXPORT NUM_SIGNED

; [NCLBTS 920]
EXPORT rSTAT
