INCLUDE "macros/audio.asm"
INCLUDE "macros/asserts.asm"
INCLUDE "macros/constants.asm"
INCLUDE "macros/code.asm"
INCLUDE "macros/data.asm"
INCLUDE "macros/scripts.asm"
INCLUDE "macros/text.asm"
INCLUDE "macros/wram.asm"
